/* ═══════════════════════════════════════════════════════════════════════════
   Public agenda data — official events, plenary sessions, committees,
   council meetings, and institutional calendar items.
   Seed data for 2026-04-10.
   ═══════════════════════════════════════════════════════════════════════════ */

export type AgendaEventType =
  | "pleno"
  | "comision"
  | "consejo-ministros"
  | "parlamento-ccaa"
  | "boe"
  | "comparecencia"
  | "elecciones"
  | "ue"
  | "otro";

export interface AgendaEvent {
  id: string;
  title: string;
  summary: string;
  eventType: AgendaEventType;
  date: string; // ISO date
  time?: string;
  endDate?: string;
  territorySlugs: string[];
  partySlugs: string[];
  politicianSlugs: string[];
  institution: string;
  sourceUrl?: string;
  status: "programado" | "en-curso" | "finalizado" | "aplazado";
}

export const eventTypeLabels: Record<AgendaEventType, string> = {
  pleno: "Pleno",
  comision: "Comisión",
  "consejo-ministros": "Consejo de Ministros",
  "parlamento-ccaa": "Parlamento autonómico",
  boe: "BOE",
  comparecencia: "Comparecencia",
  elecciones: "Elecciones",
  ue: "Unión Europea",
  otro: "Otro",
};

export const eventTypeColors: Record<AgendaEventType, string> = {
  pleno: "#c8102e",
  comision: "#003da5",
  "consejo-ministros": "#1a1a2e",
  "parlamento-ccaa": "#009b3a",
  boe: "#9a7400",
  comparecencia: "#6b2d7b",
  elecciones: "#e30613",
  ue: "#003399",
  otro: "#8e8e9a",
};

export const agendaEvents: AgendaEvent[] = [
  // ── Past sessions (celebradas — with transcripts available) ───────────
  {
    id: "agenda-past-001",
    title: "Pleno del Congreso — Debate sobre el estado de la Nación",
    summary: "Debate sobre el estado de la Nación 2026. Aprobación de resoluciones sobre vivienda, empleo y transición energética. Transcripción disponible.",
    eventType: "pleno",
    date: "2026-03-25",
    time: "09:00",
    endDate: "2026-03-25",
    territorySlugs: ["espana"],
    partySlugs: ["psoe", "pp", "vox", "sumar", "erc", "eh-bildu", "pnv", "junts"],
    politicianSlugs: ["pedro-sanchez", "miguel-tellado", "santiago-abascal", "yolanda-diaz"],
    institution: "Congreso de los Diputados",
    sourceUrl: "https://www.congreso.es/public_oficiales/L15/CONG/DS/PL/DSCD-15-PL-142.PDF",
    status: "finalizado",
  },
  {
    id: "agenda-past-002",
    title: "Pleno del Congreso — Sesión de control al Gobierno",
    summary: "Control con preguntas sobre financiación autonómica, empleo y fondos NGEU. Moción sobre Canarias rechazada. Transcripción disponible.",
    eventType: "pleno",
    date: "2026-03-26",
    time: "09:00",
    territorySlugs: ["espana", "canarias"],
    partySlugs: ["psoe", "pp", "vox", "sumar"],
    politicianSlugs: ["pedro-sanchez", "alberto-nunez-feijoo"],
    institution: "Congreso de los Diputados",
    sourceUrl: "https://www.congreso.es/public_oficiales/L15/CONG/DS/PL/DSCD-15-PL-143.PDF",
    status: "finalizado",
  },
  {
    id: "agenda-past-003",
    title: "Pleno del Senado — Ley de Inteligencia Artificial",
    summary: "Aprobación del Proyecto de Ley de regulación de la IA. Enmiendas PP sobre protección PYMES aprobadas parcialmente. Transcripción disponible.",
    eventType: "pleno",
    date: "2026-03-27",
    time: "10:00",
    territorySlugs: ["espana"],
    partySlugs: ["psoe", "pp", "vox", "sumar", "pnv"],
    politicianSlugs: ["pedro-rollan", "eva-granados"],
    institution: "Senado",
    sourceUrl: "https://www.senado.es/legis15/publicaciones/pdf/senado/ds/DS_P_15_078.PDF",
    status: "finalizado",
  },
  {
    id: "agenda-past-004",
    title: "Parlament de Catalunya — Pleno sobre presupuestos 2026",
    summary: "Aprobación presupuestos Generalitat 2026. Sanidad +8%, educación +6%, vivienda +15%. Transcripción disponible.",
    eventType: "parlamento-ccaa",
    date: "2026-03-28",
    time: "10:00",
    territorySlugs: ["cataluna"],
    partySlugs: ["psoe", "erc", "junts"],
    politicianSlugs: [],
    institution: "Parlament de Catalunya",
    sourceUrl: "https://www.parlament.cat/web/documentacio/diari-sessions/index.html",
    status: "finalizado",
  },
  {
    id: "agenda-past-005",
    title: "Comisión de Economía — Comparecencia Gobernador Banco de España",
    summary: "Comparecencia sobre estabilidad financiera, crédito a empresas y tipos de interés BCE. Transcripción disponible.",
    eventType: "comision",
    date: "2026-03-31",
    time: "10:00",
    territorySlugs: ["espana"],
    partySlugs: ["psoe", "pp", "sumar"],
    politicianSlugs: [],
    institution: "Congreso — Comisión de Economía",
    sourceUrl: "https://www.congreso.es/public_oficiales/L15/CONG/DS/CO/DSCD-15-CO-45.PDF",
    status: "finalizado",
  },
  {
    id: "agenda-past-006",
    title: "Pleno del Congreso — PNL Vivienda y Ley Crea y Crece",
    summary: "PNL sobre alquiler (aprobada), Kit Digital (aprobada), Crea y Crece (aprobada). Convalidación RDL DANA. Transcripción disponible.",
    eventType: "pleno",
    date: "2026-04-01",
    time: "09:00",
    territorySlugs: ["espana", "comunitat-valenciana"],
    partySlugs: ["psoe", "pp", "vox", "sumar", "erc", "eh-bildu", "pnv"],
    politicianSlugs: ["pedro-sanchez", "cuca-gamarra"],
    institution: "Congreso de los Diputados",
    sourceUrl: "https://www.congreso.es/public_oficiales/L15/CONG/DS/PL/DSCD-15-PL-144.PDF",
    status: "finalizado",
  },
  {
    id: "agenda-past-007",
    title: "Parlamento de Andalucía — Control al Gobierno andaluz",
    summary: "Control sobre gestión hídrica, sequía, Plan Hidrológico y listas de espera sanitarias. Transcripción disponible.",
    eventType: "parlamento-ccaa",
    date: "2026-04-02",
    time: "10:00",
    territorySlugs: ["andalucia"],
    partySlugs: ["pp", "psoe", "vox"],
    politicianSlugs: [],
    institution: "Parlamento de Andalucía",
    sourceUrl: "https://www.parlamentodeandalucia.es/webdinamica/portal-web-parlamento/recursosdeinformacion/diariodesesiones.do",
    status: "finalizado",
  },
  {
    id: "agenda-past-008",
    title: "Comisión de Hacienda — Informe del Tribunal de Cuentas",
    summary: "Informe anual TCU sobre Cuenta General 2025. Hallazgos en contratación pública y ejecución NGEU. Transcripción disponible.",
    eventType: "comision",
    date: "2026-04-03",
    time: "10:30",
    territorySlugs: ["espana"],
    partySlugs: ["psoe", "pp", "sumar"],
    politicianSlugs: [],
    institution: "Congreso — Comisión de Hacienda",
    sourceUrl: "https://www.congreso.es/public_oficiales/L15/CONG/DS/CO/DSCD-15-CO-46.PDF",
    status: "finalizado",
  },
  {
    id: "agenda-past-009",
    title: "Pleno del Congreso — Sesión de control al Gobierno",
    summary: "Control sobre política energética, reindustrialización, PERTE, pensiones y relación con Marruecos. Transcripción disponible.",
    eventType: "pleno",
    date: "2026-04-08",
    time: "09:00",
    territorySlugs: ["espana"],
    partySlugs: ["psoe", "pp", "vox", "sumar"],
    politicianSlugs: ["pedro-sanchez", "alberto-nunez-feijoo", "santiago-abascal"],
    institution: "Congreso de los Diputados",
    sourceUrl: "https://www.congreso.es/public_oficiales/L15/CONG/DS/PL/DSCD-15-PL-145.PDF",
    status: "finalizado",
  },

  // ── Finalized 9–10 April ───────────────────────────────────────────────
  {
    id: "agenda-past-010",
    title: "Pleno del Congreso — Debate de política general",
    summary: "Debate sobre política general: reforma fiscal, modelo territorial, relaciones UE. Aprobada PNL sobre reforma de financiación autonómica. Transcripción disponible.",
    eventType: "pleno",
    date: "2026-04-09",
    time: "09:00",
    territorySlugs: ["espana"],
    partySlugs: ["psoe", "pp", "vox", "sumar", "erc", "pnv"],
    politicianSlugs: ["pedro-sanchez", "miguel-tellado", "santiago-abascal", "yolanda-diaz"],
    institution: "Congreso de los Diputados",
    sourceUrl: "https://www.congreso.es/public_oficiales/L15/CONG/DS/PL/DSCD-15-PL-146.PDF",
    status: "finalizado",
  },
  {
    id: "agenda-past-011",
    title: "Consejo de Ministros — RDL vivienda y protección social",
    summary: "Aprobación del RDL 6/2026 de medidas urgentes de vivienda: ampliación bono alquiler, ayudas rehabilitación y movilización de vivienda vacía.",
    eventType: "consejo-ministros",
    date: "2026-04-09",
    time: "10:30",
    territorySlugs: ["espana"],
    partySlugs: ["psoe"],
    politicianSlugs: ["pedro-sanchez"],
    institution: "Gobierno de España",
    status: "finalizado",
  },
  {
    id: "agenda-past-012",
    title: "Comisión de Transición Ecológica — Comparecencia Ministra",
    summary: "Comparecencia de la Ministra sobre Plan Nacional de Adaptación al Cambio Climático y ejecución de fondos PERTE de descarbonización.",
    eventType: "comision",
    date: "2026-04-10",
    time: "10:00",
    territorySlugs: ["espana"],
    partySlugs: ["psoe", "pp", "sumar", "vox"],
    politicianSlugs: [],
    institution: "Congreso — Comisión de Transición Ecológica",
    sourceUrl: "https://www.congreso.es/public_oficiales/L15/CONG/DS/CO/DSCD-15-CO-47.PDF",
    status: "finalizado",
  },
  {
    id: "agenda-past-013",
    title: "Asamblea de Madrid — Pleno ordinario",
    summary: "Debate sobre presupuestos de la CAM 2026, inversión en metro, sanidad pública y política fiscal. PNL sobre vivienda rechazada.",
    eventType: "parlamento-ccaa",
    date: "2026-04-10",
    time: "10:00",
    territorySlugs: ["madrid"],
    partySlugs: ["pp", "psoe", "vox", "sumar"],
    politicianSlugs: [],
    institution: "Asamblea de Madrid",
    sourceUrl: "https://www.asambleamadrid.es/servicios/publicaciones/diario-de-sesiones",
    status: "finalizado",
  },

  // ── Upcoming events (programados) ─────────────────────────────────────
  {
    id: "agenda-001",
    title: "Pleno del Senado — Ley de Familias y mociones",
    summary: "Debate de enmiendas a la Ley de Familias. Votación de mociones sobre despoblación, financiación autonómica y emergencia climática.",
    eventType: "pleno",
    date: "2026-04-14",
    time: "10:00",
    territorySlugs: ["espana"],
    partySlugs: ["psoe", "pp", "pnv", "erc", "vox"],
    politicianSlugs: [],
    institution: "Senado",
    sourceUrl: "https://www.senado.es/legis15/agenda",
    status: "programado",
  },
  {
    id: "agenda-002",
    title: "Consejo de Ministros",
    summary: "Sesión ordinaria del Consejo de Ministros. Aprobación prevista de medidas sobre mercado eléctrico y plan de empleo juvenil.",
    eventType: "consejo-ministros",
    date: "2026-04-14",
    time: "10:30",
    territorySlugs: ["espana"],
    partySlugs: ["psoe", "sumar"],
    politicianSlugs: ["pedro-sanchez", "yolanda-diaz"],
    institution: "La Moncloa",
    sourceUrl: "https://www.lamoncloa.gob.es/consejodeministros/paginas/index.aspx",
    status: "programado",
  },
  {
    id: "agenda-003",
    title: "Comisión de Presupuestos — Comparecencia del Ministro de Hacienda",
    summary: "Comparecencia sobre la ejecución presupuestaria del primer trimestre de 2026 y previsiones de ingresos fiscales. Transcripción disponible.",
    eventType: "comision",
    date: "2026-04-10",
    time: "10:00",
    territorySlugs: ["espana"],
    partySlugs: ["psoe", "pp"],
    politicianSlugs: ["pedro-sanchez"],
    institution: "Congreso — Comisión de Presupuestos",
    sourceUrl: "https://www.congreso.es/public_oficiales/L15/CONG/DS/CO/DSCD-15-CO-48.PDF",
    status: "finalizado",
  },
  {
    id: "agenda-004",
    title: "Pleno del Senado — Moción sobre financiación autonómica",
    summary: "Moción del GP Popular sobre reforma de financiación autonómica. Rechazada por mayoría progresista. Transcripción disponible.",
    eventType: "pleno",
    date: "2026-04-10",
    time: "09:00",
    territorySlugs: ["espana", "cataluna", "comunitat-valenciana", "andalucia"],
    partySlugs: ["pp", "psoe", "pnv", "erc"],
    politicianSlugs: [],
    institution: "Senado",
    sourceUrl: "https://www.senado.es/legis15/publicaciones/pdf/senado/ds/DS_P_15_079.PDF",
    status: "finalizado",
  },
  {
    id: "agenda-005",
    title: "Parlament de Catalunya — Pleno ordinario",
    summary: "Debate sobre ley de vivienda catalana y comparecencia del Conseller d'Economia sobre impacto del turismo. Transcripción disponible.",
    eventType: "parlamento-ccaa",
    date: "2026-04-10",
    time: "10:00",
    territorySlugs: ["cataluna"],
    partySlugs: ["psoe", "junts", "erc"],
    politicianSlugs: ["gabriel-rufian"],
    institution: "Parlament de Catalunya",
    sourceUrl: "https://www.parlament.cat/web/documentacio/diari-sessions/index.html",
    status: "finalizado",
  },
  {
    id: "agenda-006",
    title: "Publicación BOE — Nuevas medidas DANA Comunitat Valenciana",
    summary: "Entrada en vigor del RDL de medidas extraordinarias para la reconstrucción de zonas afectadas por la DANA en la Comunitat Valenciana.",
    eventType: "boe",
    date: "2026-04-11",
    territorySlugs: ["comunitat-valenciana", "espana"],
    partySlugs: ["psoe", "pp"],
    politicianSlugs: [],
    institution: "BOE",
    sourceUrl: "https://www.boe.es/",
    status: "programado",
  },
  {
    id: "agenda-007",
    title: "Comparecencia del Presidente del Gobierno en el Congreso",
    summary: "Comparecencia extraordinaria de Pedro Sánchez sobre la situación económica y las negociaciones con la UE sobre los fondos NextGenerationEU.",
    eventType: "comparecencia",
    date: "2026-04-14",
    time: "12:00",
    territorySlugs: ["espana"],
    partySlugs: ["psoe"],
    politicianSlugs: ["pedro-sanchez"],
    institution: "Congreso de los Diputados",
    status: "programado",
  },
  {
    id: "agenda-008",
    title: "Parlamento Vasco — Debate sobre autogobierno",
    summary: "Debate sobre la propuesta de actualización del Estatuto de Gernika y el nuevo marco de relaciones con el Estado.",
    eventType: "parlamento-ccaa",
    date: "2026-04-14",
    time: "09:30",
    territorySlugs: ["pais-vasco"],
    partySlugs: ["pnv", "eh-bildu", "psoe"],
    politicianSlugs: ["mertxe-aizpurua"],
    institution: "Parlamento Vasco",
    status: "programado",
  },
  {
    id: "agenda-009",
    title: "Comisión de Asuntos Exteriores — Semestre Europeo",
    summary: "Debate sobre las recomendaciones del Semestre Europeo 2026 para España y el Plan Nacional de Reformas.",
    eventType: "ue",
    date: "2026-04-15",
    time: "16:00",
    territorySlugs: ["espana"],
    partySlugs: ["psoe", "pp", "sumar"],
    politicianSlugs: [],
    institution: "Congreso — Comisión de Asuntos Exteriores",
    status: "programado",
  },
  {
    id: "agenda-010",
    title: "Parlamento de Andalucía — Debate sobre el Plan Hidrológico",
    summary: "Sesión extraordinaria sobre el Plan Hidrológico del Guadalquivir y medidas contra la sequía en el territorio andaluz.",
    eventType: "parlamento-ccaa",
    date: "2026-04-15",
    time: "10:00",
    territorySlugs: ["andalucia"],
    partySlugs: ["pp", "psoe", "vox"],
    politicianSlugs: [],
    institution: "Parlamento de Andalucía",
    status: "programado",
  },
  {
    id: "agenda-011",
    title: "Consejo de Ministros extraordinario — Fondo de Reconstrucción",
    summary: "Aprobación del nuevo tramo del Fondo de Reconstrucción y medidas de apoyo a pymes afectadas por la DANA.",
    eventType: "consejo-ministros",
    date: "2026-04-16",
    time: "11:00",
    territorySlugs: ["espana", "comunitat-valenciana"],
    partySlugs: ["psoe", "sumar"],
    politicianSlugs: ["pedro-sanchez", "yolanda-diaz"],
    institution: "La Moncloa",
    status: "programado",
  },
  {
    id: "agenda-012",
    title: "Asamblea de Madrid — Control al Gobierno regional",
    summary: "Sesión de control con preguntas orales al Gobierno de la Comunidad de Madrid sobre transporte y vivienda.",
    eventType: "parlamento-ccaa",
    date: "2026-04-16",
    time: "10:00",
    territorySlugs: ["madrid"],
    partySlugs: ["pp", "psoe", "sumar", "vox"],
    politicianSlugs: [],
    institution: "Asamblea de Madrid",
    status: "programado",
  },
  {
    id: "agenda-013",
    title: "Pleno del Congreso — Votación Ley de Vivienda",
    summary: "Votación final del Proyecto de Ley de reforma integral de la Ley de Vivienda con enmiendas del Senado.",
    eventType: "pleno",
    date: "2026-04-17",
    time: "09:00",
    territorySlugs: ["espana"],
    partySlugs: ["psoe", "pp", "sumar", "erc", "eh-bildu", "pnv"],
    politicianSlugs: ["pedro-sanchez", "yolanda-diaz", "ione-belarra"],
    institution: "Congreso de los Diputados",
    status: "programado",
  },
  {
    id: "agenda-014",
    title: "Parlamento de Canarias — Presupuestos 2027",
    summary: "Inicio del debate sobre el Proyecto de Ley de Presupuestos Generales de Canarias para 2027.",
    eventType: "parlamento-ccaa",
    date: "2026-04-17",
    time: "10:00",
    territorySlugs: ["canarias"],
    partySlugs: ["coalicion-canaria", "pp", "psoe"],
    politicianSlugs: [],
    institution: "Parlamento de Canarias",
    status: "programado",
  },

  // ── CCAA plenaries (remaining communities) ───────────────────────────
  {
    id: "agenda-ccaa-001",
    title: "Cortes de Aragón — Debate sobre política industrial",
    summary: "Sesión plenaria sobre el plan de reindustrialización de Aragón y atracción de inversión extranjera en el sector automovilístico.",
    eventType: "parlamento-ccaa",
    date: "2026-04-13",
    time: "10:00",
    territorySlugs: ["aragon"],
    partySlugs: ["pp", "vox"],
    politicianSlugs: [],
    institution: "Cortes de Aragón",
    status: "programado",
  },
  {
    id: "agenda-ccaa-002",
    title: "Junta General del Principado — Control al Gobierno",
    summary: "Sesión de control al Gobierno del Principado de Asturias con preguntas sobre política sanitaria, demografía y transición energética.",
    eventType: "parlamento-ccaa",
    date: "2026-04-14",
    time: "10:00",
    territorySlugs: ["asturias"],
    partySlugs: ["psoe", "pp", "sumar"],
    politicianSlugs: [],
    institution: "Junta General del Principado de Asturias",
    status: "programado",
  },
  {
    id: "agenda-ccaa-003",
    title: "Parlament de les Illes Balears — Ley de turismo sostenible",
    summary: "Debate y toma en consideración de la proposición de ley de turismo sostenible y regulación de la vivienda vacacional.",
    eventType: "parlamento-ccaa",
    date: "2026-04-15",
    time: "10:00",
    territorySlugs: ["illes-balears"],
    partySlugs: ["pp", "vox"],
    politicianSlugs: [],
    institution: "Parlament de les Illes Balears",
    status: "programado",
  },
  {
    id: "agenda-ccaa-004",
    title: "Parlamento de Cantabria — Presupuestos 2027",
    summary: "Inicio del debate sobre el Proyecto de Ley de Presupuestos Generales de Cantabria para 2027.",
    eventType: "parlamento-ccaa",
    date: "2026-04-16",
    time: "10:00",
    territorySlugs: ["cantabria"],
    partySlugs: ["pp", "vox"],
    politicianSlugs: [],
    institution: "Parlamento de Cantabria",
    status: "programado",
  },
  {
    id: "agenda-ccaa-005",
    title: "Cortes de Castilla y León — Plan de despoblación",
    summary: "Debate monográfico sobre el Plan Integral contra la Despoblación y medidas de cohesión territorial.",
    eventType: "parlamento-ccaa",
    date: "2026-04-20",
    time: "10:00",
    territorySlugs: ["castilla-y-leon"],
    partySlugs: ["pp", "vox"],
    politicianSlugs: [],
    institution: "Cortes de Castilla y León",
    status: "programado",
  },
  {
    id: "agenda-ccaa-006",
    title: "Cortes de Castilla-La Mancha — Ley de agua",
    summary: "Debate sobre la Ley del Agua de Castilla-La Mancha y la gestión del trasvase Tajo-Segura.",
    eventType: "parlamento-ccaa",
    date: "2026-04-21",
    time: "10:00",
    territorySlugs: ["castilla-la-mancha"],
    partySlugs: ["psoe", "pp"],
    politicianSlugs: [],
    institution: "Cortes de Castilla-La Mancha",
    status: "programado",
  },
  {
    id: "agenda-ccaa-007",
    title: "Asamblea de Extremadura — Plan de infraestructuras",
    summary: "Pleno extraordinario sobre el Plan de Infraestructuras de Extremadura: tren de alta velocidad y conexiones viarias.",
    eventType: "parlamento-ccaa",
    date: "2026-04-22",
    time: "10:00",
    territorySlugs: ["extremadura"],
    partySlugs: ["pp", "vox"],
    politicianSlugs: [],
    institution: "Asamblea de Extremadura",
    status: "programado",
  },
  {
    id: "agenda-ccaa-008",
    title: "Parlamento de Galicia — Debate sobre pesca",
    summary: "Debate monográfico sobre la política pesquera gallega, acuicultura y la reforma de la Política Pesquera Común europea.",
    eventType: "parlamento-ccaa",
    date: "2026-04-23",
    time: "10:00",
    territorySlugs: ["galicia"],
    partySlugs: ["pp", "bng", "psoe"],
    politicianSlugs: [],
    institution: "Parlamento de Galicia",
    status: "programado",
  },
  {
    id: "agenda-ccaa-009",
    title: "Asamblea Regional de Murcia — Mar Menor",
    summary: "Sesión plenaria sobre la protección y restauración del Mar Menor y el plan de vertidos cero.",
    eventType: "parlamento-ccaa",
    date: "2026-04-24",
    time: "10:00",
    territorySlugs: ["murcia"],
    partySlugs: ["pp", "vox", "psoe"],
    politicianSlugs: [],
    institution: "Asamblea Regional de Murcia",
    status: "programado",
  },
  {
    id: "agenda-ccaa-010",
    title: "Parlamento de Navarra — Autogobierno",
    summary: "Debate sobre la actualización del Convenio Económico y las competencias de autogobierno de la Comunidad Foral.",
    eventType: "parlamento-ccaa",
    date: "2026-04-27",
    time: "10:00",
    territorySlugs: ["navarra"],
    partySlugs: ["psoe", "eh-bildu", "pnv"],
    politicianSlugs: [],
    institution: "Parlamento de Navarra",
    status: "programado",
  },
  {
    id: "agenda-ccaa-011",
    title: "Parlamento de La Rioja — Control al Gobierno",
    summary: "Sesión de control al Gobierno de La Rioja con preguntas sobre viticultura, demografía y servicios públicos.",
    eventType: "parlamento-ccaa",
    date: "2026-04-28",
    time: "10:00",
    territorySlugs: ["la-rioja"],
    partySlugs: ["pp", "psoe"],
    politicianSlugs: [],
    institution: "Parlamento de La Rioja",
    status: "programado",
  },
  {
    id: "agenda-ccaa-012",
    title: "Corts Valencianes — Reconstrucción DANA",
    summary: "Pleno monográfico sobre el estado de la reconstrucción tras la DANA, ayudas a damnificados y plan de resiliencia hídrica.",
    eventType: "parlamento-ccaa",
    date: "2026-04-29",
    time: "10:00",
    territorySlugs: ["comunitat-valenciana"],
    partySlugs: ["pp", "vox", "psoe"],
    politicianSlugs: [],
    institution: "Corts Valencianes",
    status: "programado",
  },
  {
    id: "agenda-ccaa-013",
    title: "Asamblea de Ceuta — Pleno ordinario",
    summary: "Pleno ordinario de la Asamblea de Ceuta con debate sobre política migratoria, comercio transfronterizo y servicios públicos.",
    eventType: "parlamento-ccaa",
    date: "2026-04-30",
    time: "10:00",
    territorySlugs: ["ceuta"],
    partySlugs: ["pp", "psoe"],
    politicianSlugs: [],
    institution: "Asamblea de Ceuta",
    status: "programado",
  },
  {
    id: "agenda-ccaa-014",
    title: "Asamblea de Melilla — Pleno ordinario",
    summary: "Pleno ordinario de la Asamblea de Melilla con debate sobre fronteras, empleo juvenil y vivienda.",
    eventType: "parlamento-ccaa",
    date: "2026-05-04",
    time: "10:00",
    territorySlugs: ["melilla"],
    partySlugs: ["pp", "psoe"],
    politicianSlugs: [],
    institution: "Asamblea de Melilla",
    status: "programado",
  },

  // ── Ministerial commissions ──────────────────────────────────────────
  {
    id: "agenda-min-001",
    title: "Comisión de Sanidad — Plan Nacional de Salud Mental",
    summary: "Debate sobre el Plan Nacional de Salud Mental 2026-2030 y dotación presupuestaria para atención primaria psicológica.",
    eventType: "comision",
    date: "2026-04-13",
    time: "09:30",
    territorySlugs: ["espana"],
    partySlugs: ["psoe", "pp", "sumar"],
    politicianSlugs: [],
    institution: "Congreso — Comisión de Sanidad",
    status: "programado",
  },
  {
    id: "agenda-min-002",
    title: "Comisión de Educación — Reforma curricular",
    summary: "Comparecencia de la Ministra de Educación sobre la reforma curricular de Bachillerato y las evaluaciones PISA 2025.",
    eventType: "comision",
    date: "2026-04-14",
    time: "16:00",
    territorySlugs: ["espana"],
    partySlugs: ["psoe", "pp", "sumar", "vox"],
    politicianSlugs: [],
    institution: "Congreso — Comisión de Educación",
    status: "programado",
  },
  {
    id: "agenda-min-003",
    title: "Comisión de Transportes — Corredor Mediterráneo",
    summary: "Debate sobre el avance de las obras del Corredor Mediterráneo ferroviario y plazos de ejecución 2026-2030.",
    eventType: "comision",
    date: "2026-04-20",
    time: "10:00",
    territorySlugs: ["espana", "comunitat-valenciana", "cataluna", "murcia", "andalucia"],
    partySlugs: ["psoe", "pp", "sumar", "erc"],
    politicianSlugs: [],
    institution: "Congreso — Comisión de Transportes",
    status: "programado",
  },
  {
    id: "agenda-min-004",
    title: "Comisión de Trabajo — Reforma mercado laboral",
    summary: "Debate sobre el impacto de la reforma laboral en la temporalidad y la negociación colectiva sectorial.",
    eventType: "comision",
    date: "2026-04-21",
    time: "09:30",
    territorySlugs: ["espana"],
    partySlugs: ["psoe", "pp", "sumar", "eh-bildu", "erc"],
    politicianSlugs: ["yolanda-diaz"],
    institution: "Congreso — Comisión de Trabajo",
    status: "programado",
  },
  {
    id: "agenda-min-005",
    title: "Comisión de Interior — Seguridad fronteriza",
    summary: "Comparecencia del Ministro del Interior sobre seguridad en las fronteras de Ceuta y Melilla y cooperación con Marruecos.",
    eventType: "comision",
    date: "2026-04-22",
    time: "10:00",
    territorySlugs: ["espana", "ceuta", "melilla"],
    partySlugs: ["psoe", "pp", "vox"],
    politicianSlugs: [],
    institution: "Congreso — Comisión de Interior",
    status: "programado",
  },
  {
    id: "agenda-min-006",
    title: "Comisión de Defensa — Presupuesto OTAN",
    summary: "Debate sobre el cumplimiento del compromiso de gasto del 2% del PIB en defensa y la hoja de ruta hacia 2030.",
    eventType: "comision",
    date: "2026-04-27",
    time: "10:00",
    territorySlugs: ["espana"],
    partySlugs: ["psoe", "pp", "vox", "sumar"],
    politicianSlugs: [],
    institution: "Congreso — Comisión de Defensa",
    status: "programado",
  },
  {
    id: "agenda-min-007",
    title: "Comisión de Transición Ecológica — Energías renovables",
    summary: "Debate sobre el PNIEC actualizado, subastas de renovables y almacenamiento energético.",
    eventType: "comision",
    date: "2026-04-28",
    time: "09:30",
    territorySlugs: ["espana"],
    partySlugs: ["psoe", "pp", "sumar", "erc"],
    politicianSlugs: [],
    institution: "Congreso — Comisión de Transición Ecológica",
    status: "programado",
  },
  {
    id: "agenda-min-008",
    title: "Comisión de Ciencia — Estrategia I+D+i",
    summary: "Comparecencia sobre la Estrategia Española de Ciencia, Tecnología e Innovación y la ejecución de fondos NGEU para I+D.",
    eventType: "comision",
    date: "2026-05-04",
    time: "10:00",
    territorySlugs: ["espana"],
    partySlugs: ["psoe", "pp", "sumar"],
    politicianSlugs: [],
    institution: "Congreso — Comisión de Ciencia",
    status: "programado",
  },
  {
    id: "agenda-min-009",
    title: "Comisión de Vivienda — Vivienda social",
    summary: "Debate sobre el parque público de vivienda social, el plan 20.000 viviendas y la regulación del alquiler de temporada.",
    eventType: "comision",
    date: "2026-05-05",
    time: "09:30",
    territorySlugs: ["espana"],
    partySlugs: ["psoe", "pp", "sumar", "eh-bildu"],
    politicianSlugs: [],
    institution: "Congreso — Comisión de Vivienda",
    status: "programado",
  },
  {
    id: "agenda-min-010",
    title: "Comisión de Agricultura — PAC y sequía",
    summary: "Debate sobre la aplicación de la PAC 2023-2027, medidas de apoyo a agricultores por la sequía y seguros agrarios.",
    eventType: "comision",
    date: "2026-05-06",
    time: "10:00",
    territorySlugs: ["espana", "andalucia", "castilla-la-mancha", "extremadura"],
    partySlugs: ["psoe", "pp", "vox"],
    politicianSlugs: [],
    institution: "Congreso — Comisión de Agricultura",
    status: "programado",
  },

  // ── Additional Consejo de Ministros ──────────────────────────────────
  {
    id: "agenda-cm-001",
    title: "Consejo de Ministros — Plan de choque energético",
    summary: "Aprobación del plan de choque contra los precios de la energía y medidas de eficiencia para industria y hogares.",
    eventType: "consejo-ministros",
    date: "2026-04-23",
    time: "10:30",
    territorySlugs: ["espana"],
    partySlugs: ["psoe", "sumar"],
    politicianSlugs: ["pedro-sanchez", "yolanda-diaz"],
    institution: "La Moncloa",
    status: "programado",
  },
  {
    id: "agenda-cm-002",
    title: "Consejo de Ministros — Estrategia Nacional de IA",
    summary: "Aprobación de la Estrategia Nacional de Inteligencia Artificial 2026-2030 y creación de la Agencia Española de Supervisión de IA.",
    eventType: "consejo-ministros",
    date: "2026-05-07",
    time: "10:30",
    territorySlugs: ["espana"],
    partySlugs: ["psoe", "sumar"],
    politicianSlugs: ["pedro-sanchez"],
    institution: "La Moncloa",
    status: "programado",
  },

  // ── Additional BOE publications ──────────────────────────────────────
  {
    id: "agenda-boe-001",
    title: "Publicación BOE — Ley de Inteligencia Artificial",
    summary: "Publicación de la Ley de regulación de la Inteligencia Artificial tras su aprobación por el Senado.",
    eventType: "boe",
    date: "2026-04-18",
    territorySlugs: ["espana"],
    partySlugs: ["psoe", "pp", "sumar"],
    politicianSlugs: [],
    institution: "BOE",
    sourceUrl: "https://www.boe.es/",
    status: "programado",
  },
  {
    id: "agenda-boe-002",
    title: "Publicación BOE — RDL de medidas fiscales verdes",
    summary: "Entrada en vigor del Real Decreto-Ley de fiscalidad verde: impuesto a envases plásticos y reforma del impuesto sobre hidrocarburos.",
    eventType: "boe",
    date: "2026-05-10",
    territorySlugs: ["espana"],
    partySlugs: ["psoe", "sumar"],
    politicianSlugs: [],
    institution: "BOE",
    sourceUrl: "https://www.boe.es/",
    status: "programado",
  },

  // ── Additional EU events ─────────────────────────────────────────────
  {
    id: "agenda-ue-001",
    title: "Ecofin — Reunión de Ministros de Economía y Finanzas",
    summary: "Reunión del Consejo de Asuntos Económicos y Financieros de la UE. Debate sobre las nuevas reglas fiscales y la Unión Bancaria.",
    eventType: "ue",
    date: "2026-04-21",
    time: "10:00",
    territorySlugs: ["espana"],
    partySlugs: ["psoe"],
    politicianSlugs: [],
    institution: "Consejo de la Unión Europea — Ecofin",
    status: "programado",
  },
  {
    id: "agenda-ue-002",
    title: "Consejo Europeo — Cumbre de Jefes de Estado y de Gobierno",
    summary: "Consejo Europeo de primavera. Agenda: competitividad industrial, defensa europea, ampliación y relaciones con EE.UU.",
    eventType: "ue",
    date: "2026-05-14",
    time: "09:00",
    endDate: "2026-05-15",
    territorySlugs: ["espana"],
    partySlugs: ["psoe"],
    politicianSlugs: ["pedro-sanchez"],
    institution: "Consejo Europeo",
    status: "programado",
  },

  // ── Additional plenos del Congreso ───────────────────────────────────
  {
    id: "agenda-cong-001",
    title: "Pleno del Congreso — Ley de Familias",
    summary: "Debate y votación del Proyecto de Ley de Familias: permisos parentales ampliados, familias monoparentales y conciliación.",
    eventType: "pleno",
    date: "2026-04-29",
    time: "09:00",
    territorySlugs: ["espana"],
    partySlugs: ["psoe", "pp", "sumar", "erc", "eh-bildu", "pnv"],
    politicianSlugs: ["pedro-sanchez", "yolanda-diaz"],
    institution: "Congreso de los Diputados",
    status: "programado",
  },
  {
    id: "agenda-cong-002",
    title: "Pleno del Congreso — Sesión de control al Gobierno",
    summary: "Sesión de control con preguntas orales sobre empleo, inmigración, vivienda y política exterior.",
    eventType: "pleno",
    date: "2026-05-13",
    time: "09:00",
    territorySlugs: ["espana"],
    partySlugs: ["psoe", "pp", "vox", "sumar", "erc", "pnv"],
    politicianSlugs: ["pedro-sanchez", "alberto-nunez-feijoo", "santiago-abascal"],
    institution: "Congreso de los Diputados",
    status: "programado",
  },

  // ── Additional pleno del Senado ──────────────────────────────────────
  {
    id: "agenda-sen-001",
    title: "Pleno del Senado — Ley de Familias y mociones",
    summary: "Debate de enmiendas a la Ley de Familias y votación de mociones sobre despoblación y financiación autonómica.",
    eventType: "pleno",
    date: "2026-05-12",
    time: "10:00",
    territorySlugs: ["espana"],
    partySlugs: ["psoe", "pp", "pnv", "erc", "vox"],
    politicianSlugs: [],
    institution: "Senado",
    status: "programado",
  },
];

/** Get events filtered by criteria */
export function getFilteredEvents(filters: {
  territorySlug?: string;
  partySlug?: string;
  eventType?: AgendaEventType;
  fromDate?: string;
  toDate?: string;
}): AgendaEvent[] {
  return agendaEvents.filter((event) => {
    if (filters.territorySlug && !event.territorySlugs.includes(filters.territorySlug)) return false;
    if (filters.partySlug && !event.partySlugs.includes(filters.partySlug)) return false;
    if (filters.eventType && event.eventType !== filters.eventType) return false;
    if (filters.fromDate && event.date < filters.fromDate) return false;
    if (filters.toDate && event.date > filters.toDate) return false;
    return true;
  });
}

/** Get upcoming events (from today) */
export function getUpcomingEvents(limit = 10): AgendaEvent[] {
  return [...agendaEvents]
    .filter((e) => e.status !== "finalizado")
    .sort((a, b) => a.date.localeCompare(b.date))
    .slice(0, limit);
}
