export interface FiscalInitiative {
  id: string;
  type: "deduccion-irpf" | "bonificacion-ibi" | "subvencion" | "exencion" | "programa";
  level: "ccaa" | "municipal";
  title: string;
  description: string;
  amount: string;
  requirements: string;
  icon: string;
}

// ---------------------------------------------------------------------------
// CCAA INITIATIVES
// ---------------------------------------------------------------------------

const CCAA_INITIATIVES: Record<string, FiscalInitiative[]> = {
  madrid: [
    {
      id: "mad-01",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Alquiler de vivienda para jóvenes menores de 35 años",
      description: "Deducción en el IRPF por arrendamiento de vivienda habitual para contribuyentes menores de 35 años en la Comunidad de Madrid.",
      amount: "Hasta 1.000 €",
      requirements: "Menor de 35 años, base imponible inferior a 25.620 €, contrato de arrendamiento registrado.",
      icon: "🏠",
    },
    {
      id: "mad-02",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Gastos educativos",
      description: "Deducción por gastos de escolaridad, enseñanza de idiomas y adquisición de vestuario escolar de hijos en etapas de educación básica.",
      amount: "Hasta 900 €",
      requirements: "Hijos escolarizados en centros autorizados, justificantes de gasto.",
      icon: "📚",
    },
    {
      id: "mad-03",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Hijos menores de 3 años",
      description: "Deducción por cada hijo menor de tres años que conviva con el contribuyente.",
      amount: "Hasta 600 €",
      requirements: "Hijo menor de 3 años, convivencia acreditada, base imponible inferior a 30.000 €.",
      icon: "👶",
    },
    {
      id: "mad-04",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Acogimiento no remunerado de mayores de 65 años",
      description: "Deducción por acoger en el domicilio habitual a personas mayores de 65 años sin contraprestación.",
      amount: "1.500 €",
      requirements: "Persona acogida mayor de 65 años, convivencia mínima de 183 días al año, sin parentesco directo.",
      icon: "🤝",
    },
    {
      id: "mad-05",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Inversión en vivienda habitual de nueva construcción",
      description: "Deducción por adquisición de vivienda habitual de nueva construcción en la Comunidad de Madrid.",
      amount: "10 %",
      requirements: "Vivienda de nueva construcción, primera adquisición, base imponible inferior a 30.000 €.",
      icon: "🏗️",
    },
    {
      id: "mad-06",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Donativos a fundaciones",
      description: "Deducción por donaciones a fundaciones que cumplan los requisitos de la Ley 49/2002 inscritas en la Comunidad de Madrid.",
      amount: "15 %",
      requirements: "Donación a fundación inscrita, justificante de la entidad receptora.",
      icon: "💝",
    },
  ],

  cataluna: [
    {
      id: "cat-01",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Nacimiento o adopción de hijos",
      description: "Deducción por nacimiento o adopción de un hijo durante el período impositivo en Cataluña.",
      amount: "300 € por hijo",
      requirements: "Nacimiento o adopción acreditados, convivencia con el hijo.",
      icon: "👶",
    },
    {
      id: "cat-02",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Alquiler de vivienda habitual",
      description: "Deducción por arrendamiento de la vivienda habitual para contribuyentes con rentas bajas en Cataluña.",
      amount: "Hasta 600 €",
      requirements: "Base imponible inferior a 20.000 € (individual), contrato registrado.",
      icon: "🏠",
    },
    {
      id: "cat-03",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Donativos a entidades de fomento de la lengua catalana",
      description: "Deducción por donaciones a entidades que fomenten el uso de la lengua catalana.",
      amount: "15 %",
      requirements: "Donación a entidad reconocida, justificante expedido por la entidad.",
      icon: "🗣️",
    },
    {
      id: "cat-04",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Rehabilitación de vivienda habitual",
      description: "Deducción por obras de rehabilitación de la vivienda habitual en Cataluña.",
      amount: "1,5 %",
      requirements: "Obras de rehabilitación acreditadas, vivienda habitual del contribuyente.",
      icon: "🔧",
    },
    {
      id: "cat-05",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Inversión por business angel en empresas",
      description: "Deducción por inversión en la adquisición de acciones o participaciones sociales de entidades de nueva o reciente creación.",
      amount: "30 %, hasta 6.000 €",
      requirements: "Empresa de nueva creación (menos de 3 años), participación inferior al 35 %, mantenimiento mínimo 3 años.",
      icon: "💼",
    },
  ],

  andalucia: [
    {
      id: "and-01",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Inversión en vivienda protegida",
      description: "Deducción por adquisición de vivienda protegida como vivienda habitual en Andalucía.",
      amount: "2 %",
      requirements: "Vivienda calificada como protegida, primera adquisición.",
      icon: "🏠",
    },
    {
      id: "and-02",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Alquiler de vivienda habitual para jóvenes",
      description: "Deducción por arrendamiento de vivienda habitual para menores de 35 años en Andalucía.",
      amount: "15 %, hasta 600 €",
      requirements: "Menor de 35 años, base imponible inferior a 19.000 €, contrato registrado.",
      icon: "🔑",
    },
    {
      id: "and-03",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Mejora de sostenibilidad de viviendas",
      description: "Deducción por inversiones en instalaciones de mejora de la sostenibilidad energética de la vivienda habitual.",
      amount: "15 %, hasta 600 €",
      requirements: "Instalaciones de energía renovable o mejora de eficiencia energética, factura acreditativa.",
      icon: "🌱",
    },
    {
      id: "and-04",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Adopción internacional",
      description: "Deducción por gastos derivados de la adopción internacional de menores.",
      amount: "600 €",
      requirements: "Adopción internacional acreditada, justificantes de gastos.",
      icon: "🌍",
    },
    {
      id: "and-05",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Familia numerosa",
      description: "Deducción por contribuyentes que ostenten el título de familia numerosa en Andalucía.",
      amount: "200-400 €",
      requirements: "Título de familia numerosa en vigor (general: 200 €, especial: 400 €).",
      icon: "👨‍👩‍👧‍👦",
    },
    {
      id: "and-06",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Discapacidad del contribuyente o familiar",
      description: "Deducción para contribuyentes con discapacidad o con ascendientes/descendientes con discapacidad a cargo.",
      amount: "100 € por persona",
      requirements: "Grado de discapacidad igual o superior al 33 %, certificado oficial.",
      icon: "♿",
    },
  ],

  valencia: [
    {
      id: "val-01",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Arrendamiento de vivienda habitual",
      description: "Deducción por cantidades destinadas al arrendamiento de la vivienda habitual en la Comunitat Valenciana.",
      amount: "20 %, hasta 800 €",
      requirements: "Contrato de arrendamiento registrado, base imponible inferior a 30.000 €.",
      icon: "🏠",
    },
    {
      id: "val-02",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Adquisición de primera vivienda para menores de 35 años",
      description: "Deducción por la compra de primera vivienda habitual para contribuyentes jóvenes.",
      amount: "5 %",
      requirements: "Menor de 35 años, primera vivienda habitual, escritura de compraventa.",
      icon: "🔑",
    },
    {
      id: "val-03",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Material escolar",
      description: "Deducción por la adquisición de material escolar para hijos en educación primaria y secundaria.",
      amount: "110 € por hijo",
      requirements: "Hijos matriculados en centros públicos o concertados, justificantes de compra.",
      icon: "✏️",
    },
    {
      id: "val-04",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Instalación de energías renovables",
      description: "Deducción por inversiones en instalaciones de autoconsumo de energía eléctrica o de aprovechamiento de energías renovables.",
      amount: "40 %, hasta 8.000 €",
      requirements: "Instalación en vivienda habitual, factura y certificado de instalación autorizada.",
      icon: "☀️",
    },
    {
      id: "val-05",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Custodia de hijos menores de 3 años",
      description: "Deducción por cantidades destinadas a la custodia en guarderías y centros de educación infantil de hijos menores de 3 años.",
      amount: "15 %, hasta 298 €",
      requirements: "Hijo menor de 3 años, centro autorizado, justificantes de pago.",
      icon: "👶",
    },
    {
      id: "val-06",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Donaciones medioambientales",
      description: "Deducción por donaciones destinadas a la protección del medio ambiente y el patrimonio natural valenciano.",
      amount: "25 %",
      requirements: "Donación a entidad medioambiental reconocida, justificante de la donación.",
      icon: "🌿",
    },
  ],

  "pais-vasco": [
    {
      id: "pvs-01",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Alquiler de vivienda habitual",
      description: "Deducción por arrendamiento de vivienda habitual en el País Vasco.",
      amount: "20 %, hasta 1.600 €",
      requirements: "Contrato de arrendamiento registrado, base imponible inferior a 30.000 €.",
      icon: "🏠",
    },
    {
      id: "pvs-02",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Inversión en vivienda habitual",
      description: "Deducción por cantidades destinadas a la adquisición de vivienda habitual en el País Vasco.",
      amount: "18 %, hasta 1.530 €",
      requirements: "Adquisición de vivienda habitual, préstamo hipotecario acreditado.",
      icon: "🏗️",
    },
    {
      id: "pvs-03",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Aportaciones a EPSV y planes de pensiones",
      description: "Deducción por aportaciones a Entidades de Previsión Social Voluntaria y planes de pensiones.",
      amount: "Hasta 5.000 €",
      requirements: "Aportaciones acreditadas a EPSV o planes de pensiones registrados.",
      icon: "💰",
    },
    {
      id: "pvs-04",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Familia numerosa",
      description: "Deducción por contribuyentes con título de familia numerosa en el País Vasco.",
      amount: "582-910 €",
      requirements: "Título de familia numerosa en vigor (general: 582 €, especial: 910 €).",
      icon: "👨‍👩‍👧‍👦",
    },
    {
      id: "pvs-05",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Discapacidad",
      description: "Deducción por discapacidad del contribuyente o de personas a su cargo.",
      amount: "727-1.216 €",
      requirements: "Grado de discapacidad igual o superior al 33 %, certificado oficial.",
      icon: "♿",
    },
    {
      id: "pvs-06",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Descendientes a cargo",
      description: "Deducción por cada descendiente que conviva con el contribuyente.",
      amount: "558-1.001 € por hijo",
      requirements: "Descendiente a cargo, convivencia acreditada, rentas del descendiente inferiores al mínimo.",
      icon: "👧",
    },
  ],

  navarra: [
    {
      id: "nav-01",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Inversión en vivienda habitual",
      description: "Deducción por cantidades destinadas a la adquisición o rehabilitación de vivienda habitual en Navarra.",
      amount: "15 %, hasta 900 €",
      requirements: "Vivienda habitual, préstamo hipotecario acreditado.",
      icon: "🏠",
    },
    {
      id: "nav-02",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Alquiler de vivienda habitual",
      description: "Deducción por arrendamiento de vivienda habitual en Navarra.",
      amount: "15 %, hasta 1.200 €",
      requirements: "Contrato de arrendamiento registrado, base imponible inferior a 30.000 €.",
      icon: "🔑",
    },
    {
      id: "nav-03",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Hijos menores de 3 años",
      description: "Deducción por cada hijo menor de 3 años que conviva con el contribuyente.",
      amount: "510 €",
      requirements: "Hijo menor de 3 años, convivencia acreditada.",
      icon: "👶",
    },
    {
      id: "nav-04",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Personas dependientes",
      description: "Deducción por cuidado de personas dependientes que convivan con el contribuyente.",
      amount: "1.024 €",
      requirements: "Persona dependiente a cargo, grado de dependencia reconocido oficialmente.",
      icon: "🤝",
    },
    {
      id: "nav-05",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Aportaciones a planes de pensiones",
      description: "Deducción por aportaciones a planes de pensiones y sistemas de previsión social en Navarra.",
      amount: "Hasta 3.500 €",
      requirements: "Aportaciones a planes registrados, justificante de la entidad gestora.",
      icon: "💰",
    },
  ],

  aragon: [
    {
      id: "ara-01",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Alquiler de vivienda habitual para jóvenes",
      description: "Deducción por arrendamiento de vivienda habitual para menores de 35 años en Aragón.",
      amount: "Hasta 450 €",
      requirements: "Menor de 35 años, contrato registrado, base imponible inferior a 15.000 €.",
      icon: "🏠",
    },
    {
      id: "ara-02",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Nacimiento o adopción del tercer hijo o sucesivos",
      description: "Deducción por nacimiento o adopción a partir del tercer hijo en Aragón.",
      amount: "500 €",
      requirements: "Nacimiento o adopción del tercer hijo o sucesivos, convivencia acreditada.",
      icon: "👶",
    },
    {
      id: "ara-03",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Gastos de guardería",
      description: "Deducción por gastos de guardería de hijos menores de 3 años en centros autorizados.",
      amount: "15 %",
      requirements: "Hijo menor de 3 años, guardería autorizada, justificantes de pago.",
      icon: "🧒",
    },
    {
      id: "ara-04",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Donaciones medioambientales",
      description: "Deducción por donaciones a entidades dedicadas a la protección del medio ambiente en Aragón.",
      amount: "20 %",
      requirements: "Donación a entidad medioambiental reconocida, justificante de la donación.",
      icon: "🌿",
    },
    {
      id: "ara-05",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Familia numerosa",
      description: "Deducción para contribuyentes con título de familia numerosa en Aragón.",
      amount: "200-400 €",
      requirements: "Título de familia numerosa en vigor (general: 200 €, especial: 400 €).",
      icon: "👨‍👩‍👧‍👦",
    },
  ],

  asturias: [
    {
      id: "ast-01",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Alquiler de vivienda habitual",
      description: "Deducción por arrendamiento de la vivienda habitual en el Principado de Asturias.",
      amount: "10 %, hasta 500 €",
      requirements: "Contrato registrado, base imponible inferior a 26.000 €.",
      icon: "🏠",
    },
    {
      id: "ast-02",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Familia numerosa",
      description: "Deducción para contribuyentes con título de familia numerosa en Asturias.",
      amount: "505-1.010 €",
      requirements: "Título de familia numerosa en vigor (general: 505 €, especial: 1.010 €).",
      icon: "👨‍👩‍👧‍👦",
    },
    {
      id: "ast-03",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Acogimiento no remunerado de mayores de 65 años",
      description: "Deducción por acogimiento no remunerado de personas mayores de 65 años.",
      amount: "253 €",
      requirements: "Persona acogida mayor de 65 años, convivencia mínima de 183 días.",
      icon: "🤝",
    },
    {
      id: "ast-04",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Partos múltiples",
      description: "Deducción por partos múltiples o adopción simultánea de dos o más menores.",
      amount: "505 €",
      requirements: "Parto múltiple o adopción simultánea acreditados.",
      icon: "👶",
    },
    {
      id: "ast-05",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Inversión en vivienda habitual protegida",
      description: "Deducción por inversión en vivienda habitual que tenga la calificación de protegida.",
      amount: "3 %",
      requirements: "Vivienda calificada como protegida, adquisición acreditada.",
      icon: "🏗️",
    },
  ],

  "illes-balears": [
    {
      id: "bal-01",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Arrendamiento de vivienda habitual para menores de 36 años",
      description: "Deducción por arrendamiento de vivienda habitual para jóvenes en las Illes Balears.",
      amount: "15 %, hasta 530 €",
      requirements: "Menor de 36 años, contrato registrado, base imponible inferior a 20.000 €.",
      icon: "🏠",
    },
    {
      id: "bal-02",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Gastos de material escolar",
      description: "Deducción por la adquisición de libros de texto y material escolar de los hijos.",
      amount: "100 € por hijo",
      requirements: "Hijos matriculados en educación obligatoria, justificantes de compra.",
      icon: "📚",
    },
    {
      id: "bal-03",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Mejora de sostenibilidad de la vivienda",
      description: "Deducción por inversiones en mejora de la sostenibilidad y eficiencia energética de la vivienda habitual.",
      amount: "50 %, hasta 10.000 €",
      requirements: "Obras de mejora energética acreditadas, certificado de eficiencia.",
      icon: "🌱",
    },
    {
      id: "bal-04",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Donativos a entidades de I+D+i",
      description: "Deducción por donaciones a entidades dedicadas a la investigación, desarrollo e innovación.",
      amount: "25 %",
      requirements: "Donación a entidad de I+D+i reconocida, justificante expedido.",
      icon: "🔬",
    },
    {
      id: "bal-05",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Discapacidad",
      description: "Deducción por discapacidad del contribuyente o personas a cargo en las Illes Balears.",
      amount: "80-150 €",
      requirements: "Grado de discapacidad igual o superior al 33 %, certificado oficial.",
      icon: "♿",
    },
  ],

  canarias: [
    {
      id: "can-01",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Nacimiento o adopción de hijos",
      description: "Deducción por nacimiento o adopción de hijos en Canarias.",
      amount: "200 € por hijo",
      requirements: "Nacimiento o adopción acreditados, convivencia con el hijo.",
      icon: "👶",
    },
    {
      id: "can-02",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Gastos de estudios",
      description: "Deducción por gastos de estudios en educación superior fuera de la isla de residencia.",
      amount: "1.700 €",
      requirements: "Estudios superiores fuera de la isla, justificantes de matrícula y desplazamiento.",
      icon: "🎓",
    },
    {
      id: "can-03",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Familia numerosa",
      description: "Deducción para contribuyentes con título de familia numerosa en Canarias.",
      amount: "200-400 €",
      requirements: "Título de familia numerosa en vigor (general: 200 €, especial: 400 €).",
      icon: "👨‍👩‍👧‍👦",
    },
    {
      id: "can-04",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Donaciones culturales",
      description: "Deducción por donaciones destinadas a la restauración y conservación del patrimonio cultural canario.",
      amount: "15 %",
      requirements: "Donación a entidad cultural reconocida, justificante de la donación.",
      icon: "🎭",
    },
    {
      id: "can-05",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Rehabilitación de vivienda habitual",
      description: "Deducción por obras de rehabilitación de la vivienda habitual en Canarias.",
      amount: "10 %",
      requirements: "Obras de rehabilitación acreditadas, vivienda habitual, licencia municipal.",
      icon: "🔧",
    },
  ],

  cantabria: [
    {
      id: "cnt-01",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Alquiler de vivienda habitual para jóvenes",
      description: "Deducción por arrendamiento de vivienda habitual para menores de 35 años en Cantabria.",
      amount: "10 %, hasta 300 €",
      requirements: "Menor de 35 años, contrato registrado, base imponible inferior a 22.000 €.",
      icon: "🏠",
    },
    {
      id: "cnt-02",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Gastos educativos",
      description: "Deducción por gastos de educación en centros autorizados de Cantabria.",
      amount: "15 %, hasta 500 €",
      requirements: "Hijos en educación obligatoria, justificantes de gasto.",
      icon: "📚",
    },
    {
      id: "cnt-03",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Cuidado de familiares",
      description: "Deducción por gastos en el cuidado de familiares dependientes.",
      amount: "100 €",
      requirements: "Familiar dependiente a cargo, convivencia acreditada.",
      icon: "🤝",
    },
    {
      id: "cnt-04",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Donativos a entidades sin ánimo de lucro",
      description: "Deducción por donaciones a fundaciones y entidades sin ánimo de lucro en Cantabria.",
      amount: "15 %",
      requirements: "Donación a entidad sin ánimo de lucro reconocida, justificante.",
      icon: "💝",
    },
    {
      id: "cnt-05",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Familia numerosa",
      description: "Deducción para contribuyentes con título de familia numerosa en Cantabria.",
      amount: "300-600 €",
      requirements: "Título de familia numerosa en vigor (general: 300 €, especial: 600 €).",
      icon: "👨‍👩‍👧‍👦",
    },
  ],

  "castilla-y-leon": [
    {
      id: "cyl-01",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Alquiler de vivienda habitual para jóvenes",
      description: "Deducción por arrendamiento de vivienda habitual para menores de 36 años en Castilla y León.",
      amount: "20 %, hasta 459 €",
      requirements: "Menor de 36 años, contrato registrado, base imponible inferior a 18.900 €.",
      icon: "🏠",
    },
    {
      id: "cyl-02",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Nacimiento o adopción de hijos",
      description: "Deducción por nacimiento o adopción de hijos en Castilla y León.",
      amount: "710-1.775 €",
      requirements: "Nacimiento o adopción acreditados (1er hijo: 710 €, 2do: 1.065 €, 3ro y siguientes: 1.775 €).",
      icon: "👶",
    },
    {
      id: "cyl-03",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Cuidado de hijos menores de 4 años",
      description: "Deducción por gastos de cuidado de hijos menores de 4 años por persona empleada del hogar o guardería.",
      amount: "30 %, hasta 322 €",
      requirements: "Hijo menor de 4 años, justificantes de gasto en cuidado.",
      icon: "🧒",
    },
    {
      id: "cyl-04",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Rehabilitación de vivienda",
      description: "Deducción por obras de rehabilitación y mejora de vivienda habitual en Castilla y León.",
      amount: "15 %",
      requirements: "Obras de rehabilitación acreditadas, licencia municipal.",
      icon: "🔧",
    },
    {
      id: "cyl-05",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Familia numerosa",
      description: "Deducción para contribuyentes con título de familia numerosa en Castilla y León.",
      amount: "500-1.000 €",
      requirements: "Título de familia numerosa en vigor (general: 500 €, especial: 1.000 €).",
      icon: "👨‍👩‍👧‍👦",
    },
  ],

  "castilla-la-mancha": [
    {
      id: "clm-01",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Nacimiento o adopción de hijos",
      description: "Deducción por nacimiento o adopción de hijos en Castilla-La Mancha.",
      amount: "100 €",
      requirements: "Nacimiento o adopción acreditados, convivencia con el hijo.",
      icon: "👶",
    },
    {
      id: "clm-02",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Discapacidad del contribuyente",
      description: "Deducción por discapacidad del contribuyente en Castilla-La Mancha.",
      amount: "300 €",
      requirements: "Grado de discapacidad igual o superior al 33 %, certificado oficial.",
      icon: "♿",
    },
    {
      id: "clm-03",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Alquiler de vivienda habitual para jóvenes",
      description: "Deducción por arrendamiento de vivienda habitual para menores de 36 años en Castilla-La Mancha.",
      amount: "15 %, hasta 450 €",
      requirements: "Menor de 36 años, contrato registrado, base imponible inferior a 12.500 €.",
      icon: "🏠",
    },
    {
      id: "clm-04",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Familia numerosa",
      description: "Deducción para contribuyentes con título de familia numerosa en Castilla-La Mancha.",
      amount: "150-300 €",
      requirements: "Título de familia numerosa en vigor (general: 150 €, especial: 300 €).",
      icon: "👨‍👩‍👧‍👦",
    },
    {
      id: "clm-05",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Donativos a entidades de cooperación",
      description: "Deducción por donaciones a ONG y entidades de cooperación internacional reconocidas.",
      amount: "15 %",
      requirements: "Donación a entidad de cooperación reconocida, justificante expedido.",
      icon: "🌍",
    },
  ],

  extremadura: [
    {
      id: "ext-01",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Alquiler de vivienda habitual para jóvenes",
      description: "Deducción por arrendamiento de vivienda habitual para menores de 36 años en Extremadura.",
      amount: "5 %, hasta 300 €",
      requirements: "Menor de 36 años, contrato registrado, base imponible inferior a 19.000 €.",
      icon: "🏠",
    },
    {
      id: "ext-02",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Trabajo dependiente",
      description: "Deducción por rendimientos del trabajo dependiente en Extremadura.",
      amount: "75 €",
      requirements: "Rendimientos del trabajo, base imponible inferior a 12.000 €.",
      icon: "💼",
    },
    {
      id: "ext-03",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Material escolar",
      description: "Deducción por la adquisición de material escolar de los hijos.",
      amount: "15 € por hijo",
      requirements: "Hijos en educación obligatoria, justificantes de compra.",
      icon: "✏️",
    },
    {
      id: "ext-04",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Acogimiento de menores",
      description: "Deducción por acogimiento familiar de menores en Extremadura.",
      amount: "250 €",
      requirements: "Acogimiento acreditado por la administración, convivencia mínima de 183 días.",
      icon: "🤝",
    },
    {
      id: "ext-05",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Familia numerosa",
      description: "Deducción para contribuyentes con título de familia numerosa en Extremadura.",
      amount: "200-400 €",
      requirements: "Título de familia numerosa en vigor (general: 200 €, especial: 400 €).",
      icon: "👨‍👩‍👧‍👦",
    },
  ],

  galicia: [
    {
      id: "gal-01",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Nacimiento o adopción de hijos",
      description: "Deducción por nacimiento o adopción de hijos en Galicia.",
      amount: "360-720 €",
      requirements: "Nacimiento o adopción acreditados (1er hijo: 360 €, 2do: 360 €, 3ro y siguientes: 720 €).",
      icon: "👶",
    },
    {
      id: "gal-02",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Alquiler de vivienda habitual para jóvenes",
      description: "Deducción por arrendamiento de vivienda habitual para menores de 35 años en Galicia.",
      amount: "20 %, hasta 600 €",
      requirements: "Menor de 35 años, contrato registrado, base imponible inferior a 22.000 €.",
      icon: "🏠",
    },
    {
      id: "gal-03",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Familia numerosa",
      description: "Deducción para contribuyentes con título de familia numerosa en Galicia.",
      amount: "250-500 €",
      requirements: "Título de familia numerosa en vigor (general: 250 €, especial: 500 €).",
      icon: "👨‍👩‍👧‍👦",
    },
    {
      id: "gal-04",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Gastos de guardería",
      description: "Deducción por gastos en escuelas infantiles de 0 a 3 años en Galicia.",
      amount: "30 %",
      requirements: "Hijo menor de 3 años, centro autorizado, justificantes de pago.",
      icon: "🧒",
    },
    {
      id: "gal-05",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Donativos a entidades sociales",
      description: "Deducción por donaciones a entidades de carácter social reconocidas en Galicia.",
      amount: "25 %",
      requirements: "Donación a entidad social reconocida, justificante expedido.",
      icon: "💝",
    },
  ],

  murcia: [
    {
      id: "mur-01",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Alquiler de vivienda habitual para jóvenes",
      description: "Deducción por arrendamiento de vivienda habitual para menores de 35 años en la Región de Murcia.",
      amount: "10 %, hasta 300 €",
      requirements: "Menor de 35 años, contrato registrado, base imponible inferior a 24.000 €.",
      icon: "🏠",
    },
    {
      id: "mur-02",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Inversión en vivienda habitual para menores de 35 años",
      description: "Deducción por adquisición de vivienda habitual para jóvenes en Murcia.",
      amount: "5 %",
      requirements: "Menor de 35 años, primera vivienda habitual, escritura de compraventa.",
      icon: "🏗️",
    },
    {
      id: "mur-03",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Gastos de guardería",
      description: "Deducción por gastos en guarderías y centros de educación infantil en Murcia.",
      amount: "20 %, hasta 400 €",
      requirements: "Hijo menor de 3 años, centro autorizado, justificantes de pago.",
      icon: "🧒",
    },
    {
      id: "mur-04",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Familia numerosa",
      description: "Deducción para contribuyentes con título de familia numerosa en Murcia.",
      amount: "200-400 €",
      requirements: "Título de familia numerosa en vigor (general: 200 €, especial: 400 €).",
      icon: "👨‍👩‍👧‍👦",
    },
    {
      id: "mur-05",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Donativos ecológicos",
      description: "Deducción por donaciones a entidades dedicadas a la protección del medio ambiente en Murcia.",
      amount: "20 %",
      requirements: "Donación a entidad ecológica reconocida, justificante de la donación.",
      icon: "🌿",
    },
  ],

  "la-rioja": [
    {
      id: "rio-01",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Nacimiento o adopción de hijos",
      description: "Deducción por nacimiento o adopción de hijos en La Rioja.",
      amount: "600 € primer hijo, 750 € segundo hijo",
      requirements: "Nacimiento o adopción acreditados, convivencia con el hijo.",
      icon: "👶",
    },
    {
      id: "rio-02",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Alquiler de vivienda habitual para jóvenes",
      description: "Deducción por arrendamiento de vivienda habitual para menores de 36 años en La Rioja.",
      amount: "10 %, hasta 300 €",
      requirements: "Menor de 36 años, contrato registrado, base imponible inferior a 18.030 €.",
      icon: "🏠",
    },
    {
      id: "rio-03",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Gastos en escuelas infantiles de 0 a 3 años",
      description: "Deducción por gastos en centros de educación infantil autorizados en La Rioja.",
      amount: "20 %",
      requirements: "Hijo menor de 3 años, centro autorizado, justificantes de pago.",
      icon: "🧒",
    },
    {
      id: "rio-04",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Familia numerosa",
      description: "Deducción para contribuyentes con título de familia numerosa en La Rioja.",
      amount: "150-300 €",
      requirements: "Título de familia numerosa en vigor (general: 150 €, especial: 300 €).",
      icon: "👨‍👩‍👧‍👦",
    },
    {
      id: "rio-05",
      type: "deduccion-irpf",
      level: "ccaa",
      title: "Inversión en vivienda habitual",
      description: "Deducción por cantidades destinadas a la adquisición o rehabilitación de vivienda habitual en La Rioja.",
      amount: "3 %",
      requirements: "Vivienda habitual, adquisición o rehabilitación acreditada.",
      icon: "🏗️",
    },
  ],
};

// ---------------------------------------------------------------------------
// MUNICIPAL INITIATIVES
// ---------------------------------------------------------------------------

const MUNICIPAL_INITIATIVES: Record<string, FiscalInitiative[]> = {
  madrid: [
    {
      id: "mun-mad-01",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI familia numerosa",
      description: "Bonificación en el Impuesto sobre Bienes Inmuebles para titulares de familia numerosa en Madrid.",
      amount: "90 %",
      requirements: "Título de familia numerosa en vigor, vivienda habitual, solicitud en plazo.",
      icon: "👨‍👩‍👧‍👦",
    },
    {
      id: "mun-mad-02",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI por instalación de energía solar",
      description: "Bonificación en el IBI por instalación de sistemas de aprovechamiento de energía solar en Madrid.",
      amount: "50 %, 3 años",
      requirements: "Instalación de paneles solares acreditada, certificado técnico.",
      icon: "☀️",
    },
    {
      id: "mun-mad-03",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación plusvalía por herencia de vivienda habitual",
      description: "Bonificación en el Impuesto sobre el Incremento de Valor de los Terrenos por transmisión mortis causa de la vivienda habitual.",
      amount: "95 %",
      requirements: "Transmisión por herencia de vivienda habitual del causante, solicitud en 6 meses.",
      icon: "🏛️",
    },
    {
      id: "mun-mad-04",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI vivienda de protección oficial",
      description: "Bonificación en el IBI para viviendas de protección oficial (VPO) en Madrid.",
      amount: "50 %, 3 años",
      requirements: "Vivienda calificada como VPO, solicitud con calificación definitiva.",
      icon: "🏠",
    },
    {
      id: "mun-mad-05",
      type: "programa",
      level: "municipal",
      title: "Programa de ayuda al alquiler joven municipal",
      description: "Programa municipal de ayuda directa al pago del alquiler para jóvenes residentes en Madrid.",
      amount: "Hasta 200 €/mes",
      requirements: "Menor de 35 años, empadronado en Madrid, ingresos inferiores a 3 veces el IPREM.",
      icon: "🔑",
    },
  ],

  barcelona: [
    {
      id: "mun-bcn-01",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI familia numerosa",
      description: "Bonificación en el IBI para familias numerosas en Barcelona.",
      amount: "50 %",
      requirements: "Título de familia numerosa en vigor, vivienda habitual.",
      icon: "👨‍👩‍👧‍👦",
    },
    {
      id: "mun-bcn-02",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI por energía solar",
      description: "Bonificación en el IBI por instalación de sistemas de energía solar en Barcelona.",
      amount: "50 %, 3 años",
      requirements: "Instalación de paneles solares acreditada, certificado técnico.",
      icon: "☀️",
    },
    {
      id: "mun-bcn-03",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación plusvalía por herencia",
      description: "Bonificación en la plusvalía municipal por transmisión mortis causa de la vivienda habitual.",
      amount: "95 %",
      requirements: "Transmisión por herencia de vivienda habitual del causante.",
      icon: "🏛️",
    },
    {
      id: "mun-bcn-04",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI vivienda de protección oficial",
      description: "Bonificación en el IBI para viviendas de protección oficial en Barcelona.",
      amount: "50 %",
      requirements: "Vivienda calificada como VPO, calificación definitiva vigente.",
      icon: "🏠",
    },
    {
      id: "mun-bcn-05",
      type: "programa",
      level: "municipal",
      title: "Ayuda al alquiler joven",
      description: "Programa municipal de ayuda directa al pago del alquiler para jóvenes en Barcelona.",
      amount: "Hasta 200 €/mes",
      requirements: "Menor de 35 años, empadronado en Barcelona, ingresos limitados.",
      icon: "🔑",
    },
  ],

  valencia: [
    {
      id: "mun-vlc-01",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI familia numerosa",
      description: "Bonificación en el IBI para familias numerosas en Valencia.",
      amount: "90 %",
      requirements: "Título de familia numerosa en vigor, vivienda habitual.",
      icon: "👨‍👩‍👧‍👦",
    },
    {
      id: "mun-vlc-02",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI por energía solar",
      description: "Bonificación en el IBI por instalación de sistemas de energía solar en Valencia.",
      amount: "50 %",
      requirements: "Instalación acreditada de paneles solares, certificado técnico.",
      icon: "☀️",
    },
    {
      id: "mun-vlc-03",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación plusvalía por herencia",
      description: "Bonificación en la plusvalía municipal por herencia de vivienda habitual en Valencia.",
      amount: "95 %",
      requirements: "Transmisión mortis causa de vivienda habitual del causante.",
      icon: "🏛️",
    },
    {
      id: "mun-vlc-04",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI vivienda de protección oficial",
      description: "Bonificación en el IBI para VPO en Valencia.",
      amount: "50 %",
      requirements: "Vivienda calificada como VPO.",
      icon: "🏠",
    },
    {
      id: "mun-vlc-05",
      type: "programa",
      level: "municipal",
      title: "Programa de rehabilitación de vivienda",
      description: "Programa municipal de ayudas a la rehabilitación de viviendas en el casco histórico de Valencia.",
      amount: "Variable",
      requirements: "Vivienda en zona de rehabilitación, proyecto técnico aprobado.",
      icon: "🔧",
    },
  ],

  sevilla: [
    {
      id: "mun-sev-01",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI familia numerosa",
      description: "Bonificación en el IBI para familias numerosas en Sevilla.",
      amount: "50 %",
      requirements: "Título de familia numerosa en vigor, vivienda habitual.",
      icon: "👨‍👩‍👧‍👦",
    },
    {
      id: "mun-sev-02",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI por energía solar",
      description: "Bonificación en el IBI por instalación de energía solar en Sevilla.",
      amount: "50 %",
      requirements: "Instalación acreditada, certificado técnico.",
      icon: "☀️",
    },
    {
      id: "mun-sev-03",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación plusvalía por herencia",
      description: "Bonificación en la plusvalía municipal por herencia de vivienda habitual en Sevilla.",
      amount: "95 %",
      requirements: "Transmisión mortis causa de vivienda habitual.",
      icon: "🏛️",
    },
    {
      id: "mun-sev-04",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI vivienda de protección oficial",
      description: "Bonificación en el IBI para VPO en Sevilla.",
      amount: "50 %, 3 años",
      requirements: "Vivienda calificada como VPO, calificación definitiva.",
      icon: "🏠",
    },
  ],

  zaragoza: [
    {
      id: "mun-zgz-01",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI familia numerosa",
      description: "Bonificación en el IBI para familias numerosas en Zaragoza.",
      amount: "50 %",
      requirements: "Título de familia numerosa en vigor, vivienda habitual.",
      icon: "👨‍👩‍👧‍👦",
    },
    {
      id: "mun-zgz-02",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI por energía solar",
      description: "Bonificación en el IBI por instalación de energía solar en Zaragoza.",
      amount: "30 %",
      requirements: "Instalación acreditada, certificado técnico.",
      icon: "☀️",
    },
    {
      id: "mun-zgz-03",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación plusvalía por herencia",
      description: "Bonificación en la plusvalía municipal por herencia de vivienda habitual en Zaragoza.",
      amount: "95 %",
      requirements: "Transmisión mortis causa de vivienda habitual.",
      icon: "🏛️",
    },
    {
      id: "mun-zgz-04",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI vivienda de protección oficial",
      description: "Bonificación en el IBI para VPO en Zaragoza.",
      amount: "50 %",
      requirements: "Vivienda calificada como VPO.",
      icon: "🏠",
    },
  ],

  malaga: [
    {
      id: "mun-mlg-01",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI familia numerosa",
      description: "Bonificación en el IBI para familias numerosas en Málaga.",
      amount: "50 %",
      requirements: "Título de familia numerosa en vigor, vivienda habitual.",
      icon: "👨‍👩‍👧‍👦",
    },
    {
      id: "mun-mlg-02",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI por energía solar",
      description: "Bonificación en el IBI por instalación de energía solar en Málaga.",
      amount: "50 %",
      requirements: "Instalación acreditada, certificado técnico.",
      icon: "☀️",
    },
    {
      id: "mun-mlg-03",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación plusvalía por herencia",
      description: "Bonificación en la plusvalía municipal por herencia de vivienda habitual en Málaga.",
      amount: "95 %",
      requirements: "Transmisión mortis causa de vivienda habitual.",
      icon: "🏛️",
    },
    {
      id: "mun-mlg-04",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI vivienda de protección oficial",
      description: "Bonificación en el IBI para VPO en Málaga.",
      amount: "50 %",
      requirements: "Vivienda calificada como VPO.",
      icon: "🏠",
    },
  ],

  bilbao: [
    {
      id: "mun-bil-01",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI familia numerosa",
      description: "Bonificación en el IBI para familias numerosas en Bilbao.",
      amount: "90 %",
      requirements: "Título de familia numerosa en vigor, vivienda habitual.",
      icon: "👨‍👩‍👧‍👦",
    },
    {
      id: "mun-bil-02",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI por energía solar",
      description: "Bonificación en el IBI por instalación de energía solar en Bilbao.",
      amount: "50 %",
      requirements: "Instalación acreditada, certificado técnico.",
      icon: "☀️",
    },
    {
      id: "mun-bil-03",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación plusvalía por herencia",
      description: "Bonificación en la plusvalía municipal por herencia de vivienda habitual en Bilbao.",
      amount: "95 %",
      requirements: "Transmisión mortis causa de vivienda habitual.",
      icon: "🏛️",
    },
    {
      id: "mun-bil-04",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI vivienda de protección oficial",
      description: "Bonificación en el IBI para VPO en Bilbao.",
      amount: "50 %, 5 años",
      requirements: "Vivienda calificada como VPO, calificación definitiva.",
      icon: "🏠",
    },
    {
      id: "mun-bil-05",
      type: "programa",
      level: "municipal",
      title: "Ayuda al alquiler joven",
      description: "Programa municipal de ayuda al alquiler para jóvenes en Bilbao.",
      amount: "Variable",
      requirements: "Menor de 35 años, empadronado en Bilbao, ingresos limitados.",
      icon: "🔑",
    },
  ],

  murcia: [
    {
      id: "mun-mur-01",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI familia numerosa",
      description: "Bonificación en el IBI para familias numerosas en Murcia.",
      amount: "50 %",
      requirements: "Título de familia numerosa en vigor, vivienda habitual.",
      icon: "👨‍👩‍👧‍👦",
    },
    {
      id: "mun-mur-02",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI por energía solar",
      description: "Bonificación en el IBI por instalación de energía solar en Murcia.",
      amount: "25 %",
      requirements: "Instalación acreditada, certificado técnico.",
      icon: "☀️",
    },
    {
      id: "mun-mur-03",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación plusvalía por herencia",
      description: "Bonificación en la plusvalía municipal por herencia de vivienda habitual en Murcia.",
      amount: "95 %",
      requirements: "Transmisión mortis causa de vivienda habitual.",
      icon: "🏛️",
    },
    {
      id: "mun-mur-04",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI vivienda de protección oficial",
      description: "Bonificación en el IBI para VPO en Murcia.",
      amount: "50 %",
      requirements: "Vivienda calificada como VPO.",
      icon: "🏠",
    },
  ],

  palma: [
    {
      id: "mun-plm-01",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI familia numerosa",
      description: "Bonificación en el IBI para familias numerosas en Palma.",
      amount: "50 %",
      requirements: "Título de familia numerosa en vigor, vivienda habitual.",
      icon: "👨‍👩‍👧‍👦",
    },
    {
      id: "mun-plm-02",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI por energía solar",
      description: "Bonificación en el IBI por instalación de energía solar en Palma.",
      amount: "50 %",
      requirements: "Instalación acreditada, certificado técnico.",
      icon: "☀️",
    },
    {
      id: "mun-plm-03",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación plusvalía por herencia",
      description: "Bonificación en la plusvalía municipal por herencia de vivienda habitual en Palma.",
      amount: "95 %",
      requirements: "Transmisión mortis causa de vivienda habitual.",
      icon: "🏛️",
    },
    {
      id: "mun-plm-04",
      type: "programa",
      level: "municipal",
      title: "Programa municipal de vivienda",
      description: "Programa de acceso a vivienda pública y ayudas al alquiler del Ayuntamiento de Palma.",
      amount: "Variable",
      requirements: "Empadronado en Palma, ingresos inferiores a 3 veces el IPREM.",
      icon: "🏠",
    },
  ],

  "las-palmas-de-gran-canaria": [
    {
      id: "mun-lpa-01",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI familia numerosa",
      description: "Bonificación en el IBI para familias numerosas en Las Palmas de Gran Canaria.",
      amount: "50 %",
      requirements: "Título de familia numerosa en vigor, vivienda habitual.",
      icon: "👨‍👩‍👧‍👦",
    },
    {
      id: "mun-lpa-02",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI por energía solar",
      description: "Bonificación en el IBI por instalación de energía solar en Las Palmas.",
      amount: "50 %",
      requirements: "Instalación acreditada, certificado técnico.",
      icon: "☀️",
    },
    {
      id: "mun-lpa-03",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación plusvalía por herencia",
      description: "Bonificación en la plusvalía municipal por herencia de vivienda habitual.",
      amount: "95 %",
      requirements: "Transmisión mortis causa de vivienda habitual.",
      icon: "🏛️",
    },
    {
      id: "mun-lpa-04",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI vivienda de protección oficial",
      description: "Bonificación en el IBI para VPO en Las Palmas de Gran Canaria.",
      amount: "50 %",
      requirements: "Vivienda calificada como VPO.",
      icon: "🏠",
    },
  ],

  cordoba: [
    {
      id: "mun-cor-01",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI familia numerosa",
      description: "Bonificación en el IBI para familias numerosas en Córdoba.",
      amount: "50 %",
      requirements: "Título de familia numerosa en vigor, vivienda habitual.",
      icon: "👨‍👩‍👧‍👦",
    },
    {
      id: "mun-cor-02",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI por energía solar",
      description: "Bonificación en el IBI por instalación de energía solar en Córdoba.",
      amount: "30 %",
      requirements: "Instalación acreditada, certificado técnico.",
      icon: "☀️",
    },
    {
      id: "mun-cor-03",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación plusvalía por herencia",
      description: "Bonificación en la plusvalía municipal por herencia de vivienda habitual en Córdoba.",
      amount: "95 %",
      requirements: "Transmisión mortis causa de vivienda habitual.",
      icon: "🏛️",
    },
    {
      id: "mun-cor-04",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI vivienda de protección oficial",
      description: "Bonificación en el IBI para VPO en Córdoba.",
      amount: "50 %",
      requirements: "Vivienda calificada como VPO.",
      icon: "🏠",
    },
  ],

  alicante: [
    {
      id: "mun-ali-01",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI familia numerosa",
      description: "Bonificación en el IBI para familias numerosas en Alicante.",
      amount: "50 %",
      requirements: "Título de familia numerosa en vigor, vivienda habitual.",
      icon: "👨‍👩‍👧‍👦",
    },
    {
      id: "mun-ali-02",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI por energía solar",
      description: "Bonificación en el IBI por instalación de energía solar en Alicante.",
      amount: "50 %",
      requirements: "Instalación acreditada, certificado técnico.",
      icon: "☀️",
    },
    {
      id: "mun-ali-03",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación plusvalía por herencia",
      description: "Bonificación en la plusvalía municipal por herencia de vivienda habitual en Alicante.",
      amount: "95 %",
      requirements: "Transmisión mortis causa de vivienda habitual.",
      icon: "🏛️",
    },
    {
      id: "mun-ali-04",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI vivienda de protección oficial",
      description: "Bonificación en el IBI para VPO en Alicante.",
      amount: "50 %",
      requirements: "Vivienda calificada como VPO.",
      icon: "🏠",
    },
  ],

  valladolid: [
    {
      id: "mun-vll-01",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI familia numerosa",
      description: "Bonificación en el IBI para familias numerosas en Valladolid.",
      amount: "90 %",
      requirements: "Título de familia numerosa en vigor, vivienda habitual.",
      icon: "👨‍👩‍👧‍👦",
    },
    {
      id: "mun-vll-02",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI por energía solar",
      description: "Bonificación en el IBI por instalación de energía solar en Valladolid.",
      amount: "50 %",
      requirements: "Instalación acreditada, certificado técnico.",
      icon: "☀️",
    },
    {
      id: "mun-vll-03",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación plusvalía por herencia",
      description: "Bonificación en la plusvalía municipal por herencia de vivienda habitual en Valladolid.",
      amount: "95 %",
      requirements: "Transmisión mortis causa de vivienda habitual.",
      icon: "🏛️",
    },
    {
      id: "mun-vll-04",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI vivienda de protección oficial",
      description: "Bonificación en el IBI para VPO en Valladolid.",
      amount: "50 %",
      requirements: "Vivienda calificada como VPO.",
      icon: "🏠",
    },
  ],

  gijon: [
    {
      id: "mun-gij-01",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI familia numerosa",
      description: "Bonificación en el IBI para familias numerosas en Gijón.",
      amount: "75 %",
      requirements: "Título de familia numerosa en vigor, vivienda habitual.",
      icon: "👨‍👩‍👧‍👦",
    },
    {
      id: "mun-gij-02",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI por energía solar",
      description: "Bonificación en el IBI por instalación de energía solar en Gijón.",
      amount: "50 %",
      requirements: "Instalación acreditada, certificado técnico.",
      icon: "☀️",
    },
    {
      id: "mun-gij-03",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación plusvalía por herencia",
      description: "Bonificación en la plusvalía municipal por herencia de vivienda habitual en Gijón.",
      amount: "95 %",
      requirements: "Transmisión mortis causa de vivienda habitual.",
      icon: "🏛️",
    },
    {
      id: "mun-gij-04",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI vivienda de protección oficial",
      description: "Bonificación en el IBI para VPO en Gijón.",
      amount: "50 %",
      requirements: "Vivienda calificada como VPO.",
      icon: "🏠",
    },
  ],

  "vitoria-gasteiz": [
    {
      id: "mun-vit-01",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI familia numerosa",
      description: "Bonificación en el IBI para familias numerosas en Vitoria-Gasteiz.",
      amount: "90 %",
      requirements: "Título de familia numerosa en vigor, vivienda habitual.",
      icon: "👨‍👩‍👧‍👦",
    },
    {
      id: "mun-vit-02",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI por energía solar",
      description: "Bonificación en el IBI por instalación de energía solar en Vitoria-Gasteiz.",
      amount: "50 %",
      requirements: "Instalación acreditada, certificado técnico.",
      icon: "☀️",
    },
    {
      id: "mun-vit-03",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación plusvalía por herencia",
      description: "Bonificación en la plusvalía municipal por herencia de vivienda habitual en Vitoria-Gasteiz.",
      amount: "95 %",
      requirements: "Transmisión mortis causa de vivienda habitual.",
      icon: "🏛️",
    },
    {
      id: "mun-vit-04",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI vivienda de protección oficial",
      description: "Bonificación en el IBI para VPO en Vitoria-Gasteiz.",
      amount: "50 %",
      requirements: "Vivienda calificada como VPO.",
      icon: "🏠",
    },
  ],

  granada: [
    {
      id: "mun-gra-01",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI familia numerosa",
      description: "Bonificación en el IBI para familias numerosas en Granada.",
      amount: "50 %",
      requirements: "Título de familia numerosa en vigor, vivienda habitual.",
      icon: "👨‍👩‍👧‍👦",
    },
    {
      id: "mun-gra-02",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI por energía solar",
      description: "Bonificación en el IBI por instalación de energía solar en Granada.",
      amount: "30 %",
      requirements: "Instalación acreditada, certificado técnico.",
      icon: "☀️",
    },
    {
      id: "mun-gra-03",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación plusvalía por herencia",
      description: "Bonificación en la plusvalía municipal por herencia de vivienda habitual en Granada.",
      amount: "95 %",
      requirements: "Transmisión mortis causa de vivienda habitual.",
      icon: "🏛️",
    },
    {
      id: "mun-gra-04",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI vivienda de protección oficial",
      description: "Bonificación en el IBI para VPO en Granada.",
      amount: "50 %",
      requirements: "Vivienda calificada como VPO.",
      icon: "🏠",
    },
  ],

  "a-coruna": [
    {
      id: "mun-acr-01",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI familia numerosa",
      description: "Bonificación en el IBI para familias numerosas en A Coruña.",
      amount: "50 %",
      requirements: "Título de familia numerosa en vigor, vivienda habitual.",
      icon: "👨‍👩‍👧‍👦",
    },
    {
      id: "mun-acr-02",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI por energía solar",
      description: "Bonificación en el IBI por instalación de energía solar en A Coruña.",
      amount: "50 %",
      requirements: "Instalación acreditada, certificado técnico.",
      icon: "☀️",
    },
    {
      id: "mun-acr-03",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación plusvalía por herencia",
      description: "Bonificación en la plusvalía municipal por herencia de vivienda habitual en A Coruña.",
      amount: "95 %",
      requirements: "Transmisión mortis causa de vivienda habitual.",
      icon: "🏛️",
    },
    {
      id: "mun-acr-04",
      type: "bonificacion-ibi",
      level: "municipal",
      title: "Bonificación IBI vivienda de protección oficial",
      description: "Bonificación en el IBI para VPO en A Coruña.",
      amount: "50 %",
      requirements: "Vivienda calificada como VPO.",
      icon: "🏠",
    },
  ],
};

// ---------------------------------------------------------------------------
// Lookup helpers
// ---------------------------------------------------------------------------

export function getCcaaInitiatives(ccaaSlug: string): FiscalInitiative[] {
  return CCAA_INITIATIVES[ccaaSlug] ?? [];
}

export function getMunicipalInitiatives(municipality: string): FiscalInitiative[] {
  const key = municipality
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/\s+/g, "-");
  return MUNICIPAL_INITIATIVES[key] ?? [];
}
