/* ═══════════════════════════════════════════════════════════════════════════
   INE socioeconomic indicators per territory.
   Based on INE TEMPUS3 API / EPA / Contabilidad Regional (seed 2026).
   ═══════════════════════════════════════════════════════════════════════════ */

export interface TerritoryIndicators {
  territorySlug: string;
  population: number;
  populationChange: number; // % vs previous year
  gdpM: number;
  gdpPerCapita: number;
  gdpGrowthPct: number;
  unemploymentRate: number;
  unemploymentChange: number;
  youthUnemploymentRate: number;
  averageSalary: number;
  cpiAnnual: number; // inflation %
  povertyRiskRate: number;
  giniIndex: number;
  lifeExpectancy: number;
  birthRate: number; // per 1000
  medianAge: number;
  activePopulationPct: number;
  housingPriceIndex: number; // base 100 = 2015
  rentAvgMonthly: number;
}

export const nationalIndicators: TerritoryIndicators = {
  territorySlug: "espana",
  population: 48_345_000,
  populationChange: 0.38,
  gdpM: 1_498_000,
  gdpPerCapita: 30_990,
  gdpGrowthPct: 2.4,
  unemploymentRate: 11.2,
  unemploymentChange: -0.8,
  youthUnemploymentRate: 26.4,
  averageSalary: 28_360,
  cpiAnnual: 2.8,
  povertyRiskRate: 20.4,
  giniIndex: 33.0,
  lifeExpectancy: 83.6,
  birthRate: 7.1,
  medianAge: 44.8,
  activePopulationPct: 58.6,
  housingPriceIndex: 142,
  rentAvgMonthly: 920,
};

export const ccaaIndicators: TerritoryIndicators[] = [
  {
    territorySlug: "andalucia",
    population: 8_620_000,
    populationChange: 0.22,
    gdpM: 182_400,
    gdpPerCapita: 21_160,
    gdpGrowthPct: 2.1,
    unemploymentRate: 18.4,
    unemploymentChange: -1.2,
    youthUnemploymentRate: 36.8,
    averageSalary: 23_420,
    cpiAnnual: 2.6,
    povertyRiskRate: 28.2,
    giniIndex: 34.8,
    lifeExpectancy: 82.4,
    birthRate: 7.8,
    medianAge: 42.6,
    activePopulationPct: 56.2,
    housingPriceIndex: 128,
    rentAvgMonthly: 720,
  },
  {
    territorySlug: "cataluna",
    population: 7_840_000,
    populationChange: 0.52,
    gdpM: 262_800,
    gdpPerCapita: 33_520,
    gdpGrowthPct: 2.6,
    unemploymentRate: 9.4,
    unemploymentChange: -0.6,
    youthUnemploymentRate: 22.1,
    averageSalary: 30_680,
    cpiAnnual: 3.0,
    povertyRiskRate: 17.8,
    giniIndex: 32.4,
    lifeExpectancy: 83.8,
    birthRate: 7.4,
    medianAge: 43.8,
    activePopulationPct: 60.4,
    housingPriceIndex: 158,
    rentAvgMonthly: 1180,
  },
  {
    territorySlug: "madrid",
    population: 6_860_000,
    populationChange: 0.68,
    gdpM: 274_200,
    gdpPerCapita: 39_970,
    gdpGrowthPct: 3.1,
    unemploymentRate: 8.6,
    unemploymentChange: -0.9,
    youthUnemploymentRate: 20.2,
    averageSalary: 33_240,
    cpiAnnual: 3.2,
    povertyRiskRate: 16.2,
    giniIndex: 35.6,
    lifeExpectancy: 84.8,
    birthRate: 8.2,
    medianAge: 42.4,
    activePopulationPct: 62.8,
    housingPriceIndex: 172,
    rentAvgMonthly: 1340,
  },
  {
    territorySlug: "comunitat-valenciana",
    population: 5_220_000,
    populationChange: 0.42,
    gdpM: 136_400,
    gdpPerCapita: 26_130,
    gdpGrowthPct: 2.4,
    unemploymentRate: 12.8,
    unemploymentChange: -0.7,
    youthUnemploymentRate: 28.6,
    averageSalary: 25_480,
    cpiAnnual: 2.8,
    povertyRiskRate: 22.4,
    giniIndex: 33.2,
    lifeExpectancy: 83.2,
    birthRate: 7.2,
    medianAge: 43.4,
    activePopulationPct: 58.2,
    housingPriceIndex: 138,
    rentAvgMonthly: 840,
  },
  {
    territorySlug: "pais-vasco",
    population: 2_220_000,
    populationChange: -0.08,
    gdpM: 84_600,
    gdpPerCapita: 38_110,
    gdpGrowthPct: 2.2,
    unemploymentRate: 7.2,
    unemploymentChange: -0.4,
    youthUnemploymentRate: 18.4,
    averageSalary: 32_860,
    cpiAnnual: 2.4,
    povertyRiskRate: 10.2,
    giniIndex: 28.4,
    lifeExpectancy: 84.2,
    birthRate: 6.4,
    medianAge: 46.8,
    activePopulationPct: 57.8,
    housingPriceIndex: 134,
    rentAvgMonthly: 980,
  },
  {
    territorySlug: "galicia",
    population: 2_700_000,
    populationChange: -0.32,
    gdpM: 72_800,
    gdpPerCapita: 26_960,
    gdpGrowthPct: 1.8,
    unemploymentRate: 10.6,
    unemploymentChange: -0.5,
    youthUnemploymentRate: 24.2,
    averageSalary: 25_120,
    cpiAnnual: 2.4,
    povertyRiskRate: 18.6,
    giniIndex: 30.8,
    lifeExpectancy: 83.4,
    birthRate: 5.8,
    medianAge: 48.2,
    activePopulationPct: 55.4,
    housingPriceIndex: 118,
    rentAvgMonthly: 620,
  },
  {
    territorySlug: "castilla-y-leon",
    population: 2_380_000,
    populationChange: -0.48,
    gdpM: 64_200,
    gdpPerCapita: 26_970,
    gdpGrowthPct: 1.6,
    unemploymentRate: 10.2,
    unemploymentChange: -0.6,
    youthUnemploymentRate: 24.8,
    averageSalary: 24_680,
    cpiAnnual: 2.2,
    povertyRiskRate: 17.4,
    giniIndex: 30.2,
    lifeExpectancy: 84.0,
    birthRate: 5.4,
    medianAge: 48.6,
    activePopulationPct: 54.8,
    housingPriceIndex: 108,
    rentAvgMonthly: 540,
  },
  {
    territorySlug: "canarias",
    population: 2_260_000,
    populationChange: 0.34,
    gdpM: 54_800,
    gdpPerCapita: 24_250,
    gdpGrowthPct: 2.8,
    unemploymentRate: 16.2,
    unemploymentChange: -1.4,
    youthUnemploymentRate: 34.2,
    averageSalary: 23_680,
    cpiAnnual: 2.6,
    povertyRiskRate: 28.6,
    giniIndex: 35.2,
    lifeExpectancy: 82.8,
    birthRate: 6.8,
    medianAge: 42.8,
    activePopulationPct: 57.4,
    housingPriceIndex: 148,
    rentAvgMonthly: 920,
  },
  {
    territorySlug: "castilla-la-mancha",
    population: 2_080_000,
    populationChange: 0.08,
    gdpM: 47_200,
    gdpPerCapita: 22_690,
    gdpGrowthPct: 2.0,
    unemploymentRate: 14.2,
    unemploymentChange: -0.8,
    youthUnemploymentRate: 30.4,
    averageSalary: 23_240,
    cpiAnnual: 2.4,
    povertyRiskRate: 26.8,
    giniIndex: 33.4,
    lifeExpectancy: 83.2,
    birthRate: 6.8,
    medianAge: 44.2,
    activePopulationPct: 56.0,
    housingPriceIndex: 106,
    rentAvgMonthly: 520,
  },
  {
    territorySlug: "murcia",
    population: 1_560_000,
    populationChange: 0.38,
    gdpM: 38_200,
    gdpPerCapita: 24_490,
    gdpGrowthPct: 2.2,
    unemploymentRate: 14.8,
    unemploymentChange: -0.6,
    youthUnemploymentRate: 32.4,
    averageSalary: 23_480,
    cpiAnnual: 2.6,
    povertyRiskRate: 27.4,
    giniIndex: 34.2,
    lifeExpectancy: 82.6,
    birthRate: 8.4,
    medianAge: 40.8,
    activePopulationPct: 57.8,
    housingPriceIndex: 116,
    rentAvgMonthly: 640,
  },
  {
    territorySlug: "aragon",
    population: 1_340_000,
    populationChange: 0.12,
    gdpM: 42_800,
    gdpPerCapita: 31_940,
    gdpGrowthPct: 2.2,
    unemploymentRate: 8.4,
    unemploymentChange: -0.5,
    youthUnemploymentRate: 20.6,
    averageSalary: 27_640,
    cpiAnnual: 2.4,
    povertyRiskRate: 15.8,
    giniIndex: 29.8,
    lifeExpectancy: 83.8,
    birthRate: 6.6,
    medianAge: 45.8,
    activePopulationPct: 57.2,
    housingPriceIndex: 114,
    rentAvgMonthly: 620,
  },
  {
    territorySlug: "extremadura",
    population: 1_060_000,
    populationChange: -0.28,
    gdpM: 22_400,
    gdpPerCapita: 21_130,
    gdpGrowthPct: 1.8,
    unemploymentRate: 17.6,
    unemploymentChange: -0.8,
    youthUnemploymentRate: 36.2,
    averageSalary: 22_480,
    cpiAnnual: 2.2,
    povertyRiskRate: 30.2,
    giniIndex: 34.6,
    lifeExpectancy: 82.2,
    birthRate: 6.4,
    medianAge: 45.4,
    activePopulationPct: 54.6,
    housingPriceIndex: 96,
    rentAvgMonthly: 440,
  },
  {
    territorySlug: "illes-balears",
    population: 1_240_000,
    populationChange: 0.62,
    gdpM: 40_200,
    gdpPerCapita: 32_420,
    gdpGrowthPct: 3.2,
    unemploymentRate: 10.8,
    unemploymentChange: -1.0,
    youthUnemploymentRate: 24.6,
    averageSalary: 26_840,
    cpiAnnual: 3.4,
    povertyRiskRate: 16.8,
    giniIndex: 33.8,
    lifeExpectancy: 83.4,
    birthRate: 7.6,
    medianAge: 41.2,
    activePopulationPct: 61.2,
    housingPriceIndex: 168,
    rentAvgMonthly: 1120,
  },
  {
    territorySlug: "asturias",
    population: 1_010_000,
    populationChange: -0.52,
    gdpM: 27_200,
    gdpPerCapita: 26_930,
    gdpGrowthPct: 1.4,
    unemploymentRate: 11.4,
    unemploymentChange: -0.4,
    youthUnemploymentRate: 26.8,
    averageSalary: 26_240,
    cpiAnnual: 2.2,
    povertyRiskRate: 18.2,
    giniIndex: 30.4,
    lifeExpectancy: 82.8,
    birthRate: 4.8,
    medianAge: 49.4,
    activePopulationPct: 53.2,
    housingPriceIndex: 104,
    rentAvgMonthly: 520,
  },
  {
    territorySlug: "navarra",
    population: 668_000,
    populationChange: 0.18,
    gdpM: 24_600,
    gdpPerCapita: 36_830,
    gdpGrowthPct: 2.4,
    unemploymentRate: 7.8,
    unemploymentChange: -0.6,
    youthUnemploymentRate: 18.2,
    averageSalary: 30_480,
    cpiAnnual: 2.4,
    povertyRiskRate: 9.8,
    giniIndex: 27.2,
    lifeExpectancy: 84.4,
    birthRate: 7.4,
    medianAge: 44.2,
    activePopulationPct: 59.4,
    housingPriceIndex: 126,
    rentAvgMonthly: 760,
  },
  {
    territorySlug: "cantabria",
    population: 584_000,
    populationChange: -0.12,
    gdpM: 16_200,
    gdpPerCapita: 27_740,
    gdpGrowthPct: 1.8,
    unemploymentRate: 9.4,
    unemploymentChange: -0.4,
    youthUnemploymentRate: 22.4,
    averageSalary: 26_120,
    cpiAnnual: 2.4,
    povertyRiskRate: 16.4,
    giniIndex: 30.0,
    lifeExpectancy: 83.6,
    birthRate: 6.0,
    medianAge: 47.2,
    activePopulationPct: 55.6,
    housingPriceIndex: 112,
    rentAvgMonthly: 600,
  },
  {
    territorySlug: "la-rioja",
    population: 322_000,
    populationChange: 0.04,
    gdpM: 10_200,
    gdpPerCapita: 31_680,
    gdpGrowthPct: 2.0,
    unemploymentRate: 9.2,
    unemploymentChange: -0.5,
    youthUnemploymentRate: 22.0,
    averageSalary: 26_480,
    cpiAnnual: 2.2,
    povertyRiskRate: 14.8,
    giniIndex: 29.4,
    lifeExpectancy: 83.8,
    birthRate: 6.8,
    medianAge: 45.4,
    activePopulationPct: 57.0,
    housingPriceIndex: 108,
    rentAvgMonthly: 540,
  },
  {
    territorySlug: "ceuta",
    population: 84_000,
    populationChange: 0.14,
    gdpM: 2_100,
    gdpPerCapita: 25_000,
    gdpGrowthPct: 1.6,
    unemploymentRate: 22.4,
    unemploymentChange: -0.6,
    youthUnemploymentRate: 42.8,
    averageSalary: 24_680,
    cpiAnnual: 2.8,
    povertyRiskRate: 32.4,
    giniIndex: 36.8,
    lifeExpectancy: 81.2,
    birthRate: 10.2,
    medianAge: 38.4,
    activePopulationPct: 52.4,
    housingPriceIndex: 98,
    rentAvgMonthly: 480,
  },
  {
    territorySlug: "melilla",
    population: 86_000,
    populationChange: 0.22,
    gdpM: 1_900,
    gdpPerCapita: 22_090,
    gdpGrowthPct: 1.4,
    unemploymentRate: 24.2,
    unemploymentChange: -0.4,
    youthUnemploymentRate: 44.6,
    averageSalary: 23_840,
    cpiAnnual: 3.0,
    povertyRiskRate: 34.8,
    giniIndex: 37.4,
    lifeExpectancy: 80.8,
    birthRate: 11.4,
    medianAge: 36.8,
    activePopulationPct: 50.8,
    housingPriceIndex: 94,
    rentAvgMonthly: 460,
  },
];

export const allIndicators = [nationalIndicators, ...ccaaIndicators];

export function getTerritoryIndicators(slug: string): TerritoryIndicators | undefined {
  return allIndicators.find((i) => i.territorySlug === slug);
}

export function getRanking(field: keyof TerritoryIndicators, order: "asc" | "desc" = "desc") {
  return [...ccaaIndicators]
    .sort((a, b) => order === "desc"
      ? (b[field] as number) - (a[field] as number)
      : (a[field] as number) - (b[field] as number)
    )
    .map((t, i) => ({ ...t, rank: i + 1 }));
}

export const indicatorLabels: Record<string, string> = {
  population: "Población",
  populationChange: "Variación poblacional",
  gdpM: "PIB (M€)",
  gdpPerCapita: "PIB per cápita",
  gdpGrowthPct: "Crecimiento PIB",
  unemploymentRate: "Tasa de paro",
  youthUnemploymentRate: "Paro juvenil",
  averageSalary: "Salario medio",
  cpiAnnual: "IPC anual",
  povertyRiskRate: "Riesgo de pobreza",
  giniIndex: "Índice Gini",
  lifeExpectancy: "Esperanza de vida",
  birthRate: "Natalidad (‰)",
  medianAge: "Edad mediana",
  activePopulationPct: "Población activa",
  housingPriceIndex: "Índice precio vivienda",
  rentAvgMonthly: "Alquiler medio mensual",
};

export const indicatorUnits: Record<string, string> = {
  population: "",
  populationChange: "%",
  gdpM: "M€",
  gdpPerCapita: "€",
  gdpGrowthPct: "%",
  unemploymentRate: "%",
  youthUnemploymentRate: "%",
  averageSalary: "€",
  cpiAnnual: "%",
  povertyRiskRate: "%",
  giniIndex: "",
  lifeExpectancy: "años",
  birthRate: "‰",
  medianAge: "años",
  activePopulationPct: "%",
  housingPriceIndex: "",
  rentAvgMonthly: "€/mes",
};
