/* ═══════════════════════════════════════════════════════════════════════════
   Ingestion Status — real-time state of each data source connector.
   Tracks what's built, what has real data, and what's still planned.
   ═══════════════════════════════════════════════════════════════════════════ */

export type IngestionState =
  | "live"          // connector built + actively ingesting real data
  | "built"         // connector code exists but not running / no stored data
  | "seed-only"     // only seed/demo data, no real ingestion
  | "planned"       // documented but no connector code
  | "stub";         // partial connector code (e.g. EUR-Lex SPARQL stub)

/** RAG agent assignment for each source group */
export type RagAgentId = "normativo" | "presupuestario" | "politico-social" | "empresarial" | "medios";

export const RAG_BY_GROUP: Record<string, RagAgentId> = {
  estado: "normativo",
  hacienda: "presupuestario",
  empleo: "presupuestario",
  regulador: "normativo",
  europa: "presupuestario",
  local: "presupuestario",
  social: "politico-social",
  ministerios: "normativo",
  autonomico: "politico-social",
};

export const RAG_LABELS: Record<RagAgentId, { label: string; color: string; icon: string }> = {
  normativo: { label: "Normativo", color: "var(--rojo)", icon: "N" },
  presupuestario: { label: "Presupuestario", color: "var(--azul)", icon: "P" },
  "politico-social": { label: "Político-Social", color: "var(--verde)", icon: "S" },
  empresarial: { label: "Empresarial", color: "#b45309", icon: "E" },
  medios: { label: "Medios", color: "#7c3aed", icon: "M" },
};

export interface DataSourceStatus {
  id: string;
  name: string;
  shortName: string;
  group: "estado" | "hacienda" | "empleo" | "regulador" | "europa" | "local" | "social" | "ministerios" | "autonomico";
  state: IngestionState;
  statusReason: string;          // one-line explanation of current state
  connectorFile?: string;       // relative path to connector code
  apiEndpoint?: string;         // official source API/URL
  ingestionEndpoint?: string;   // our API endpoint to trigger ingestion
  docsCount: number;            // documents/records actually stored
  seedCount: number;            // seed/demo records
  lastIngestion?: string;       // ISO date of last successful ingestion
  updateFrequency: "realtime" | "daily" | "weekly" | "monthly" | "annual" | "on-demand" | "none";
  weHave?: string;              // what data we currently have access to
  cannotHave?: string;          // what data we cannot access and why
  notes?: string;
}

export const dataSourceStatuses: DataSourceStatus[] = [
  /* ── Estado — Poder Legislativo y Ejecutivo ── */
  {
    id: "boe-sumario",
    name: "BOE — Boletín Oficial del Estado",
    shortName: "BOE",
    group: "estado",
    state: "live",
    statusReason: "API datos abiertos boe.es conectada — 277K disposiciones en archivo JSONL (2010-2025)",
    connectorFile: "apps/web/lib/boe-live.ts",
    apiEndpoint: "https://www.boe.es/datosabiertos/api/boe/sumario/",
    ingestionEndpoint: "GET /api/boe/latest",
    docsCount: 276944,
    seedCount: 3,
    lastIngestion: "2026-04-11",
    updateFrequency: "daily",
    weHave: "Sumarios diarios, disposiciones, metadatos, scoring de impacto, detección territorial. Archivo histórico 2010-2025 (277K items, 5.474 días)",
    cannotHave: "Textos HTML completos requieren scraping pesado. PDFs escaneados sin OCR",
    notes: "Live fetcher + JSONL archive + backfill engine. Cache 1h. Alimenta RAG Normativo.",
  },
  {
    id: "borme-sumario",
    name: "BORME — Boletín Oficial del Registro Mercantil",
    shortName: "BORME",
    group: "estado",
    state: "built",
    statusReason: "Conector listo — pendiente de activar ingesta automática en producción",
    connectorFile: "packages/official-connectors/src/borme.ts",
    apiEndpoint: "https://www.boe.es/datosabiertos/api/borme/sumario/",
    ingestionEndpoint: "POST /v1/ingest/borme/run",
    docsCount: 0,
    seedCount: 0,
    updateFrequency: "daily",
    weHave: "Sumarios diarios de actos mercantiles, nombramientos, ceses, constituciones, ampliaciones",
    cannotHave: "Datos de cuentas anuales completos requieren acceso al Registro Mercantil (de pago)",
    notes: "Fetcher + DB persistence listos. Scheduler diario configurado.",
  },
  {
    id: "congreso-diputados",
    name: "Congreso de los Diputados — Composición e Iniciativas",
    shortName: "Congreso",
    group: "estado",
    state: "live",
    statusReason: "API OpenData del Congreso conectada — 350 diputados + 89 iniciativas ingestados",
    connectorFile: "packages/official-connectors/src/congreso.ts",
    apiEndpoint: "https://www.congreso.es/webpublica/opendata/",
    ingestionEndpoint: "POST /v1/ingest/congreso/run",
    docsCount: 439,
    seedCount: 4,
    lastIngestion: "2026-04-10",
    updateFrequency: "weekly",
    weHave: "350 diputados (nombre, partido, circunscripción, foto), 89 iniciativas, composición de comisiones, grupos parlamentarios",
    cannotHave: "Votaciones nominales individuales (solo totales por grupo). Agenda de comisiones en tiempo real. Enmiendas en tramitación no publicadas",
    notes: "350 diputados + 89 iniciativas ingestados en PostgreSQL. Scheduler semanal activo.",
  },
  {
    id: "senado-composicion",
    name: "Senado — Composición y Grupos Parlamentarios",
    shortName: "Senado",
    group: "estado",
    state: "live",
    statusReason: "API XML del Senado conectada — 266 senadores ingestados con grupos y comisiones",
    connectorFile: "packages/official-connectors/src/senado.ts",
    apiEndpoint: "https://www.senado.es/web/ficopendataservlet",
    ingestionEndpoint: "POST /v1/ingest/senado/run",
    docsCount: 266,
    seedCount: 0,
    lastIngestion: "2026-04-10",
    updateFrequency: "weekly",
    weHave: "266 senadores (nombre, grupo, procedencia, comisiones), grupos parlamentarios, composición de mesa",
    cannotHave: "Iniciativas legislativas del Senado en formato estructurado. Intervenciones textuales indexadas por orador",
    notes: "266 senadores ingestados en PostgreSQL. XML + grupos parlamentarios. Scheduler semanal.",
  },
  {
    id: "datos-auxiliares-boe",
    name: "BOE — Catálogos Auxiliares (materias, ámbitos, departamentos)",
    shortName: "BOE Aux.",
    group: "estado",
    state: "built",
    statusReason: "7 catálogos auxiliares disponibles — pendiente de integrar en RAG",
    connectorFile: "packages/official-connectors/src/borme.ts",
    apiEndpoint: "https://www.boe.es/datosabiertos/api/boe/",
    ingestionEndpoint: "GET /v1/datos-auxiliares/:dataset",
    docsCount: 0,
    seedCount: 0,
    updateFrequency: "monthly",
    weHave: "7 catálogos: materias, ámbitos geográficos, estados de consolidación, departamentos, rangos normativos, orígenes, secciones",
    cannotHave: "Relaciones cruzadas entre catálogos. Histórico de cambios de nomenclatura ministerial",
    notes: "7 datasets auxiliares: materias, ámbitos, estados-consolidacion, departamentos, rangos, etc.",
  },
  {
    id: "congreso-diario-sesiones",
    name: "Diarios de Sesiones — Congreso (Intervenciones)",
    shortName: "Diario Congreso",
    group: "estado",
    state: "live",
    statusReason: "36.174 intervenciones disponibles en leg. XV — 150 ingestadas via API filtrarListado",
    connectorFile: "packages/official-connectors/src/congreso-intervenciones.ts",
    apiEndpoint: "https://www.congreso.es/es/busqueda-de-intervenciones",
    ingestionEndpoint: "POST /v1/ingest/congreso-intervenciones/run",
    docsCount: 150,
    seedCount: 0,
    lastIngestion: "2026-04-10",
    updateFrequency: "weekly",
    weHave: "Intervenciones por orador, fecha, comisión; enlace a PDF del diario y vídeo MP4. 36.174 disponibles en legislatura XV",
    cannotHave: "Texto completo transcrito (solo PDFs). Indexación semántica requiere OCR/NLP propio. Legislaturas anteriores a la XII incompletas",
    notes: "36.174 intervenciones disponibles (leg. XV). API filtrarListado con orador, diario PDF, vídeo. 150 ingestadas (3 páginas). Scheduler semanal.",
  },
  {
    id: "senado-diario-sesiones",
    name: "Diarios de Sesiones — Senado",
    shortName: "Diario Senado",
    group: "estado",
    state: "live",
    statusReason: "~120 PDFs de pleno legislatura XV indexados vía HEAD scan",
    connectorFile: "packages/official-connectors/src/senado-diarios.ts",
    apiEndpoint: "https://www.senado.es/legis15/publicaciones/pdf/senado/ds/",
    ingestionEndpoint: "POST /v1/ingest/senado-diarios/run",
    docsCount: 120,
    seedCount: 0,
    lastIngestion: "2026-04-10",
    updateFrequency: "weekly",
    weHave: "~120 PDFs de plenos legislatura XV, metadatos de sesión (fecha, número, tipo)",
    cannotHave: "Texto indexado por intervención/orador (solo PDF monolítico). Comisiones no disponibles en formato PDF abierto",
    notes: "~120 PDFs de pleno (leg. XV) indexados via HEAD scan. Scheduler semanal.",
  },
  {
    id: "congreso-tv",
    name: "Congreso TV — Archivo Audiovisual",
    shortName: "Congreso TV",
    group: "estado",
    state: "live",
    statusReason: "URLs de vídeo MP4 enlazados con cada intervención — streaming y descarga",
    connectorFile: "packages/official-connectors/src/congreso-intervenciones.ts",
    apiEndpoint: "https://static.congreso.es/audiovisual/video/",
    ingestionEndpoint: "POST /v1/ingest/congreso-intervenciones/run",
    docsCount: 150,
    seedCount: 0,
    lastIngestion: "2026-04-10",
    updateFrequency: "weekly",
    weHave: "URLs directas de vídeo MP4 (descarga y streaming) por intervención, enlazados con orador y sesión",
    cannotHave: "Transcripciones automáticas (requiere Whisper u otro STT propio). Vídeos de legislaturas anteriores no indexados. Sin subtítulos oficiales",
    notes: "URLs de vídeo MP4 (descarga + streaming) incluidos en cada intervención. Misma API que Diario Congreso. Potencial Whisper transcription.",
  },
  {
    id: "lamoncloa-gobierno",
    name: "La Moncloa — Composición del Gobierno",
    shortName: "Gobierno",
    group: "estado",
    state: "live",
    statusReason: "12 miembros del Gobierno ingestados via scraping HTML de La Moncloa",
    connectorFile: "packages/official-connectors/src/gobierno.ts",
    apiEndpoint: "https://www.lamoncloa.gob.es/gobierno/composiciondelgobierno/",
    ingestionEndpoint: "POST /v1/ingest/gobierno/run",
    docsCount: 12,
    seedCount: 0,
    lastIngestion: "2026-04-10",
    updateFrequency: "weekly",
    weHave: "22 miembros del Gobierno (nombre, cargo, ministerio, foto, biografía), estructura de vicepresidencias y ministerios",
    cannotHave: "Agenda del Consejo de Ministros antes de publicación. Actas de reuniones. Órdenes ministeriales internas no publicadas",
    notes: "12 miembros del Gobierno ingestados via scraping HTML. Scheduler semanal.",
  },
  {
    id: "transparencia",
    name: "Portal de Transparencia — Resoluciones FOI",
    shortName: "Transparencia",
    group: "estado",
    state: "live",
    statusReason: "532 resoluciones FOI (denegaciones + estimaciones 2024-2025) vía scraping HTML",
    connectorFile: "packages/official-connectors/src/transparencia.ts",
    apiEndpoint: "https://transparencia.gob.es/derecho-acceso/resoluciones-denegatorias",
    ingestionEndpoint: "POST /v1/ingest/transparencia/run",
    docsCount: 532,
    seedCount: 0,
    lastIngestion: "2026-04-10",
    updateFrequency: "monthly",
    weHave: "532 resoluciones FOI (denegaciones + estimaciones 2024-2025), motivo, organismo, fecha, sentido",
    cannotHave: "Documentos solicitados en sí mismos. Resoluciones anteriores a 2024 no tabuladas. Solicitudes pendientes sin resolver",
    notes: "532 resoluciones FOI (153 denegaciones 2024-2025 + 379 estimaciones). Scraping tablas HTML. Scheduler mensual.",
  },

  /* ── Hacienda y Fiscalidad ── */
  {
    id: "aeat",
    name: "AEAT — Agencia Tributaria (datos abiertos)",
    shortName: "AEAT",
    group: "hacienda",
    state: "built",
    statusReason: "Conector listo vía datos.gob.es — filtro de publisher pendiente de ajustar",
    connectorFile: "packages/official-connectors/src/aeat.ts",
    apiEndpoint: "https://sede.agenciatributaria.gob.es/Sede/datosabiertos.html",
    ingestionEndpoint: "POST /v1/ingest/aeat/run",
    docsCount: 0,
    seedCount: 0,
    updateFrequency: "monthly",
    weHave: "Estadísticas tributarias agregadas, recaudación por impuesto, declaraciones por CC.AA. vía datos.gob.es",
    cannotHave: "Datos individuales de contribuyentes (secreto tributario). Microdatos de declaraciones. Inspecciones en curso",
    notes: "Conector listo vía datos.gob.es. Filtro de publisher pendiente de ajustar.",
  },
  {
    id: "igae",
    name: "IGAE — Intervención General del Estado",
    shortName: "IGAE",
    group: "hacienda",
    state: "seed-only",
    statusReason: "Solo datos seed (42 snapshots) — sin API pública disponible",
    apiEndpoint: "https://www.igae.pap.hacienda.gob.es/",
    docsCount: 0,
    seedCount: 42,
    updateFrequency: "monthly",
    weHave: "Ejecución presupuestaria mensual, contabilidad nacional, déficit/superávit por administración, deuda pública",
    cannotHave: "Microdatos de ejecución por partida individual. Informes de control interno no publicados. Datos en tiempo real (retraso 1-2 meses)",
    notes: "Ejecución presupuestaria, contabilidad nacional. 42 budget snapshots seed en finance-data.ts.",
  },
  {
    id: "airef",
    name: "AIReF — Autoridad Independiente de Responsabilidad Fiscal",
    shortName: "AIReF",
    group: "hacienda",
    state: "live",
    statusReason: "RSS activo — 1.534 publicaciones disponibles, 50 ingestadas",
    connectorFile: "packages/official-connectors/src/airef.ts",
    apiEndpoint: "https://www.airef.es/es/feed/",
    ingestionEndpoint: "POST /v1/ingest/airef/run",
    docsCount: 50,
    seedCount: 0,
    lastIngestion: "2026-04-10",
    updateFrequency: "weekly",
    weHave: "Informes de opinión, estudios, previsiones macro, evaluaciones de gasto público vía RSS (1.534 publicaciones)",
    cannotHave: "Modelos econométricos internos. Borradores de informes. Datos micro que alimentan las previsiones",
    notes: "~1.534 publicaciones disponibles via RSS (informes, opiniones, estudios). 50 ingestadas (5 páginas). Scheduler semanal.",
  },
  {
    id: "cdti",
    name: "CDTI — Centro para el Desarrollo Tecnológico e Industrial",
    shortName: "CDTI",
    group: "hacienda",
    state: "live",
    statusReason: "15 programas catalogados — cdti.es bloqueado por WAF Incapsula para scraping extensivo",
    connectorFile: "packages/official-connectors/src/cdti.ts",
    apiEndpoint: "https://www.cdti.es/ayudas",
    ingestionEndpoint: "POST /v1/ingest/cdti/run",
    docsCount: 15,
    seedCount: 0,
    lastIngestion: "2026-04-10",
    updateFrequency: "monthly",
    weHave: "15 programas de ayudas (PERTEs, NEOTEC, Eureka, Misiones), convocatorias abiertas, requisitos",
    cannotHave: "WAF Incapsula bloquea scraping automatizado. Resoluciones de concesión individuales. Presupuesto ejecutado por empresa",
    notes: "15 programas CDTI catalogados (PERTEs, NEOTEC, Eureka, Misiones, etc.). cdti.es bloqueado por WAF Incapsula.",
  },
  {
    id: "hacienda-eell",
    name: "Hacienda — Datos Financieros de Entidades Locales (SIEL)",
    shortName: "SIEL",
    group: "hacienda",
    state: "seed-only",
    statusReason: "Solo datos seed (107 registros) — publicación anual con 6-12 meses de retraso",
    apiEndpoint: "https://www.hacienda.gob.es/",
    docsCount: 0,
    seedCount: 107,
    updateFrequency: "annual",
    weHave: "Presupuestos liquidados de ayuntamientos y diputaciones, deuda viva, indicadores financieros EELL",
    cannotHave: "Datos en tiempo real (publicación anual con 6-12 meses de retraso). Municipios < 5.000 hab. incompletos. Ejecución mensual local",
    notes: "Presupuestos de 52 ayuntamientos + 55 diputaciones en finance-data.ts. Datos seed estimados.",
  },
  {
    id: "contratacion-publica",
    name: "Plataforma de Contratación del Sector Público",
    shortName: "Contratación",
    group: "hacienda",
    state: "seed-only",
    statusReason: "Bloqueado — requiere certificado digital SSL de administración pública",
    apiEndpoint: "https://contrataciondelestado.es/",
    docsCount: 0,
    seedCount: 5,
    updateFrequency: "daily",
    weHave: "Licitaciones, adjudicaciones, contratos menores (>15.000€), pliegos, criterios de adjudicación",
    cannotHave: "API requiere certificado digital SSL de administración pública. Contratos menores <15.000€ no obligatorio publicar. Ofertas no adjudicatarias",
    notes: "Licitaciones y adjudicaciones. Datos seed en contracts-data.ts. PLACSP bloqueado por certificado SSL.",
  },

  /* ── Empleo y Seguridad Social ── */
  {
    id: "seg-social",
    name: "Seguridad Social — Catálogo de Estadísticas",
    shortName: "Seg. Social",
    group: "empleo",
    state: "live",
    statusReason: "9 secciones estadísticas indexadas — web JS-rendered limita profundidad",
    connectorFile: "packages/official-connectors/src/seg-social.ts",
    apiEndpoint: "https://www.seg-social.es/wps/portal/wss/internet/EstadisticasPresupuestosEstudios/Estadisticas",
    ingestionEndpoint: "POST /v1/ingest/seg-social/run",
    docsCount: 9,
    seedCount: 0,
    lastIngestion: "2026-04-10",
    updateFrequency: "monthly",
    weHave: "9 secciones estadísticas: pensiones, afiliación, empresas, prestaciones, recaudación, autónomos, accidentes, presupuestos",
    cannotHave: "Web JS-rendered — datos tabulares dentro de sub-categorías requieren navegación JS. Microdatos individuales de afiliación protegidos (LOPD)",
    notes: "9 secciones de estadísticas indexadas (pensiones, afiliación, empresas, prestaciones, recaudación). Web JS-rendered — catálogo de secciones con sub-categorías.",
  },
  {
    id: "sepe",
    name: "SEPE — Servicio Público de Empleo Estatal",
    shortName: "SEPE",
    group: "empleo",
    state: "built",
    statusReason: "Conector listo vía datos.gob.es — URL de dataset específico pendiente de confirmar",
    connectorFile: "packages/official-connectors/src/sepe.ts",
    apiEndpoint: "https://www.sepe.es/",
    ingestionEndpoint: "POST /v1/ingest/sepe/run",
    docsCount: 0,
    seedCount: 0,
    updateFrequency: "monthly",
    weHave: "Paro registrado mensual por provincia/CCAA, contratos registrados, prestaciones, estadísticas de empleo",
    cannotHave: "Microdatos de demandantes individuales (LOPD). Ofertas de empleo privadas. Datos en tiempo real (publicación mensual)",
    notes: "Conector listo vía datos.gob.es. Dataset específico pendiente de confirmar URL.",
  },

  /* ── Reguladores y Justicia ── */
  {
    id: "cnmc",
    name: "CNMC — Comisión Nacional de los Mercados y la Competencia",
    shortName: "CNMC",
    group: "regulador",
    state: "built",
    statusReason: "Conector listo — web JS-rendered requiere headless browser para scraping completo",
    connectorFile: "packages/official-connectors/src/cnmc.ts",
    apiEndpoint: "https://www.cnmc.es/",
    ingestionEndpoint: "POST /v1/ingest/cnmc/run",
    docsCount: 0,
    seedCount: 0,
    updateFrequency: "weekly",
    weHave: "Resoluciones públicas, informes de competencia, expedientes sancionadores, estadísticas de telecomunicaciones y energía",
    cannotHave: "Web JS-rendered requiere headless browser. Expedientes en instrucción (confidenciales). Datos de mercado de operadores privados",
    notes: "Conector listo. Página JS-rendered, requiere headless browser para scraping completo.",
  },
  {
    id: "tribunal-constitucional",
    name: "Tribunal Constitucional — Jurisprudencia",
    shortName: "TC",
    group: "regulador",
    state: "live",
    statusReason: "2 resoluciones recientes ingestadas via scraping del buscador HJ",
    connectorFile: "packages/official-connectors/src/tribunal-constitucional.ts",
    apiEndpoint: "https://hj.tribunalconstitucional.es/",
    ingestionEndpoint: "POST /v1/ingest/tc/run",
    docsCount: 2,
    seedCount: 0,
    lastIngestion: "2026-04-10",
    updateFrequency: "weekly",
    weHave: "Sentencias y autos publicados (texto completo), votos particulares, ponente, fecha, número de resolución",
    cannotHave: "Deliberaciones internas del pleno. Recursos de amparo pendientes de admisión. Borradores de sentencias",
    notes: "2 resoluciones recientes ingestadas via scraping HJ. Scheduler semanal.",
  },
  {
    id: "banco-espana",
    name: "Banco de España — Estadísticas",
    shortName: "BdE",
    group: "regulador",
    state: "built",
    statusReason: "Conector listo para 4 series SDMX — mapeo completo de endpoints pendiente",
    connectorFile: "packages/official-connectors/src/banco-espana.ts",
    apiEndpoint: "https://www.bde.es/wbe/es/estadisticas/",
    ingestionEndpoint: "POST /v1/ingest/bde/run",
    docsCount: 0,
    seedCount: 0,
    updateFrequency: "monthly",
    weHave: "Series estadísticas SDMX: tipos de interés, crédito, balanza de pagos, estabilidad financiera, informes anuales",
    cannotHave: "API SDMX pendiente de mapeo completo. Datos de supervisión bancaria individual (secreto de supervisión). Stress tests confidenciales",
    notes: "Conector listo para 4 series clave. API SDMX pendiente de mapeo de endpoints.",
  },
  {
    id: "tribunal-cuentas",
    name: "Tribunal de Cuentas — Informes de Fiscalización",
    shortName: "T. Cuentas",
    group: "regulador",
    state: "seed-only",
    statusReason: "Solo 3 informes seed — sin API pública, requiere scraping manual",
    apiEndpoint: "https://www.tcu.es/",
    docsCount: 0,
    seedCount: 3,
    updateFrequency: "on-demand",
    weHave: "Informes de fiscalización publicados, resoluciones, importes cuestionados, recomendaciones",
    cannotHave: "Informes en fase de alegaciones. Datos de enjuiciamiento contable (jurisdicción separada). Informes de fiscalización operativa en curso",
    notes: "Informes de auditoría del sector público. 3 informes seed en audit-data.ts.",
  },

  /* ── Unión Europea ── */
  {
    id: "eurostat-spain",
    name: "Eurostat — Indicadores macro España vs UE-27",
    shortName: "Eurostat",
    group: "europa",
    state: "live",
    statusReason: "API REST Eurostat conectada — 9 indicadores macro con comparativa España vs UE-27 en tiempo real",
    connectorFile: "apps/web/lib/eurostat-live.ts",
    apiEndpoint: "https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data/",
    ingestionEndpoint: "GET /api/eurostat",
    docsCount: 9,
    seedCount: 0,
    lastIngestion: "2026-04-11",
    updateFrequency: "monthly",
    weHave: "9 indicadores: deuda, déficit, PIB, PIB per cápita, desempleo, desempleo juvenil, inflación, pobreza, Gini — España vs DE/FR/IT/PT/UE27",
    cannotHave: "Microdatos de encuestas (LFS, SILC) requieren solicitud formal. Indicadores experimentales no disponibles vía API estándar",
    notes: "Live fetcher con cache 6h. Ranking de España entre pares. Alimenta RAG Presupuestario.",
  },
  {
    id: "eurlex-spain",
    name: "EUR-Lex — Legislación Europea aplicable a España",
    shortName: "EUR-Lex",
    group: "europa",
    state: "stub",
    statusReason: "Stub: endpoint SPARQL CELLAR documentado pero no implementado (complejidad alta)",
    connectorFile: "packages/official-connectors/src/eu.ts",
    apiEndpoint: "https://eur-lex.europa.eu/",
    docsCount: 0,
    seedCount: 0,
    updateFrequency: "weekly",
    weHave: "SPARQL endpoint CELLAR documentado: reglamentos, directivas, decisiones por materia, fecha, estado de transposición",
    cannotHave: "Endpoint SPARQL no implementado en producción (complejo). Transposiciones nacionales incompletas. Jurisprudencia TJUE requiere scraping separado",
    notes: "Stub: SPARQL endpoint documentado (CELLAR) pero no implementado en producción.",
  },
  {
    id: "eu-semester",
    name: "Semestre Europeo — Recomendaciones España (CSR)",
    shortName: "EU Semester",
    group: "europa",
    state: "seed-only",
    statusReason: "4 años de CSR hardcodeados (2020-2024) — sin API pública para automatizar",
    connectorFile: "packages/official-connectors/src/eu.ts",
    docsCount: 0,
    seedCount: 4,
    updateFrequency: "annual",
    weHave: "Recomendaciones específicas por país (CSR) 2020-2024, hitos de cumplimiento, evaluaciones de progreso",
    cannotHave: "CSR anteriores a 2020 no incluidos. Negociaciones bilaterales Comisión-España. Indicadores auxiliares del scoreboard MIP",
    notes: "CSR 2020-2024 hardcodeados. 4 años de recomendaciones específicas.",
  },
  {
    id: "nextgeneu-spain",
    name: "NextGenerationEU — Plan de Recuperación España",
    shortName: "NextGenEU",
    group: "europa",
    state: "seed-only",
    statusReason: "6 desembolsos hardcodeados (€53.7B total) — sin API pública de seguimiento",
    connectorFile: "packages/official-connectors/src/eu.ts",
    docsCount: 0,
    seedCount: 6,
    updateFrequency: "on-demand",
    weHave: "6 desembolsos (€53.7B total), hitos y reformas cumplidos, componentes del plan, calendario de pagos",
    cannotHave: "Ejecución real por proyecto/beneficiario (no publicado aún). Auditorías OLAF. Addenda y modificaciones del plan en negociación",
    notes: "6 desembolsos hardcodeados (€53.7B total). Hitos y reformas en seed-data.",
  },
  {
    id: "parlamento-europeo",
    name: "Parlamento Europeo — Eurodiputados españoles",
    shortName: "PE",
    group: "europa",
    state: "live",
    statusReason: "API REST oficial del PE — 354 eurodiputados españoles (históricos + actuales)",
    connectorFile: "packages/official-connectors/src/europarlamento.ts",
    apiEndpoint: "https://data.europarl.europa.eu/api/v2/meps",
    ingestionEndpoint: "POST /v1/ingest/europarlamento/run",
    docsCount: 354,
    seedCount: 0,
    lastIngestion: "2026-04-10",
    updateFrequency: "monthly",
    weHave: "354 eurodiputados españoles (históricos + actuales): nombre, grupo, comisiones, mandatos, contacto vía API REST oficial",
    cannotHave: "Votaciones nominales del PE (API separada). Declaraciones de intereses. Asistencia a plenos y comisiones",
    notes: "354 eurodiputados españoles (históricos + actuales) via API REST oficial. Scheduler mensual.",
  },
  {
    id: "fondos-estructurales",
    name: "Fondos Estructurales UE — Cohesion Data",
    shortName: "FEDER/FSE",
    group: "europa",
    state: "planned",
    statusReason: "Planificado — API Cohesion Data documentada, pendiente de implementar",
    apiEndpoint: "https://cohesiondata.ec.europa.eu/",
    docsCount: 0,
    seedCount: 0,
    updateFrequency: "annual",
    weHave: "API planificada: asignaciones FEDER/FSE/FC por región, programas operativos, tasas de absorción",
    cannotHave: "Proyectos individuales financiados (requiere portal nacional). Irregularidades detectadas por OLAF. Datos provisionales no validados",
  },

  /* ── Social / Open Sources ── */
  {
    id: "wikidata",
    name: "Wikidata — Perfiles estructurados de políticos",
    shortName: "Wikidata",
    group: "social",
    state: "built",
    statusReason: "SPARQL endpoint disponible — fetch bajo demanda, sin almacenamiento persistente",
    connectorFile: "packages/official-connectors/src/social.ts",
    apiEndpoint: "https://query.wikidata.org/sparql",
    docsCount: 0,
    seedCount: 0,
    updateFrequency: "on-demand",
    weHave: "Perfiles estructurados: nombre, partido, cargo, circunscripción, handles Twitter/Mastodon/Bluesky, foto, fecha de nacimiento",
    cannotHave: "Datos no verificados por la comunidad Wikidata. Handles sociales pueden estar desactualizados. Rate-limiting en consultas SPARQL pesadas",
    notes: "SPARQL query para diputados/senadores con handles sociales. Fetch live, sin almacenamiento.",
  },
  {
    id: "mastodon-bluesky",
    name: "Mastodon / Bluesky — Posts públicos de políticos",
    shortName: "Social",
    group: "social",
    state: "built",
    statusReason: "APIs públicas sin auth — fetch bajo demanda, sin almacenamiento persistente",
    connectorFile: "packages/official-connectors/src/social.ts",
    apiEndpoint: "https://public.api.bsky.app/xrpc/",
    docsCount: 0,
    seedCount: 0,
    updateFrequency: "realtime",
    weHave: "Posts públicos de cuentas verificadas en Mastodon (ActivityPub) y Bluesky (AT Protocol) sin autenticación",
    cannotHave: "Twitter/X (API de pago, >40.000€/año). Posts borrados o editados. DMs o contenido privado. Métricas de engagement fiables",
    notes: "ActivityPub + AT Protocol. Sin auth requerida. Sin almacenamiento persistente.",
  },
  {
    id: "rss-partidos",
    name: "RSS — Comunicación oficial de partidos",
    shortName: "RSS",
    group: "social",
    state: "built",
    statusReason: "3 feeds (PSOE, PP, Sumar) — otros partidos sin RSS público (Vox, Junts, ERC)",
    connectorFile: "packages/official-connectors/src/social.ts",
    docsCount: 0,
    seedCount: 3,
    updateFrequency: "realtime",
    weHave: "Notas de prensa, comunicados y noticias de PSOE, PP y Sumar vía RSS. Título, enlace, fecha, resumen",
    cannotHave: "Partidos sin feed RSS (Vox, Junts, ERC, etc.). Comunicados internos. Actas de comités ejecutivos",
    notes: "3 feeds hardcodeados (PSOE, PP, Sumar). Polling activo vía rss-store.ts.",
  },
  {
    id: "wikipedia",
    name: "Wikipedia — Biografías de políticos",
    shortName: "Wikipedia",
    group: "social",
    state: "built",
    statusReason: "REST API disponible — fetch bajo demanda, ~60% de diputados sin artículo",
    connectorFile: "packages/official-connectors/src/social.ts",
    apiEndpoint: "https://es.wikipedia.org/api/rest_v1/",
    docsCount: 0,
    seedCount: 0,
    updateFrequency: "on-demand",
    weHave: "Biografías completas, extracto, imagen, categorías, referencias externas de políticos con artículo en Wikipedia ES",
    cannotHave: "Políticos sin artículo en Wikipedia (~60% de diputados). Información no verificada editorialmente. Sesgo de cobertura por notoriedad",
    notes: "REST API. Fetch bajo demanda, sin almacenamiento.",
  },

  /* ── Administración Local ── */
  {
    id: "datos-gob",
    name: "datos.gob.es — Portal de Datos Abiertos de España",
    shortName: "datos.gob",
    group: "local",
    state: "live",
    statusReason: "API CKAN Linked Data conectada — 50+ datasets ingestados semanalmente",
    connectorFile: "packages/official-connectors/src/datos-gob.ts",
    apiEndpoint: "https://datos.gob.es/apidata/catalog/dataset.json",
    ingestionEndpoint: "POST /v1/ingest/datos-gob/run",
    docsCount: 50,
    seedCount: 0,
    lastIngestion: "2026-04-10",
    updateFrequency: "weekly",
    weHave: "Catálogo CKAN con metadatos de 50+ datasets, distribuciones (CSV, JSON, XML), publishers, licencias, frecuencia",
    cannotHave: "Contenido real de cada dataset (solo metadatos del catálogo). Datasets de CCAA no federados. Calidad variable entre publishers",
    notes: "50 datasets del catálogo CKAN ingestados. API Linked Data. Scheduler semanal.",
  },
  {
    id: "ine-tempus",
    name: "INE — TEMPUS3 API (demografía, economía, sociedad)",
    shortName: "INE",
    group: "local",
    state: "live",
    statusReason: "API TEMPUS3 conectada — 8 indicadores en tiempo real (paro, IPC, PIB, población, etc.)",
    connectorFile: "apps/web/lib/ine-live.ts",
    apiEndpoint: "https://servicios.ine.es/wstempus/js/ES/",
    ingestionEndpoint: "GET /api/ine",
    docsCount: 8,
    seedCount: 12,
    lastIngestion: "2026-04-11",
    updateFrequency: "monthly",
    weHave: "8 indicadores live: tasa de paro (EPA), ocupados, IPC general, IPC variación, PIB trimestral, IPV, población, IPI. Tendencia y variación automáticas",
    cannotHave: "Microdatos de encuestas (EPA, ECV) requieren solicitud al INE. Series a nivel municipal incompletas",
    notes: "Live fetcher con cache 1h. Sync getter para RAG Presupuestario. 8 tablas INE conectadas.",
  },
  {
    id: "infoelectoral",
    name: "Infoelectoral — Resultados electorales (Interior)",
    shortName: "Elecciones",
    group: "local",
    state: "live",
    statusReason: "4 elecciones generales (2016-2023) catalogadas — WAF bloquea scraping automatizado",
    connectorFile: "packages/official-connectors/src/elecciones.ts",
    apiEndpoint: "https://infoelectoral.interior.gob.es/",
    ingestionEndpoint: "POST /v1/ingest/elecciones/run",
    docsCount: 49,
    seedCount: 0,
    updateFrequency: "on-demand",
    weHave: "Resultados oficiales de 4 generales (2016-2023): votos por partido y circunscripción, escaños, participación, censo",
    cannotHave: "WAF bloquea acceso automatizado. Resultados mesa a mesa (ficheros .DAT). Elecciones municipales y autonómicas (formato diferente). Tiempo real noche electoral",
    notes: "infoelectoral.interior.gob.es bloqueado por WAF. Catálogo estático con resultados oficiales de 4 elecciones generales recientes (2016, 2019-abr, 2019-nov, 2023). 4 fichas meta + 49 resultados por partido.",
  },
  {
    id: "registro-entidades-locales",
    name: "Registro de Entidades Locales (SEAP)",
    shortName: "REL",
    group: "local",
    state: "planned",
    statusReason: "Planificado — API no documentada públicamente",
    apiEndpoint: "https://ssweb.seap.minhap.es/REL/",
    docsCount: 0,
    seedCount: 0,
    updateFrequency: "monthly",
    weHave: "Planificado: directorio de 8.131 municipios, mancomunidades, comarcas, diputaciones con código INE y datos básicos",
    cannotHave: "API no documentada públicamente. Datos de cargos electos locales en registro separado (RedSARA). Actualizaciones con retraso",
  },
  {
    id: "concejales-redsara",
    name: "Registro de Concejales — RedSARA",
    shortName: "Concejales",
    group: "local",
    state: "planned",
    statusReason: "Bloqueado — requiere certificado digital de administración pública (RedSARA)",
    apiEndpoint: "https://concejales.redsara.es/",
    docsCount: 0,
    seedCount: 0,
    updateFrequency: "on-demand",
    weHave: "Planificado: 67.515 concejales electos en 8.131 municipios — nombre, partido, municipio, cargo (INE REL 2025)",
    cannotHave: "Acceso restringido: requiere certificado digital de administración pública. Sin API pública. Solo accesible desde RedSARA",
    notes: "67.515 concejales objetivo (INE 2025). Acceso restringido, requiere certificado digital.",
  },
  {
    id: "madrid-datos",
    name: "Datos Abiertos Madrid",
    shortName: "Madrid",
    group: "local",
    state: "planned",
    statusReason: "Planificado — API CKAN disponible, pendiente de mapeo",
    apiEndpoint: "https://datos.madrid.es/",
    docsCount: 0,
    seedCount: 0,
    updateFrequency: "on-demand",
    weHave: "Planificado: catálogo de datos abiertos del Ayuntamiento de Madrid — presupuestos, contratación, urbanismo, movilidad",
    cannotHave: "Datos de otras concejalías sin publicar. Expedientes urbanísticos en tramitación. Actas de juntas de distrito no digitalizadas",
  },
  {
    id: "bcn-opendata",
    name: "Open Data Barcelona",
    shortName: "Barcelona",
    group: "local",
    state: "planned",
    statusReason: "Planificado — API CKAN disponible, datos en catalán sin traducción automática",
    apiEndpoint: "https://opendata-ajuntament.barcelona.cat/",
    docsCount: 0,
    seedCount: 0,
    updateFrequency: "on-demand",
    weHave: "Planificado: 500+ datasets del Ajuntament — transporte, turismo, economía, medio ambiente, demografía",
    cannotHave: "API CKAN requiere mapeo específico. Datos en catalán sin traducción automática. Integración con Àrea Metropolitana pendiente",
  },

  /* ── Ministerios del Gobierno de España ── */
  {
    id: "mpr-presidencia",
    name: "Ministerio de la Presidencia, Justicia y Relaciones con las Cortes",
    shortName: "Presidencia",
    group: "ministerios",
    state: "seed-only",
    statusReason: "Solo datos seed — sin API pública, portal institucional sin datos abiertos",
    apiEndpoint: "https://www.mpr.gob.es/",
    docsCount: 0,
    seedCount: 2,
    updateFrequency: "monthly",
    weHave: "Estructura orgánica, agenda ministerial, relación de altos cargos, notas de prensa, acuerdos Consejo de Ministros",
    cannotHave: "Orden del día del Consejo de Ministros antes de publicación. Comunicaciones internas con Cortes. Informes jurídicos reservados",
    notes: "Portal institucional, agenda ministerial y relaciones con Cortes.",
  },
  {
    id: "mineco",
    name: "Ministerio de Economía, Comercio y Empresa",
    shortName: "Economía",
    group: "ministerios",
    state: "seed-only",
    statusReason: "Solo datos seed — indicadores macro cubiertos vía INE y Eurostat",
    apiEndpoint: "https://www.mineco.gob.es/",
    docsCount: 0,
    seedCount: 3,
    updateFrequency: "monthly",
    weHave: "Previsiones macro, indicadores de comercio exterior, informes de coyuntura, convocatorias de ayudas a empresas",
    cannotHave: "Borradores de previsiones antes de publicación. Datos confidenciales de negociaciones comerciales. Informes CDGAE internos",
    notes: "Política económica, comercio, competitividad. Indicadores macro y previsiones.",
  },
  {
    id: "hacienda-ministerio",
    name: "Ministerio de Hacienda",
    shortName: "Hacienda Min.",
    group: "ministerios",
    state: "seed-only",
    statusReason: "Solo datos seed — PGE y financiación disponibles en formatos PDF/HTML",
    apiEndpoint: "https://www.hacienda.gob.es/",
    docsCount: 0,
    seedCount: 4,
    updateFrequency: "monthly",
    weHave: "PGE (presupuestos), financiación autonómica y local, estabilidad presupuestaria, liquidaciones, deuda de CCAA",
    cannotHave: "Negociaciones de PGE en curso. Datos individuales de contribuyentes. Propuestas de reforma fiscal no publicadas",
    notes: "Presupuestos Generales del Estado, financiación autonómica y local, estabilidad presupuestaria.",
  },
  {
    id: "miteco",
    name: "Ministerio para la Transición Ecológica y el Reto Demográfico",
    shortName: "Transición Ecológica",
    group: "ministerios",
    state: "seed-only",
    statusReason: "Solo datos seed — sin API pública, datos ambientales en portales específicos",
    apiEndpoint: "https://www.miteco.gob.es/",
    docsCount: 0,
    seedCount: 2,
    updateFrequency: "monthly",
    weHave: "Inventario de emisiones GEI, estado de masas de agua, PNIEC, planes hidrológicos, red de calidad del aire",
    cannotHave: "Datos en tiempo real de estaciones de medición (requiere API específica). EIA en tramitación. Expedientes sancionadores ambientales",
    notes: "Cambio climático, agua, biodiversidad, energía y reto demográfico.",
  },
  {
    id: "mitma",
    name: "Ministerio de Transportes y Movilidad Sostenible",
    shortName: "Transportes",
    group: "ministerios",
    state: "seed-only",
    statusReason: "Solo datos seed — estadísticas de tráfico en informes PDF",
    apiEndpoint: "https://www.transportes.gob.es/",
    docsCount: 0,
    seedCount: 2,
    updateFrequency: "monthly",
    weHave: "Estadísticas de tráfico, datos de puertos y aeropuertos, vivienda (visados, precios), atlas digital de áreas urbanas",
    cannotHave: "Datos de operadores privados de transporte. Estudios informativos de infraestructuras en fase previa. Datos de Correos",
    notes: "Infraestructuras, movilidad, vivienda, agenda urbana.",
  },
  {
    id: "mecd",
    name: "Ministerio de Educación, Formación Profesional y Deportes",
    shortName: "Educación",
    group: "ministerios",
    state: "seed-only",
    statusReason: "Solo datos seed — estadísticas educativas en informes PDF/Excel",
    apiEndpoint: "https://www.educacionyfp.gob.es/",
    docsCount: 0,
    seedCount: 2,
    updateFrequency: "monthly",
    weHave: "Estadísticas educativas (alumnado, centros, profesorado, gasto), convocatorias de becas, resultados PISA/TIMSS",
    cannotHave: "Microdatos de alumnos individuales (LOPD). Resultados por centro educativo. Expedientes de homologación de títulos",
    notes: "Estadísticas educativas, becas, formación profesional, sistema universitario.",
  },
  {
    id: "mscbs",
    name: "Ministerio de Sanidad, Consumo y Bienestar Social",
    shortName: "Sanidad",
    group: "ministerios",
    state: "seed-only",
    statusReason: "Solo datos seed — estadísticas SNS en informes PDF",
    apiEndpoint: "https://www.sanidad.gob.es/",
    docsCount: 0,
    seedCount: 2,
    updateFrequency: "monthly",
    weHave: "Estadísticas SNS, listas de espera agregadas, gasto farmacéutico, alertas sanitarias, encuesta nacional de salud",
    cannotHave: "Datos clínicos individuales (secreto médico). Precios de compra de medicamentos por CCAA. Actas de la comisión interterritorial",
    notes: "Sistema Nacional de Salud, estadísticas sanitarias, alertas, consumo.",
  },
  {
    id: "mdsocialvivienda",
    name: "Ministerio de Vivienda y Agenda Urbana",
    shortName: "Vivienda",
    group: "ministerios",
    state: "planned",
    statusReason: "Planificado — sin API pública, índice de alquiler en formato web",
    apiEndpoint: "https://www.mivau.gob.es/",
    docsCount: 0,
    seedCount: 0,
    updateFrequency: "monthly",
    weHave: "Planificado: índice de precios de alquiler, plan estatal de vivienda, ayudas a rehabilitación, zonas tensionadas",
    cannotHave: "Registro de grandes tenedores (competencia autonómica). Datos de contratos de alquiler individuales (LOPD). Inspecciones de vivienda",
    notes: "Política de vivienda, alquiler, rehabilitación y agenda urbana.",
  },
  {
    id: "mtrabajo",
    name: "Ministerio de Trabajo y Economía Social",
    shortName: "Trabajo",
    group: "ministerios",
    state: "seed-only",
    statusReason: "Solo datos seed — convenios colectivos sin API estructurada",
    apiEndpoint: "https://www.mites.gob.es/",
    docsCount: 0,
    seedCount: 2,
    updateFrequency: "monthly",
    weHave: "Convenios colectivos registrados, conflictos laborales, EREs autorizados, economía social (cooperativas), estadísticas de huelgas",
    cannotHave: "Actas de inspección de trabajo individuales. Expedientes sancionadores en curso. Negociaciones de diálogo social en curso",
    notes: "Relaciones laborales, economía social, inspección de trabajo, diálogo social.",
  },
  {
    id: "mintur",
    name: "Ministerio de Industria y Turismo",
    shortName: "Industria",
    group: "ministerios",
    state: "seed-only",
    statusReason: "Solo datos seed — Frontur/Egatur cubiertos parcialmente vía INE",
    apiEndpoint: "https://www.mintur.gob.es/",
    docsCount: 0,
    seedCount: 2,
    updateFrequency: "monthly",
    weHave: "Estadísticas de turismo (Frontur, Egatur, ETR), encuestas de ocupación hotelera, indicadores industriales, registro PYME",
    cannotHave: "Datos individuales de empresas (secreto estadístico). Planes estratégicos en fase de consulta. Datos de destinos turísticos a nivel local",
    notes: "Política industrial, turismo, comercio interior, PYMEs.",
  },
  {
    id: "maec",
    name: "Ministerio de Asuntos Exteriores, Unión Europea y Cooperación",
    shortName: "Exteriores",
    group: "ministerios",
    state: "planned",
    statusReason: "Planificado — sin API pública, datos de cooperación dispersos",
    apiEndpoint: "https://www.exteriores.gob.es/",
    docsCount: 0,
    seedCount: 0,
    updateFrequency: "monthly",
    weHave: "Planificado: red de embajadas y consulados, cooperación al desarrollo (AECID), tratados internacionales, comunicados",
    cannotHave: "Cables diplomáticos y telegramas (clasificados). Negociaciones bilaterales en curso. Información consular individual",
    notes: "Política exterior, cooperación al desarrollo, asuntos consulares, UE.",
  },
  {
    id: "mju",
    name: "Ministerio de Justicia",
    shortName: "Justicia",
    group: "ministerios",
    state: "planned",
    statusReason: "Planificado — estadística judicial depende del CGPJ, sin API directa",
    apiEndpoint: "https://www.mjusticia.gob.es/",
    docsCount: 0,
    seedCount: 0,
    updateFrequency: "monthly",
    weHave: "Planificado: estadística judicial (CGPJ), registros civiles, antecedentes penales (consulta pública), apostillas",
    cannotHave: "Expedientes judiciales individuales (secreto de sumario). Datos del registro de penados. Informes de la fiscalía no publicados",
    notes: "Administración de justicia, registros civiles, cooperación jurídica.",
  },
  {
    id: "mdefensa",
    name: "Ministerio de Defensa",
    shortName: "Defensa",
    group: "ministerios",
    state: "planned",
    statusReason: "Planificado — información clasificada, datos públicos limitados",
    apiEndpoint: "https://www.defensa.gob.es/",
    docsCount: 0,
    seedCount: 0,
    updateFrequency: "monthly",
    weHave: "Planificado: presupuesto de defensa, misiones internacionales activas, estructura de las FAS, convocatorias de empleo",
    cannotHave: "Información clasificada (secreto de estado). Contratos de defensa con cláusula de seguridad. Despliegues operativos",
    notes: "Política de defensa, misiones internacionales, industria de defensa.",
  },
  {
    id: "minterior",
    name: "Ministerio del Interior",
    shortName: "Interior",
    group: "ministerios",
    state: "seed-only",
    statusReason: "Solo datos seed — anuario estadístico en PDF, sin API estructurada",
    apiEndpoint: "https://www.interior.gob.es/",
    docsCount: 0,
    seedCount: 3,
    updateFrequency: "monthly",
    weHave: "Anuario estadístico (criminalidad), datos de tráfico (DGT), resultados electorales, infracciones, población reclusa",
    cannotHave: "Datos policiales operativos (secreto). Identidad de víctimas/agresores. Información sobre operaciones antiterroristas. Datos de vigilancia",
    notes: "Seguridad ciudadana, tráfico, instituciones penitenciarias, procesos electorales.",
  },
  {
    id: "migualdad",
    name: "Ministerio de Igualdad",
    shortName: "Igualdad",
    group: "ministerios",
    state: "planned",
    statusReason: "Planificado — estadísticas de violencia de género en portal específico",
    apiEndpoint: "https://www.igualdad.gob.es/",
    docsCount: 0,
    seedCount: 0,
    updateFrequency: "monthly",
    weHave: "Planificado: estadísticas de violencia de género, brecha salarial, planes de igualdad de empresas, recursos para víctimas",
    cannotHave: "Datos individuales de víctimas (protección especial). Denuncias en instrucción. Informes de evaluación de impacto de género no publicados",
    notes: "Políticas de igualdad, violencia de género, diversidad, LGTBI.",
  },
  {
    id: "minclusión",
    name: "Ministerio de Inclusión, Seguridad Social y Migraciones",
    shortName: "Inclusión",
    group: "ministerios",
    state: "seed-only",
    statusReason: "Solo datos seed — pensiones y afiliación cubiertos vía Seg. Social e INE",
    apiEndpoint: "https://www.inclusion.gob.es/",
    docsCount: 0,
    seedCount: 2,
    updateFrequency: "monthly",
    weHave: "Estadísticas de pensiones, IMV (beneficiarios, cuantías), afiliación de extranjeros, flujos migratorios agregados",
    cannotHave: "Datos individuales de beneficiarios (LOPD). Expedientes de asilo en curso. Datos biométricos de control migratorio",
    notes: "Seguridad Social, migraciones, ingreso mínimo vital, pensiones.",
  },
  {
    id: "mcultura",
    name: "Ministerio de Cultura",
    shortName: "Cultura",
    group: "ministerios",
    state: "planned",
    statusReason: "Planificado — anuario estadístico cultural en PDF",
    apiEndpoint: "https://www.cultura.gob.es/",
    docsCount: 0,
    seedCount: 0,
    updateFrequency: "monthly",
    weHave: "Planificado: anuario de estadísticas culturales, catálogo de patrimonio, agenda de museos estatales, ayudas y subvenciones",
    cannotHave: "Inventario completo de bienes culturales (parcialmente digitalizado). Datos de taquilla de cine (fuente privada: Comscore). Valoraciones de patrimonio",
    notes: "Patrimonio cultural, bibliotecas, museos, artes escénicas, propiedad intelectual.",
  },
  {
    id: "mciencia",
    name: "Ministerio de Ciencia, Innovación y Universidades",
    shortName: "Ciencia",
    group: "ministerios",
    state: "seed-only",
    statusReason: "Solo datos seed — convocatorias I+D sin API pública estructurada",
    apiEndpoint: "https://www.ciencia.gob.es/",
    docsCount: 0,
    seedCount: 2,
    updateFrequency: "monthly",
    weHave: "Plan estatal de I+D+i, convocatorias (FPU, FPI, Ramón y Cajal), gasto en I+D por CCAA, rankings universitarios",
    cannotHave: "Evaluaciones individuales de proyectos (confidencial ANEP/AEI). Borradores de convocatorias. Datos de patentes por investigador",
    notes: "I+D+i, universidades, transferencia de conocimiento, plan estatal de investigación.",
  },
  {
    id: "mderechossociales",
    name: "Ministerio de Derechos Sociales y Agenda 2030",
    shortName: "Derechos Sociales",
    group: "ministerios",
    state: "planned",
    statusReason: "Planificado — SAAD y dependencia sin API pública",
    apiEndpoint: "https://www.mdsocialesa2030.gob.es/",
    docsCount: 0,
    seedCount: 0,
    updateFrequency: "monthly",
    weHave: "Planificado: SAAD (dependencia), informe ODS, estadísticas de servicios sociales, catálogo de prestaciones",
    cannotHave: "Expedientes individuales de dependencia (LOPD). Evaluaciones de impacto ODS internas. Datos de centros de menores tutelados",
    notes: "Servicios sociales, dependencia, discapacidad, infancia, agenda 2030.",
  },
  {
    id: "mtransformacion",
    name: "Ministerio para la Transformación Digital y de la Función Pública",
    shortName: "Transformación Digital",
    group: "ministerios",
    state: "seed-only",
    statusReason: "Solo datos seed — indicadores DESI disponibles vía Eurostat",
    apiEndpoint: "https://portal.mineco.gob.es/",
    docsCount: 0,
    seedCount: 2,
    updateFrequency: "monthly",
    weHave: "España Digital 2026, indicadores DESI, oferta de empleo público, registro de funcionarios agregado, plan de IA",
    cannotHave: "Datos individuales de funcionarios (LOPD). Contratos TIC clasificados. Auditorías de ciberseguridad del sector público",
    notes: "Digitalización, IA, función pública, administración electrónica, España Digital 2026.",
  },
  {
    id: "magricultura",
    name: "Ministerio de Agricultura, Pesca y Alimentación",
    shortName: "Agricultura",
    group: "ministerios",
    state: "seed-only",
    statusReason: "Solo datos seed — anuario agrario en PDF, sin API REST",
    apiEndpoint: "https://www.mapa.gob.es/",
    docsCount: 0,
    seedCount: 3,
    updateFrequency: "monthly",
    weHave: "Anuario de estadística agraria, ayudas PAC agregadas, precios de alimentos, cuotas pesqueras, alertas alimentarias",
    cannotHave: "Datos individuales de beneficiarios PAC >1.250€ (parcialmente público). Inspecciones AESAN individuales. Negociaciones de cuotas pesqueras UE",
    notes: "PAC, pesca, cadena alimentaria, desarrollo rural, estadísticas agrarias.",
  },

  /* ── Fuentes Autonómicas (17 CCAA × 3 fuentes = 51) ── */
  {
    id: "ccaa-17",
    name: "17 Comunidades Autónomas — Gobierno, Parlamento, Boletín",
    shortName: "17 CCAA",
    group: "autonomico",
    state: "seed-only",
    statusReason: "51 URLs registradas — sin ingesta activa, cada CCAA tiene formato web diferente",
    docsCount: 0,
    seedCount: 51,
    updateFrequency: "on-demand",
    weHave: "51 fuentes registradas (17×3): URLs de gobierno, parlamento y boletín oficial de cada CCAA verificadas y normalizadas",
    cannotHave: "Ingesta activa de contenido (sin scrapers autonómicos). Cada CCAA tiene formato web diferente. Boletines sin API estandarizada",
    notes: "51 fuentes territoriales registradas (17×3). URLs verificadas, sin ingesta activa.",
  },
];

/* ── Aggregate stats ── */

export const ingestionStats = {
  total: dataSourceStatuses.length,
  live: dataSourceStatuses.filter((s) => s.state === "live").length,
  built: dataSourceStatuses.filter((s) => s.state === "built").length,
  seedOnly: dataSourceStatuses.filter((s) => s.state === "seed-only").length,
  stub: dataSourceStatuses.filter((s) => s.state === "stub").length,
  planned: dataSourceStatuses.filter((s) => s.state === "planned").length,
  totalDocs: dataSourceStatuses.reduce((s, d) => s + d.docsCount, 0),
  totalSeed: dataSourceStatuses.reduce((s, d) => s + d.seedCount, 0),
};

export const stateLabels: Record<IngestionState, string> = {
  live: "En producción",
  built: "Conector listo",
  "seed-only": "Solo seed",
  stub: "Stub parcial",
  planned: "Planificado",
};

export const stateColors: Record<IngestionState, string> = {
  live: "#047857",
  built: "#1d4ed8",
  "seed-only": "#b45309",
  stub: "#7c3aed",
  planned: "#6b7280",
};

export const groupLabels: Record<string, string> = {
  estado: "Estado",
  hacienda: "Hacienda",
  empleo: "Empleo",
  regulador: "Reguladores",
  europa: "Unión Europea",
  social: "Social / Open",
  ministerios: "Ministerios",
  local: "Local",
  autonomico: "Autonómico",
};
