/* ═══════════════════════════════════════════════════════════════════════════
   Congreso de los Diputados — XV Legislatura
   350 diputados · 9 grupos parlamentarios
   Source: https://www.congreso.es/es/opendata/diputados
   Last fetched: 2026-04-10
   ═══════════════════════════════════════════════════════════════════════════ */

export interface CongressDeputySeed {
  slug: string;
  fullName: string;
  constituency: string;
  electoralFormation: string;
  parliamentaryGroup: string;
}

export const congressDeputies: CongressDeputySeed[] = [
  { slug: "abades-martinez-cristina", fullName: "Abades Martínez, Cristina", constituency: "Lugo", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "abascal-conde-santiago", fullName: "Abascal Conde, Santiago", constituency: "Madrid", electoralFormation: "VOX", parliamentaryGroup: "Grupo Parlamentario VOX" },
  { slug: "acedo-reyes-sofia", fullName: "Acedo Reyes, Sofía", constituency: "Melilla", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "aceves-galindo-jose-luis", fullName: "Aceves Galindo, José Luis", constituency: "Segovia", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "adrio-taracido-maria", fullName: "Adrio Taracido, María", constituency: "Pontevedra", electoralFormation: "PsdeG-PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "agirretxea-urresti-joseba-andoni", fullName: "Agirretxea Urresti, Joseba Andoni", constituency: "Gipuzkoa", electoralFormation: "EAJ-PNV", parliamentaryGroup: "Grupo Parlamentario Vasco (EAJ-PNV)" },
  { slug: "aguera-gago-cristina", fullName: "Agüera Gago, Cristina", constituency: "Barcelona", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "aguirre-gil-de-biedma-rocio", fullName: "Aguirre Gil de Biedma, Rocío", constituency: "Madrid", electoralFormation: "VOX", parliamentaryGroup: "Grupo Parlamentario VOX" },
  { slug: "aizcorbe-torra-juan-jose", fullName: "Aizcorbe Torra, Juan José", constituency: "Barcelona", electoralFormation: "VOX", parliamentaryGroup: "Grupo Parlamentario VOX" },
  { slug: "aizpurua-arzallus-mertxe", fullName: "Aizpurua Arzallus, Mertxe", constituency: "Gipuzkoa", electoralFormation: "EH Bildu", parliamentaryGroup: "Grupo Parlamentario Euskal Herria Bildu" },
  { slug: "alcaraz-martos-francisco-jose", fullName: "Alcaraz Martos, Francisco José", constituency: "Jaén", electoralFormation: "VOX", parliamentaryGroup: "Grupo Parlamentario VOX" },
  { slug: "alfonso-cendon-javier", fullName: "Alfonso Cendón, Javier", constituency: "León", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "alfonso-silvestre-alma", fullName: "Alfonso Silvestre, Alma", constituency: "Valencia/València", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "alia-aguado-maria-pilar", fullName: "Alía Aguado, María Pilar", constituency: "Toledo", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "almiron-ruiz-oriol", fullName: "Almirón Ruiz, Oriol", constituency: "Barcelona", electoralFormation: "PSC-PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "almodovar-sanchez-emilia", fullName: "Almodóvar Sánchez, Emilia", constituency: "Cáceres", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "alonso-cantorne-felix", fullName: "Alonso Cantorné, Fèlix", constituency: "Tarragona", electoralFormation: "SUMAR", parliamentaryGroup: "Grupo Parlamentario Plurinacional SUMAR" },
  { slug: "alos-lopez-ana-isabel", fullName: "Alós López, Ana Isabel", constituency: "Huesca", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "alvarez-de-toledo-peralta-ramos-cayetana", fullName: "Álvarez de Toledo Peralta-Ramos, Cayetana", constituency: "Madrid", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "alvarez-fanjul-beatriz", fullName: "Álvarez Fanjul, Beatriz", constituency: "Bizkaia", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "alvarez-gonzalez-alicia", fullName: "Álvarez González, Alicia", constituency: "S/C Tenerife", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "alvaro-vidal-francesc-marc", fullName: "Álvaro Vidal, Francesc-Marc", constituency: "Barcelona", electoralFormation: "ERC", parliamentaryGroup: "Grupo Parlamentario Republicano" },
  { slug: "andala-ubbi-teslem", fullName: "Andala Ubbi, Teslem", constituency: "Madrid", electoralFormation: "SUMAR", parliamentaryGroup: "Grupo Parlamentario Plurinacional SUMAR" },
  { slug: "andres-anon-carmen", fullName: "Andrés Añón, Carmen", constituency: "Barcelona", electoralFormation: "PSC-PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "antunano-colina-pablo", fullName: "Antuñano Colina, Pablo", constituency: "Cantabria", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "aragones-mendiguchia-carlos", fullName: "Aragonés Mendiguchía, Carlos", constituency: "Madrid", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "aranda-vargas-francisco", fullName: "Aranda Vargas, Francisco", constituency: "Barcelona", electoralFormation: "PSC-PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "argota-castro-trinidad-carmen", fullName: "Argota Castro, Trinidad Carmen", constituency: "Sevilla", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "arguelles-garcia-silverio", fullName: "Argüelles García, Silverio", constituency: "Asturias", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "armario-gonzalez-blanca", fullName: "Armario González, Blanca", constituency: "Cádiz", electoralFormation: "VOX", parliamentaryGroup: "Grupo Parlamentario VOX" },
  { slug: "armengol-socias-francina", fullName: "Armengol Socias, Francina", constituency: "Balears (Illes)", electoralFormation: "PSIB-PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "arribas-maroto-manuel", fullName: "Arribas Maroto, Manuel", constituency: "Ávila", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "asarta-cuevas-alberto", fullName: "Asarta Cuevas, Alberto", constituency: "Castellón/Castelló", electoralFormation: "VOX", parliamentaryGroup: "Grupo Parlamentario VOX" },
  { slug: "aznar-teruel-evarist", fullName: "Aznar Teruel, Evarist", constituency: "Valencia/València", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "azorin-salar-lazaro", fullName: "Azorín Salar, Lázaro", constituency: "Alicante/Alacant", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "badia-casas-eloi", fullName: "Badia Casas, Eloi", constituency: "Barcelona", electoralFormation: "SUMAR", parliamentaryGroup: "Grupo Parlamentario Plurinacional SUMAR" },
  { slug: "barrio-baroja-carmelo", fullName: "Barrio Baroja, Carmelo", constituency: "Araba/Álava", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "bayon-rolo-juan-andres", fullName: "Bayón Rolo, Juan Andrés", constituency: "Pontevedra", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "beamonte-mesa-luis-maria", fullName: "Beamonte Mesa, Luis María", constituency: "Zaragoza", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "belarra-urteaga-ione", fullName: "Belarra Urteaga, Ione", constituency: "Madrid", electoralFormation: "SUMAR", parliamentaryGroup: "Grupo Parlamentario Mixto" },
  { slug: "belda-perez-pedrero-enrique", fullName: "Belda Pérez-Pedrero, Enrique", constituency: "Ciudad Real", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "belmonte-gomez-rafael-benigno", fullName: "Belmonte Gómez, Rafael Benigno", constituency: "Sevilla", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "bendodo-benasayag-elias", fullName: "Bendodo Benasayag, Elías", constituency: "Málaga", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "bermudez-de-castro-fernandez-jose-antonio", fullName: "Bermúdez de Castro Fernández, José Antonio", constituency: "Salamanca", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "blanco-arrue-gabriel", fullName: "Blanco Arrúe, Gabriel", constituency: "Bizkaia", electoralFormation: "PSE-EE (PSOE)", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "blanquer-alcaraz-patricia", fullName: "Blanquer Alcaraz, Patricia", constituency: "Alicante/Alacant", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "boada-danes-julia", fullName: "Boada Danés, Júlia", constituency: "Girona", electoralFormation: "SUMAR", parliamentaryGroup: "Grupo Parlamentario Plurinacional SUMAR" },
  { slug: "bolanos-garcia-felix", fullName: "Bolaños García, Félix", constituency: "Madrid", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "borrego-cortes-isabel-maria", fullName: "Borrego Cortés, Isabel María", constituency: "Murcia", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "bravo-baena-juan", fullName: "Bravo Baena, Juan", constituency: "Sevilla", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "cabezon-casas-tomas", fullName: "Cabezón Casas, Tomás", constituency: "Soria", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "cacho-isla-ivan", fullName: "Cacho Isla, Iván", constituency: "Navarra", electoralFormation: "PSN-PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "calvo-gomez-pilar", fullName: "Calvo Gómez, Pilar", constituency: "Barcelona", electoralFormation: "JxCAT-JUNTS", parliamentaryGroup: "Grupo Parlamentario Junts per Catalunya" },
  { slug: "camino-minana-victor", fullName: "Camino Miñana, Víctor", constituency: "Valencia/València", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "campos-asensi-jorge", fullName: "Campos Asensi, Jorge", constituency: "Balears (Illes)", electoralFormation: "VOX", parliamentaryGroup: "Grupo Parlamentario VOX" },
  { slug: "canelo-matito-andrea", fullName: "Canelo Matito, Andrea", constituency: "Barcelona", electoralFormation: "PSC-PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "cantalapiedra-alvarez-maria-de-las-mercedes", fullName: "Cantalapiedra Álvarez, María de las Mercedes", constituency: "Valladolid", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "carazo-hermoso-eduardo", fullName: "Carazo Hermoso, Eduardo", constituency: "Valladolid", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "carballedo-berlanga-maria-eugenia", fullName: "Carballedo Berlanga, María Eugenia", constituency: "Madrid", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "castilla-alvarez-maria-carmen", fullName: "Castilla Álvarez, María Carmen", constituency: "Sevilla", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "catalan-higueras-alberto", fullName: "Catalán Higueras, Alberto", constituency: "Navarra", electoralFormation: "UPN", parliamentaryGroup: "Grupo Parlamentario Mixto" },
  { slug: "cavacasillas-rodriguez-antonio", fullName: "Cavacasillas Rodríguez, Antonio", constituency: "Badajoz", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "celaya-brey-javier", fullName: "Celaya Brey, Javier", constituency: "Ceuta", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "cercas-mena-blanca", fullName: "Cercas Mena, Blanca", constituency: "Girona", electoralFormation: "PSC-PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "cervera-pinart-josep-maria", fullName: "Cervera Pinart, Josep Maria", constituency: "Girona", electoralFormation: "JxCAT-JUNTS", parliamentaryGroup: "Grupo Parlamentario Junts per Catalunya" },
  { slug: "chamorro-delmo-ricardo", fullName: "Chamorro Delmo, Ricardo", constituency: "Ciudad Real", electoralFormation: "VOX", parliamentaryGroup: "Grupo Parlamentario VOX" },
  { slug: "clavell-lopez-oscar", fullName: "Clavell López, Óscar", constituency: "Castellón/Castelló", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "clemente-munoz-raquel", fullName: "Clemente Muñoz, Raquel", constituency: "Teruel", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "cobo-carmona-ana", fullName: "Cobo Carmona, Ana", constituency: "Jaén", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "cobo-perez-noelia", fullName: "Cobo Pérez, Noelia", constituency: "Cantabria", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "cobo-vega-manuel", fullName: "Cobo Vega, Manuel", constituency: "Madrid", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "cofino-fernandez-rafael", fullName: "Cofiño Fernández, Rafael", constituency: "Asturias", electoralFormation: "SUMAR", parliamentaryGroup: "Grupo Parlamentario Plurinacional SUMAR" },
  { slug: "conde-bajen-agustin", fullName: "Conde Bajén, Agustín", constituency: "Toledo", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "conde-lopez-francisco-jose", fullName: "Conde López, Francisco José", constituency: "Lugo", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "conesa-coma-ignasi", fullName: "Conesa Coma, Ignasi", constituency: "Barcelona", electoralFormation: "PSC-PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "cortes-carballo-mario", fullName: "Cortés Carballo, Mario", constituency: "Málaga", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "corujo-berriel-maria-dolores", fullName: "Corujo Berriel, María Dolores", constituency: "Palmas (Las)", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "crespin-rubio-rafaela", fullName: "Crespín Rubio, Rafaela", constituency: "Córdoba", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "cruset-domenech-josep-maria", fullName: "Cruset Domènech, Josep Maria", constituency: "Tarragona", electoralFormation: "JxCAT-JUNTS", parliamentaryGroup: "Grupo Parlamentario Junts per Catalunya" },
  { slug: "cruz-santana-gabriel", fullName: "Cruz Santana, Gabriel", constituency: "Huelva", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "cruz-guzman-garcia-maria-soledad", fullName: "Cruz-Guzmán García, María Soledad", constituency: "Sevilla", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "cuesta-rodriguez-maria", fullName: "Cuesta Rodríguez, María", constituency: "Segovia", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "cuevas-larrosa-raul", fullName: "Cuevas Larrosa, Raúl", constituency: "Zaragoza", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "de-la-rosa-baena-olvido", fullName: "De la Rosa Baena, Olvido", constituency: "Granada", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "de-las-cuevas-cortes-felix", fullName: "De las Cuevas Cortés, Félix", constituency: "Cantabria", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "de-los-santos-gonzalez-jaime-miguel", fullName: "De los Santos González, Jaime Miguel", constituency: "Madrid", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "de-luna-tobarra-llanos", fullName: "De Luna Tobarra, Llanos", constituency: "Barcelona", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "de-meer-mendez-rocio", fullName: "De Meer Méndez, Rocío", constituency: "Almería", electoralFormation: "VOX", parliamentaryGroup: "Grupo Parlamentario VOX" },
  { slug: "de-rosa-torner-fernando", fullName: "De Rosa Torner, Fernando", constituency: "Valencia/València", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "del-valle-rodriguez-emilio-jesus", fullName: "Del Valle Rodríguez, Emilio Jesús", constituency: "Cantabria", electoralFormation: "VOX", parliamentaryGroup: "Grupo Parlamentario VOX" },
  { slug: "delgado-arce-celso-luis", fullName: "Delgado Arce, Celso Luis", constituency: "Ourense", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "delgado-taramona-hernandez-jimena", fullName: "Delgado-Taramona Hernández, Jimena", constituency: "Palmas (Las)", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "diaz-marin-raul", fullName: "Díaz Marín, Raúl", constituency: "Rioja (La)", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "diaz-perez-yolanda", fullName: "Díaz Pérez, Yolanda", constituency: "Madrid", electoralFormation: "SUMAR", parliamentaryGroup: "Grupo Parlamentario Plurinacional SUMAR" },
  { slug: "diouf-dioh-luc-andre", fullName: "Diouf Dioh, Luc Andre", constituency: "Palmas (Las)", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "estrems-fayos-etna", fullName: "Estrems Fayos, Etna", constituency: "Girona", electoralFormation: "ERC", parliamentaryGroup: "Grupo Parlamentario Republicano" },
  { slug: "fabra-part-alberto", fullName: "Fabra Part, Alberto", constituency: "Castellón/Castelló", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "fagundez-campo-antidio", fullName: "Fagúndez Campo, Antidio", constituency: "Zamora", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "faneca-lopez-maria-luisa", fullName: "Faneca López, María Luisa", constituency: "Huelva", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "fernandez-beneitez-andrea", fullName: "Fernández Benéitez, Andrea", constituency: "León", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "fernandez-gonzalez-maria-mercedes", fullName: "Fernández González, María Mercedes", constituency: "Asturias", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "fernandez-hernandez-pedro", fullName: "Fernández Hernández, Pedro", constituency: "Zaragoza", electoralFormation: "VOX", parliamentaryGroup: "Grupo Parlamentario VOX" },
  { slug: "fernandez-rios-tomas", fullName: "Fernández Ríos, Tomás", constituency: "Huelva", electoralFormation: "VOX", parliamentaryGroup: "Grupo Parlamentario VOX" },
  { slug: "figaredo-alvarez-sala-jose-maria", fullName: "Figaredo Álvarez-Sala, José María", constituency: "Asturias", electoralFormation: "VOX", parliamentaryGroup: "Grupo Parlamentario VOX" },
  { slug: "flores-juberias-carlos", fullName: "Flores Juberías, Carlos", constituency: "Valencia/València", electoralFormation: "VOX", parliamentaryGroup: "Grupo Parlamentario VOX" },
  { slug: "floriano-corrales-carlos-javier", fullName: "Floriano Corrales, Carlos Javier", constituency: "Cáceres", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "folch-blanc-javier-jose", fullName: "Folch Blanc, Javier José", constituency: "Huesca", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "franco-gonzalez-silvia", fullName: "Franco González, Silvia", constituency: "León", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "fullaondo-la-cruz-marije", fullName: "Fullaondo la Cruz, Marije", constituency: "Bizkaia", electoralFormation: "EH Bildu", parliamentaryGroup: "Grupo Parlamentario Euskal Herria Bildu" },
  { slug: "funez-de-gregorio-carmen", fullName: "Fúnez de Gregorio, Carmen", constituency: "Ciudad Real", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "gallardo-barrena-pedro-ignacio", fullName: "Gallardo Barrena, Pedro Ignacio", constituency: "Cádiz", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "gamarra-ruiz-clavijo-concepcion", fullName: "Gamarra Ruiz-Clavijo, Concepción", constituency: "Rioja (La)", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "garcia-adanero-carlos", fullName: "García Adanero, Carlos", constituency: "Madrid", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "garcia-chavarria-maria-montserrat", fullName: "García Chavarría, María Montserrat", constituency: "Coruña (A)", electoralFormation: "PsdeG-PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "garcia-felix-manuel", fullName: "García Félix, Manuel", constituency: "Huelva", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "garcia-gomis-david", fullName: "García Gomis, David", constituency: "Alicante/Alacant", electoralFormation: "VOX", parliamentaryGroup: "Grupo Parlamentario VOX" },
  { slug: "garcia-gurrutxaga-maria-luisa", fullName: "García Gurrutxaga, María Luisa", constituency: "Gipuzkoa", electoralFormation: "PSE-EE (PSOE)", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "garcia-lopez-maribel", fullName: "García López, Maribel", constituency: "Badajoz", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "garcia-moris-roberto", fullName: "García Morís, Roberto", constituency: "Asturias", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "garre-murcia-cristobal", fullName: "Garre Murcia, Cristóbal", constituency: "Málaga", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "garrido-jimenez-elisa", fullName: "Garrido Jiménez, Elisa", constituency: "Rioja (La)", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "garrido-valenzuela-irene", fullName: "Garrido Valenzuela, Irene", constituency: "Pontevedra", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "gavin-i-valls-isidre", fullName: "Gavin i Valls, Isidre", constituency: "Lleida", electoralFormation: "JxCAT-JUNTS", parliamentaryGroup: "Grupo Parlamentario Junts per Catalunya" },
  { slug: "gil-de-reboleno-lastortres-esther", fullName: "Gil de Reboleño Lastortres, Esther", constituency: "Cádiz", electoralFormation: "SUMAR", parliamentaryGroup: "Grupo Parlamentario Plurinacional SUMAR" },
  { slug: "gil-lazaro-ignacio", fullName: "Gil Lázaro, Ignacio", constituency: "Valencia/València", electoralFormation: "VOX", parliamentaryGroup: "Grupo Parlamentario VOX" },
  { slug: "gomez-pina-luis-antonio", fullName: "Gómez Piña, Luis Antonio", constituency: "Pontevedra", electoralFormation: "PsdeG-PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "gonzalez-gracia-juan-antonio", fullName: "González Gracia, Juan Antonio", constituency: "Badajoz", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "gonzalez-herdaro-ana", fullName: "González Herdaro, Ana", constituency: "Valencia/València", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "gonzalez-lopez-nahuel", fullName: "González López, Nahuel", constituency: "Valencia/València", electoralFormation: "SUMAR", parliamentaryGroup: "Grupo Parlamentario Plurinacional SUMAR" },
  { slug: "gonzalez-vazquez-marta", fullName: "González Vázquez, Marta", constituency: "Coruña (A)", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "gonzalez-robatto-perote-jacobo", fullName: "González-Robatto Perote, Jacobo", constituency: "Granada", electoralFormation: "VOX", parliamentaryGroup: "Grupo Parlamentario VOX" },
  { slug: "gracia-blanco-marta", fullName: "Gracia Blanco, Marta", constituency: "Zaragoza", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "granollers-cunillera-ines", fullName: "Granollers Cunillera, Inés", constituency: "Lleida", electoralFormation: "ERC", parliamentaryGroup: "Grupo Parlamentario Republicano" },
  { slug: "guardiola-salmeron-mirian", fullName: "Guardiola Salmerón, Mirian", constituency: "Murcia", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "guijarro-garcia-txema", fullName: "Guijarro García, Txema", constituency: "Alicante/Alacant", electoralFormation: "SUMAR", parliamentaryGroup: "Grupo Parlamentario Plurinacional SUMAR" },
  { slug: "guinart-moreno-lidia", fullName: "Guinart Moreno, Lídia", constituency: "Barcelona", electoralFormation: "PSC-PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "gutierrez-prieto-sergio", fullName: "Gutiérrez Prieto, Sergio", constituency: "Toledo", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "gutierrez-santiago-victor", fullName: "Gutiérrez Santiago, Víctor", constituency: "Madrid", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "hernandez-quero-carlos", fullName: "Hernández Quero, Carlos", constituency: "Málaga", electoralFormation: "VOX", parliamentaryGroup: "Grupo Parlamentario VOX" },
  { slug: "hernando-fraile-rafael-antonio", fullName: "Hernando Fraile, Rafael Antonio", constituency: "Almería", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "herrera-garcia-milena", fullName: "Herrera García, Milena", constituency: "Balears (Illes)", electoralFormation: "PSIB-PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "herrero-bono-jose-alberto", fullName: "Herrero Bono, José Alberto", constituency: "Teruel", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "hispan-iglesias-de-ussel-pablo", fullName: "Hispán Iglesias de Ussel, Pablo", constituency: "Granada", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "hita-tellez-guillermo", fullName: "Hita Téllez, Guillermo", constituency: "Madrid", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "hoces-iniguez-ignacio", fullName: "Hoces Íñiguez, Ignacio", constituency: "Badajoz", electoralFormation: "VOX", parliamentaryGroup: "Grupo Parlamentario VOX" },
  { slug: "hoyo-julia-belen", fullName: "Hoyo Juliá, Belén", constituency: "Valencia/València", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "ibanez-hernando-angel", fullName: "Ibáñez Hernando, Ángel", constituency: "Burgos", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "ibanez-mezquita-alberto", fullName: "Ibáñez Mezquita, Alberto", constituency: "Valencia/València", electoralFormation: "SUMAR", parliamentaryGroup: "Grupo Parlamentario Plurinacional SUMAR" },
  { slug: "iniesta-egido-isabel", fullName: "Iniesta Egido, Isabel", constituency: "Albacete", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "inarritu-garcia-jon", fullName: "Iñarritu García, Jon", constituency: "Gipuzkoa", electoralFormation: "EH Bildu", parliamentaryGroup: "Grupo Parlamentario Euskal Herria Bildu" },
  { slug: "jerez-antequera-juan-carlos", fullName: "Jerez Antequera, Juan Carlos", constituency: "Barcelona", electoralFormation: "PSC-PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "jimenez-linuesa-beatriz", fullName: "Jiménez Linuesa, Beatriz", constituency: "Cuenca", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "jodar-perez-irene", fullName: "Jódar Pérez, Irene", constituency: "Murcia", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "jorda-i-roura-teresa", fullName: "Jordà i Roura, Teresa", constituency: "Barcelona", electoralFormation: "ERC", parliamentaryGroup: "Grupo Parlamentario Republicano" },
  { slug: "lago-penas-manuel", fullName: "Lago Peñas, Manuel", constituency: "Coruña (A)", electoralFormation: "SUMAR", parliamentaryGroup: "Grupo Parlamentario Plurinacional SUMAR" },
  { slug: "lamua-estanol-marc", fullName: "Lamuà Estañol, Marc", constituency: "Girona", electoralFormation: "PSC-PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "leal-fernandez-isaura", fullName: "Leal Fernández, Isaura", constituency: "Madrid", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "legarda-uriarte-mikel", fullName: "Legarda Uriarte, Mikel", constituency: "Araba/Álava", electoralFormation: "EAJ-PNV", parliamentaryGroup: "Grupo Parlamentario Vasco (EAJ-PNV)" },
  { slug: "lima-garcia-laura-maria", fullName: "Lima García, Laura María", constituency: "S/C Tenerife", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "llamazares-domingo-esther", fullName: "Llamazares Domingo, Esther", constituency: "Asturias", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "lopez-alvarez-patxi", fullName: "López Álvarez, Patxi", constituency: "Bizkaia", electoralFormation: "PSE-EE (PSOE)", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "lopez-cano-ignacio", fullName: "López Cano, Ignacio", constituency: "Málaga", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "lopez-maraver-angel", fullName: "López Maraver, Ángel", constituency: "Guadalajara", electoralFormation: "VOX", parliamentaryGroup: "Grupo Parlamentario VOX" },
  { slug: "lopez-tagliafico-candela", fullName: "López Tagliafico, Candela", constituency: "Barcelona", electoralFormation: "SUMAR", parliamentaryGroup: "Grupo Parlamentario Plurinacional SUMAR" },
  { slug: "lopez-zamora-cristina", fullName: "López Zamora, Cristina", constituency: "Ciudad Real", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "lorente-anaya-macarena", fullName: "Lorente Anaya, Macarena", constituency: "Cádiz", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "lorenzo-cazorla-juan-antonio", fullName: "Lorenzo Cazorla, Juan Antonio", constituency: "Almería", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "losada-fernandez-jose", fullName: "Losada Fernández, José", constituency: "Sevilla", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "macias-gata-alfonso-carlos", fullName: "Macías Gata, Alfonso Carlos", constituency: "Badajoz", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "madrenas-i-mir-marta", fullName: "Madrenas i Mir, Marta", constituency: "Girona", electoralFormation: "JxCAT-JUNTS", parliamentaryGroup: "Grupo Parlamentario Junts per Catalunya" },
  { slug: "madrid-olmo-bartolome", fullName: "Madrid Olmo, Bartolomé", constituency: "Córdoba", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "maldonado-lopez-adriana", fullName: "Maldonado López, Adriana", constituency: "Navarra", electoralFormation: "PSN-PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "marcos-ortega-milagros", fullName: "Marcos Ortega, Milagros", constituency: "Palencia", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "mari-boso-jose-vicente", fullName: "Marí Bosó, José Vicente", constituency: "Balears (Illes)", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "mariscal-anaya-guillermo", fullName: "Mariscal Anaya, Guillermo", constituency: "Palmas (Las)", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "mariscal-zabala-manuel", fullName: "Mariscal Zabala, Manuel", constituency: "Toledo", electoralFormation: "VOX", parliamentaryGroup: "Grupo Parlamentario VOX" },
  { slug: "marques-ates-amador", fullName: "Marqués Atés, Amador", constituency: "Lleida", electoralFormation: "PSC-PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "martin-blanco-nacho", fullName: "Martín Blanco, Nacho", constituency: "Barcelona", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "martin-garcia-pedro-samuel", fullName: "Martín García, Pedro Samuel", constituency: "Salamanca", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "martin-martinez-andreu", fullName: "Martín Martínez, Andreu", constituency: "Tarragona", electoralFormation: "PSC-PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "martin-rodriguez-margarita", fullName: "Martín Rodríguez, Margarita", constituency: "Ourense", electoralFormation: "PsdeG-PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "martin-urriza-carlos", fullName: "Martín Urriza, Carlos", constituency: "Madrid", electoralFormation: "SUMAR", parliamentaryGroup: "Grupo Parlamentario Plurinacional SUMAR" },
  { slug: "martinez-barbero-veronica", fullName: "Martínez Barbero, Verónica", constituency: "Pontevedra", electoralFormation: "SUMAR", parliamentaryGroup: "Grupo Parlamentario Plurinacional SUMAR" },
  { slug: "martinez-gomez-antonio", fullName: "Martínez Gómez, Antonio", constituency: "Albacete", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "martinez-hierro-lander", fullName: "Martínez Hierro, Lander", constituency: "Bizkaia", electoralFormation: "SUMAR", parliamentaryGroup: "Grupo Parlamentario Plurinacional SUMAR" },
  { slug: "martinez-labella-ana", fullName: "Martínez Labella, Ana", constituency: "Almería", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "martinez-ramirez-carmen", fullName: "Martínez Ramírez, Carmen", constituency: "Valencia/València", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "martinez-salmeron-joaquin", fullName: "Martínez Salmerón, Joaquín", constituency: "Murcia", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "martinez-seijo-maria-luz", fullName: "Martínez Seijo, María Luz", constituency: "Palencia", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "matute-garcia-de-jalon-oskar", fullName: "Matute García de Jalón, Oskar", constituency: "Bizkaia", electoralFormation: "EH Bildu", parliamentaryGroup: "Grupo Parlamentario Euskal Herria Bildu" },
  { slug: "mayoral-de-lamo-alberto", fullName: "Mayoral de Lamo, Alberto", constituency: "Córdoba", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "mayoral-perez-jesus", fullName: "Mayoral Pérez, Jesús", constituency: "Toledo", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "mejias-sanchez-carina", fullName: "Mejías Sánchez, Carina", constituency: "Barcelona", electoralFormation: "VOX", parliamentaryGroup: "Grupo Parlamentario VOX" },
  { slug: "melgarejo-moreno-joaquin", fullName: "Melgarejo Moreno, Joaquín", constituency: "Alicante/Alacant", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "mellado-sierra-valle", fullName: "Mellado Sierra, Valle", constituency: "Tarragona", electoralFormation: "PSC-PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "mendez-monasterio-lourdes", fullName: "Méndez Monasterio, Lourdes", constituency: "Murcia", electoralFormation: "VOX", parliamentaryGroup: "Grupo Parlamentario VOX" },
  { slug: "mercadal-baquero-pepe", fullName: "Mercadal Baquero, Pepe", constituency: "Balears (Illes)", electoralFormation: "PSIB-PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "merino-martinez-javier", fullName: "Merino Martínez, Javier", constituency: "Rioja (La)", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "mesquida-mayans-joan", fullName: "Mesquida Mayans, Joan", constituency: "Balears (Illes)", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "mico-mico-agueda", fullName: "Micó Micó, Àgueda", constituency: "Valencia/València", electoralFormation: "SUMAR", parliamentaryGroup: "Grupo Parlamentario Mixto" },
  { slug: "minguez-garcia-montse", fullName: "Mínguez García, Montse", constituency: "Lleida", electoralFormation: "PSC-PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "molina-leon-ainhoa", fullName: "Molina León, Ainhoa", constituency: "S/C Tenerife", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "moneo-diez-maria-sandra", fullName: "Moneo Díez, María Sandra", constituency: "Burgos", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "montavez-aguillaume-vicente", fullName: "Montávez Aguillaume, Vicente", constituency: "Madrid", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "montero-cuadrado-maria-jesus", fullName: "Montero Cuadrado, María Jesús", constituency: "Sevilla", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "montesinos-de-miguel-macarena", fullName: "Montesinos de Miguel, Macarena", constituency: "Alicante/Alacant", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "moraleja-gomez-tristana-maria", fullName: "Moraleja Gómez, Tristana María", constituency: "Coruña (A)", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "morales-alvarez-alvaro", fullName: "Morales Álvarez, Álvaro", constituency: "Burgos", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "moreno-borras-cristina", fullName: "Moreno Borrás, Cristina", constituency: "Valencia/València", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "moreno-fernandez-m-isabel", fullName: "Moreno Fernández, Mª Isabel", constituency: "Cádiz", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "moro-almaraz-maria-jesus", fullName: "Moro Almaraz, María Jesús", constituency: "Salamanca", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "munoz-abrines-pedro", fullName: "Muñoz Abrines, Pedro", constituency: "Madrid", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "munoz-de-la-iglesia-ester", fullName: "Muñoz de la Iglesia, Ester", constituency: "León", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "nacarino-brabo-jimenez-aurora", fullName: "Nacarino-Brabo Jiménez, Aurora", constituency: "Madrid", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "narbona-ruiz-cristina", fullName: "Narbona Ruiz, Cristina", constituency: "Madrid", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "nasarre-oliva-begona", fullName: "Nasarre Oliva, Begoña", constituency: "Huesca", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "navarro-lacoba-carmen", fullName: "Navarro Lacoba, Carmen", constituency: "Albacete", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "navarro-lopez-pedro", fullName: "Navarro López, Pedro", constituency: "Zaragoza", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "nogueras-i-camero-miriam", fullName: "Nogueras i Camero, Míriam", constituency: "Barcelona", electoralFormation: "JxCAT-JUNTS", parliamentaryGroup: "Grupo Parlamentario Junts per Catalunya" },
  { slug: "noriega-gomez-javier", fullName: "Noriega Gómez, Javier", constituency: "Cantabria", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "nunez-feijoo-alberto", fullName: "Núñez Feijóo, Alberto", constituency: "Madrid", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "nunez-guijarro-jose-enrique", fullName: "Núñez Guijarro, José Enrique", constituency: "Madrid", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "ogou-i-corbi-viviane", fullName: "Ogou i Corbi, Viviane", constituency: "Barcelona", electoralFormation: "SUMAR", parliamentaryGroup: "Grupo Parlamentario Plurinacional SUMAR" },
  { slug: "olano-vela-jaime-eduardo-de", fullName: "Olano Vela, Jaime Eduardo de", constituency: "Lugo", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "ortega-smith-molina-francisco-javier", fullName: "Ortega Smith-Molina, Francisco Javier", constituency: "Madrid", electoralFormation: "VOX", parliamentaryGroup: "Grupo Parlamentario VOX" },
  { slug: "otero-gabirondo-mikel", fullName: "Otero Gabirondo, Mikel", constituency: "Araba/Álava", electoralFormation: "EH Bildu", parliamentaryGroup: "Grupo Parlamentario Euskal Herria Bildu" },
  { slug: "otero-garcia-mercedes", fullName: "Otero García, Mercedes", constituency: "Asturias", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "otero-rodriguez-patricia", fullName: "Otero Rodríguez, Patricia", constituency: "Lugo", electoralFormation: "PsdeG-PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "pages-i-masso-josep", fullName: "Pagès i Massó, Josep", constituency: "Barcelona", electoralFormation: "JxCAT-JUNTS", parliamentaryGroup: "Grupo Parlamentario Junts per Catalunya" },
  { slug: "palencia-rubio-hector", fullName: "Palencia Rubio, Héctor", constituency: "Ávila", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "paniagua-nunez-miguel-angel", fullName: "Paniagua Núñez, Miguel Ángel", constituency: "Palencia", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "pare-aregall-josep", fullName: "Paré Aregall, Josep", constituency: "Barcelona", electoralFormation: "PSC-PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "parra-aparicio-julia", fullName: "Parra Aparicio, Julia", constituency: "Alicante/Alacant", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "parra-gallego-agustin", fullName: "Parra Gallego, Agustín", constituency: "Barcelona", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "pascual-rocamora-sandra", fullName: "Pascual Rocamora, Sandra", constituency: "Alicante/Alacant", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "pedreno-molina-juan-luis", fullName: "Pedreño Molina, Juan Luis", constituency: "Murcia", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "pena-camarero-esther", fullName: "Peña Camarero, Esther", constituency: "Burgos", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "perea-i-conillas-maria-merce", fullName: "Perea i Conillas, María Mercè", constituency: "Barcelona", electoralFormation: "PSC-PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "perez-coronado-pablo", fullName: "Pérez Coronado, Pablo", constituency: "Segovia", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "perez-lopez-alvaro", fullName: "Pérez López, Álvaro", constituency: "Coruña (A)", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "perez-ortiz-isabel-maria", fullName: "Pérez Ortiz, Isabel María", constituency: "Málaga", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "perez-osma-daniel", fullName: "Pérez Osma, Daniel", constituency: "Cuenca", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "perez-recuerda-isabel-gema", fullName: "Pérez Recuerda, Isabel Gema", constituency: "Málaga", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "pisarello-prados-gerardo", fullName: "Pisarello Prados, Gerardo", constituency: "Barcelona", electoralFormation: "SUMAR", parliamentaryGroup: "Grupo Parlamentario Plurinacional SUMAR" },
  { slug: "plaza-garcia-ines", fullName: "Plaza García, Inés", constituency: "Almería", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "poblador-pacheco-maria-araceli", fullName: "Poblador Pacheco, María Araceli", constituency: "Alicante/Alacant", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "pose-mesura-modesto", fullName: "Pose Mesura, Modesto", constituency: "Pontevedra", electoralFormation: "PsdeG-PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "pozueta-fernandez-isabel", fullName: "Pozueta Fernández, Isabel", constituency: "Navarra", electoralFormation: "EH Bildu", parliamentaryGroup: "Grupo Parlamentario Euskal Herria Bildu" },
  { slug: "prieto-serrano-maria-isabel", fullName: "Prieto Serrano, María Isabel", constituency: "Córdoba", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "puente-santiago-oscar", fullName: "Puente Santiago, Óscar", constituency: "Valladolid", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "puy-fraga-pedro", fullName: "Puy Fraga, Pedro", constituency: "Pontevedra", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "quintana-carballo-rosa", fullName: "Quintana Carballo, Rosa", constituency: "Ourense", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "quintanilla-navarro-miguel-angel", fullName: "Quintanilla Navarro, Miguel Ángel", constituency: "Madrid", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "quintero-hernandez-jonay", fullName: "Quintero Hernández, Jonay", constituency: "S/C Tenerife", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "rallo-lombarte-artemi", fullName: "Rallo Lombarte, Artemi", constituency: "Castellón/Castelló", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "ramajo-prada-oscar", fullName: "Ramajo Prada, Óscar", constituency: "Zamora", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "ramirez-carner-arnau", fullName: "Ramírez Carner, Arnau", constituency: "Barcelona", electoralFormation: "PSC-PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "ramirez-del-rio-jose", fullName: "Ramírez del Río, José", constituency: "Córdoba", electoralFormation: "VOX", parliamentaryGroup: "Grupo Parlamentario VOX" },
  { slug: "ramirez-martin-maria-lourdes", fullName: "Ramírez Martín, María Lourdes", constituency: "Granada", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "ramirez-moreno-maria-de-las-nieves", fullName: "Ramírez Moreno, María de las Nieves", constituency: "Málaga", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "ramos-esteban-cesar-joaquin", fullName: "Ramos Esteban, César Joaquín", constituency: "Cáceres", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "recas-martin-alda", fullName: "Recas Martín, Alda", constituency: "Madrid", electoralFormation: "SUMAR", parliamentaryGroup: "Grupo Parlamentario Plurinacional SUMAR" },
  { slug: "redondo-cardenas-gonzalo", fullName: "Redondo Cárdenas, Gonzalo", constituency: "Ciudad Real", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "rego-candamil-nestor", fullName: "Rego Candamil, Néstor", constituency: "Coruña (A)", electoralFormation: "BNG", parliamentaryGroup: "Grupo Parlamentario Mixto" },
  { slug: "renteria-lasanta-nerea", fullName: "Renteria Lasanta, Nerea", constituency: "Bizkaia", electoralFormation: "EAJ-PNV", parliamentaryGroup: "Grupo Parlamentario Vasco (EAJ-PNV)" },
  { slug: "requena-ruiz-juan-diego", fullName: "Requena Ruiz, Juan Diego", constituency: "Jaén", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "rey-de-las-heras-luis-alfonso", fullName: "Rey de las Heras, Luis Alfonso", constituency: "Soria", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "reynal-reillo-esperanza", fullName: "Reynal Reillo, Esperanza", constituency: "Valencia/València", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "rivera-arias-engracia", fullName: "Rivera Arias, Engracia", constituency: "Sevilla", electoralFormation: "SUMAR", parliamentaryGroup: "Grupo Parlamentario Plurinacional SUMAR" },
  { slug: "rives-arcayna-caridad", fullName: "Rives Arcayna, Caridad", constituency: "Murcia", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "robles-lopez-joaquin", fullName: "Robles López, Joaquín", constituency: "Murcia", electoralFormation: "VOX", parliamentaryGroup: "Grupo Parlamentario VOX" },
  { slug: "rodriguez-almeida-andres-alberto", fullName: "Rodríguez Almeida, Andrés Alberto", constituency: "Palmas (Las)", electoralFormation: "VOX", parliamentaryGroup: "Grupo Parlamentario VOX" },
  { slug: "rodriguez-calleja-patricia", fullName: "Rodríguez Calleja, Patricia", constituency: "Ávila", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "rodriguez-de-millan-parro-maria-jose", fullName: "Rodríguez de Millán Parro, María José", constituency: "Madrid", electoralFormation: "VOX", parliamentaryGroup: "Grupo Parlamentario VOX" },
  { slug: "rodriguez-gomez-de-celis-alfonso", fullName: "Rodríguez Gómez de Celis, Alfonso", constituency: "Sevilla", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "rodriguez-herrer-maria-elvira", fullName: "Rodríguez Herrer, María Elvira", constituency: "Madrid", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "rodriguez-palacios-javier", fullName: "Rodríguez Palacios, Javier", constituency: "Madrid", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "rodriguez-salas-jose-antonio", fullName: "Rodríguez Salas, José Antonio", constituency: "Granada", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "rodriguez-serra-santi", fullName: "Rodríguez Serra, Santi", constituency: "Barcelona", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "rodriguez-suarez-esther", fullName: "Rodríguez Suárez, Esther", constituency: "S/C Tenerife", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "rojas-garcia-carlos", fullName: "Rojas García, Carlos", constituency: "Granada", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "rojas-manrique-juan-antonio", fullName: "Rojas Manrique, Juan Antonio", constituency: "S/C Tenerife", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "rojo-blas-alberto", fullName: "Rojo Blas, Alberto", constituency: "Guadalajara", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "roman-jasanada-antonio", fullName: "Román Jasanada, Antonio", constituency: "Guadalajara", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "romani-cantera-jose-ignacio", fullName: "Romaní Cantera, José Ignacio", constituency: "Cádiz", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "romero-pozo-rafaela", fullName: "Romero Pozo, Rafaela", constituency: "Gipuzkoa", electoralFormation: "PSE-EE (PSOE)", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "romero-vilches-maria-de-los-reyes", fullName: "Romero Vilches, María de los Reyes", constituency: "Sevilla", electoralFormation: "VOX", parliamentaryGroup: "Grupo Parlamentario VOX" },
  { slug: "ros-martinez-susana", fullName: "Ros Martínez, Susana", constituency: "Castellón/Castelló", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "rueda-perello-patricia", fullName: "Rueda Perelló, Patricia", constituency: "Málaga", electoralFormation: "VOX", parliamentaryGroup: "Grupo Parlamentario VOX" },
  { slug: "rufian-romero-gabriel", fullName: "Rufián Romero, Gabriel", constituency: "Barcelona", electoralFormation: "ERC", parliamentaryGroup: "Grupo Parlamentario Republicano" },
  { slug: "ruiz-boix-juan-carlos", fullName: "Ruiz Boix, Juan Carlos", constituency: "Cádiz", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "ruiz-de-diego-victor-javier", fullName: "Ruiz de Diego, Víctor Javier", constituency: "Zaragoza", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "ruiz-solas-maria-de-la-cabeza", fullName: "Ruiz Solás, María de la Cabeza", constituency: "Madrid", electoralFormation: "VOX", parliamentaryGroup: "Grupo Parlamentario VOX" },
  { slug: "saez-alonso-munumer-pablo", fullName: "Sáez Alonso-Muñumer, Pablo", constituency: "Valladolid", electoralFormation: "VOX", parliamentaryGroup: "Grupo Parlamentario VOX" },
  { slug: "saez-cruz-emilio", fullName: "Sáez Cruz, Emilio", constituency: "Albacete", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "sagastizabal-unzetabarrenetxea-idoia", fullName: "Sagastizabal Unzetabarrenetxea, Idoia", constituency: "Bizkaia", electoralFormation: "EAJ-PNV", parliamentaryGroup: "Grupo Parlamentario Vasco (EAJ-PNV)" },
  { slug: "sahuquillo-garcia-luis-carlos", fullName: "Sahuquillo García, Luis Carlos", constituency: "Cuenca", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "sainz-martin-maria", fullName: "Sainz Martín, María", constituency: "Madrid", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "salvador-i-duch-jordi", fullName: "Salvador i Duch, Jordi", constituency: "Tarragona", electoralFormation: "ERC", parliamentaryGroup: "Grupo Parlamentario Republicano" },
  { slug: "sanchez-diaz-maria-carmen", fullName: "Sánchez Díaz, María Carmen", constituency: "Cádiz", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "sanchez-garcia-jose-maria", fullName: "Sánchez García, José María", constituency: "Alicante/Alacant", electoralFormation: "VOX", parliamentaryGroup: "Grupo Parlamentario VOX" },
  { slug: "sanchez-ojeda-carlos-alberto", fullName: "Sánchez Ojeda, Carlos Alberto", constituency: "Palmas (Las)", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "sanchez-perez-cesar", fullName: "Sánchez Pérez, César", constituency: "Alicante/Alacant", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "sanchez-perez-castejon-pedro", fullName: "Sánchez Pérez-Castejón, Pedro", constituency: "Madrid", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "sanchez-serna-javier", fullName: "Sánchez Serna, Javier", constituency: "Murcia", electoralFormation: "SUMAR", parliamentaryGroup: "Grupo Parlamentario Mixto" },
  { slug: "sanchez-sierra-maria-del-mar", fullName: "Sánchez Sierra, María del Mar", constituency: "Madrid", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "sanchez-torregrosa-maribel", fullName: "Sánchez Torregrosa, Maribel", constituency: "Almería", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "sancho-iniguez-herminio-rufino", fullName: "Sancho Íñiguez, Herminio Rufino", constituency: "Teruel", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "santana-aguilera-ada", fullName: "Santana Aguilera, Ada", constituency: "Palmas (Las)", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "santana-perera-noemi", fullName: "Santana Perera, Noemí", constituency: "Palmas (Las)", electoralFormation: "SUMAR", parliamentaryGroup: "Grupo Parlamentario Mixto" },
  { slug: "santiago-romero-enrique-fernando", fullName: "Santiago Romero, Enrique Fernando", constituency: "Córdoba", electoralFormation: "SUMAR", parliamentaryGroup: "Grupo Parlamentario Plurinacional SUMAR" },
  { slug: "santos-maraver-agustin", fullName: "Santos Maraver, Agustín", constituency: "Madrid", electoralFormation: "SUMAR", parliamentaryGroup: "Grupo Parlamentario Plurinacional SUMAR" },
  { slug: "sanz-martinez-luisa", fullName: "Sanz Martínez, Luisa", constituency: "Valladolid", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "sarria-morell-vicent-manuel", fullName: "Sarrià Morell, Vicent Manuel", constituency: "Valencia/València", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "sastre-uya-miguel-angel", fullName: "Sastre Uyá, Miguel Ángel", constituency: "Cádiz", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "sayas-lopez-sergio", fullName: "Sayas López, Sergio", constituency: "Navarra", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "semper-pascual-borja", fullName: "Sémper Pascual, Borja", constituency: "Madrid", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "senderos-oraa-daniel", fullName: "Senderos Oraá, Daniel", constituency: "Araba/Álava", electoralFormation: "PSE-EE (PSOE)", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "serrada-pariente-david", fullName: "Serrada Pariente, David", constituency: "Salamanca", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "serrano-martinez-juan-francisco", fullName: "Serrano Martínez, Juan Francisco", constituency: "Jaén", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "sierra-caballero-francisco", fullName: "Sierra Caballero, Francisco", constituency: "Sevilla", electoralFormation: "SUMAR", parliamentaryGroup: "Grupo Parlamentario Plurinacional SUMAR" },
  { slug: "simancas-simancas-rafael", fullName: "Simancas Simancas, Rafael", constituency: "Madrid", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "simarro-vicens-carlos", fullName: "Simarro Vicens, Carlos", constituency: "Balears (Illes)", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "soldevilla-novials-alba", fullName: "Soldevilla Novials, Alba", constituency: "Barcelona", electoralFormation: "PSC-PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "soler-mur-alejandro", fullName: "Soler Mur, Alejandro", constituency: "Alicante/Alacant", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "taboadela-alvarez-obdulia", fullName: "Taboadela Álvarez, Obdulia", constituency: "Coruña (A)", electoralFormation: "PsdeG-PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "tarno-blanco-ricardo", fullName: "Tarno Blanco, Ricardo", constituency: "Sevilla", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "tellado-filgueira-miguel", fullName: "Tellado Filgueira, Miguel", constituency: "Coruña (A)", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "teniente-sanchez-cristina", fullName: "Teniente Sánchez, Cristina", constituency: "Cáceres", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "tomas-olivares-violante", fullName: "Tomás Olivares, Violante", constituency: "Murcia", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "torres-tejada-maria", fullName: "Torres Tejada, María", constituency: "Jaén", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "trenzano-rubio-marta", fullName: "Trenzano Rubio, Marta", constituency: "Valencia/València", electoralFormation: "PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "uriarte-bengoechea-edurne", fullName: "Uriarte Bengoechea, Edurne", constituency: "Madrid", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "valero-morales-juan-antonio", fullName: "Valero Morales, Juan Antonio", constituency: "Málaga", electoralFormation: "SUMAR", parliamentaryGroup: "Grupo Parlamentario Plurinacional SUMAR" },
  { slug: "valido-garcia-cristina", fullName: "Valido García, Cristina", constituency: "S/C Tenerife", electoralFormation: "CCa", parliamentaryGroup: "Grupo Parlamentario Mixto" },
  { slug: "vallugera-balana-pilar", fullName: "Vallugera Balañà, Pilar", constituency: "Barcelona", electoralFormation: "ERC", parliamentaryGroup: "Grupo Parlamentario Republicano" },
  { slug: "vaquero-montero-maribel", fullName: "Vaquero Montero, Maribel", constituency: "Gipuzkoa", electoralFormation: "EAJ-PNV", parliamentaryGroup: "Grupo Parlamentario Vasco (EAJ-PNV)" },
  { slug: "varela-pazos-marta", fullName: "Varela Pazos, Marta", constituency: "Madrid", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "vazquez-blanco-ana-belen", fullName: "Vázquez Blanco, Ana Belén", constituency: "Ourense", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "vazquez-jimenez-maria-del-mar", fullName: "Vázquez Jiménez, María del Mar", constituency: "Málaga", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "vedrina-conesa-maria-elisa", fullName: "Vedrina Conesa, María Elisa", constituency: "Tarragona", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "velarde-gomez-martina", fullName: "Velarde Gómez, Martina", constituency: "Granada", electoralFormation: "SUMAR", parliamentaryGroup: "Grupo Parlamentario Mixto" },
  { slug: "velasco-morillo-elvira", fullName: "Velasco Morillo, Elvira", constituency: "Zamora", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "velasco-retamosa-jose-manuel", fullName: "Velasco Retamosa, José Manuel", constituency: "Toledo", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "verano-dominguez-bella", fullName: "Verano Domínguez, Bella", constituency: "Huelva", electoralFormation: "PP", parliamentaryGroup: "Grupo Parlamentario Popular en el Congreso" },
  { slug: "verdejo-vicente-ferran", fullName: "Verdejo Vicente, Ferran", constituency: "Barcelona", electoralFormation: "PSC-PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
  { slug: "vergara-roman-laura", fullName: "Vergara Román, Laura", constituency: "Zaragoza", electoralFormation: "SUMAR", parliamentaryGroup: "Grupo Parlamentario Plurinacional SUMAR" },
  { slug: "vidal-matas-vicenc", fullName: "Vidal Matas, Vicenç", constituency: "Balears (Illes)", electoralFormation: "SUMAR", parliamentaryGroup: "Grupo Parlamentario Plurinacional SUMAR" },
  { slug: "vidal-saez-aina", fullName: "Vidal Sáez, Aina", constituency: "Barcelona", electoralFormation: "SUMAR", parliamentaryGroup: "Grupo Parlamentario Plurinacional SUMAR" },
  { slug: "zaragoza-alonso-jose", fullName: "Zaragoza Alonso, José", constituency: "Barcelona", electoralFormation: "PSC-PSOE", parliamentaryGroup: "Grupo Parlamentario Socialista" },
];

export const parliamentaryGroups = [
  { slug: "grupo-parlamentario-popular-en-el-congreso", name: "Grupo Parlamentario Popular en el Congreso", seats: 137 },
  { slug: "grupo-parlamentario-socialista", name: "Grupo Parlamentario Socialista", seats: 121 },
  { slug: "grupo-parlamentario-vox", name: "Grupo Parlamentario VOX", seats: 33 },
  { slug: "grupo-parlamentario-plurinacional-sumar", name: "Grupo Parlamentario Plurinacional SUMAR", seats: 26 },
  { slug: "grupo-parlamentario-mixto", name: "Grupo Parlamentario Mixto", seats: 8 },
  { slug: "grupo-parlamentario-republicano", name: "Grupo Parlamentario Republicano", seats: 7 },
  { slug: "grupo-parlamentario-junts-per-catalunya", name: "Grupo Parlamentario Junts per Catalunya", seats: 7 },
  { slug: "grupo-parlamentario-euskal-herria-bildu", name: "Grupo Parlamentario Euskal Herria Bildu", seats: 6 },
  { slug: "grupo-parlamentario-vasco-eaj-pnv", name: "Grupo Parlamentario Vasco (EAJ-PNV)", seats: 5 },
];
